import { StyleSheet } from 'react-native';

const cardShadow = {
  shadowColor: '#17213A',
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: 0.06,
  shadowRadius: 12,
  elevation: 2,
};

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F5F7FA' },
  content: { flexGrow: 1, paddingHorizontal: 20, paddingTop: 24 },
  eyebrow: { color: '#1257E0', fontSize: 12, fontWeight: '900', letterSpacing: 1.2 },
  title: { marginTop: 7, color: '#17191C', fontSize: 29, lineHeight: 38, fontWeight: '800', letterSpacing: -0.8 },
  description: { marginTop: 8, color: '#687180', fontSize: 14, lineHeight: 21 },
  sectionLabel: { marginTop: 24, marginBottom: 10, color: '#536071', fontSize: 13, fontWeight: '800' },
  periodRow: { flexDirection: 'row', gap: 8 },
  periodButton: { flex: 1, minHeight: 46, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#E2E6EC', borderRadius: 14, backgroundColor: '#FFFFFF' },
  selectedPeriod: { borderColor: '#17191C', backgroundColor: '#17191C' },
  periodButtonText: { color: '#687180', fontSize: 13, fontWeight: '800' },
  selectedPeriodText: { color: '#FFFFFF' },
  customDates: { ...cardShadow, marginTop: 10, padding: 16, borderWidth: 1, borderColor: '#E8EBF0', borderRadius: 18, backgroundColor: '#FFFFFF' },
  datePickerItem: { minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  datePickerLabel: { color: '#536071', fontSize: 13, fontWeight: '700' },
  customHint: { marginTop: 8, color: '#8B919B', fontSize: 12, lineHeight: 18 },
  statusCard: { ...cardShadow, minHeight: 240, alignItems: 'center', justifyContent: 'center', marginTop: 18, padding: 24, borderRadius: 22, backgroundColor: '#FFFFFF' },
  skeletonWrap: { marginTop: 18 },
  skeletonBaseline: { height: 180, borderRadius: 22, backgroundColor: '#E8EBF0' },
  skeletonChart: { height: 310, marginTop: 14, padding: 18, borderRadius: 22, backgroundColor: '#FFFFFF' },
  skeletonLineShort: { width: '42%', height: 18, borderRadius: 8, backgroundColor: '#E8EBF0' },
  skeletonLine: { width: '68%', height: 12, marginTop: 10, borderRadius: 6, backgroundColor: '#F0F2F5' },
  skeletonGraph: { flex: 1, marginTop: 24, borderRadius: 16, backgroundColor: '#F3F5F7' },
  statusText: { marginTop: 10, textAlign: 'center', color: '#687180', fontSize: 14, lineHeight: 21 },
  errorTitle: { color: '#17191C', fontSize: 18, fontWeight: '800', textAlign: 'center' },
  retryButton: { minWidth: 116, minHeight: 46, alignItems: 'center', justifyContent: 'center', marginTop: 16, borderRadius: 14, backgroundColor: '#E8F0FF' },
  retryText: { color: '#1257E0', fontSize: 13, fontWeight: '800' },
  baseline: { ...cardShadow, marginTop: 18, padding: 19, borderRadius: 22, backgroundColor: '#182033' },
  cardHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 },
  baselineEyebrow: { color: '#8EB0F6', fontSize: 12, fontWeight: '800' },
  baselineTitle: { marginTop: 6, color: '#FFFFFF', fontSize: 20, fontWeight: '800' },
  baselineCount: { color: '#AFC7FA', fontSize: 13, fontWeight: '800' },
  baselineGrid: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 14 },
  base: { width: '50%', paddingVertical: 10 },
  baseLabel: { color: '#AEB6C4', fontSize: 11 },
  baseValue: { marginTop: 5, color: '#FFFFFF', fontSize: 15, fontWeight: '800' },
  comparison: { marginTop: 10, padding: 13, overflow: 'hidden', borderRadius: 13, color: '#DDE7FA', backgroundColor: '#26324A', fontSize: 12, lineHeight: 18 },
  progressTrack: { height: 8, overflow: 'hidden', marginTop: 20, borderRadius: 4, backgroundColor: '#354055' },
  progressFill: { height: 8, borderRadius: 4, backgroundColor: '#6B9BFA' },
  baselineGuide: { marginTop: 11, color: '#C2CAD8', fontSize: 12, lineHeight: 18 },
  chartCard: { ...cardShadow, marginTop: 14, padding: 17, borderRadius: 22, backgroundColor: '#FFFFFF' },
  cardTitle: { color: '#17191C', fontSize: 18, fontWeight: '800' },
  cardDescription: { marginTop: 5, color: '#7B8492', fontSize: 12 },
  selectedCount: { minWidth: 40, paddingVertical: 5, textAlign: 'center', overflow: 'hidden', borderRadius: 10, color: '#1257E0', backgroundColor: '#EEF3FF', fontSize: 12, fontWeight: '800' },
  metricChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 17 },
  metricChip: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 7, paddingHorizontal: 12, borderWidth: 1, borderColor: '#DDE2E9', borderRadius: 14, backgroundColor: '#FAFBFC' },
  metricDot: { width: 8, height: 8, borderRadius: 4 },
  metricText: { color: '#465163', fontSize: 12, fontWeight: '700' },
  selectionNotice: { marginTop: 10, color: '#C95C2A', fontSize: 12, lineHeight: 18 },
  legend: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginTop: 15 },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  legendLine: { width: 16, height: 3, borderRadius: 2 },
  legendText: { color: '#687180', fontSize: 10 },
  chartHint: { marginTop: 2, textAlign: 'center', color: '#7B8492', fontSize: 11, lineHeight: 17 },
  patternHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 30, marginBottom: 12 },
  sectionTitle: { color: '#17191C', fontSize: 21, fontWeight: '800' },
  sectionDescription: { marginTop: 5, color: '#7B8492', fontSize: 12 },
  count: { color: '#1257E0', fontSize: 13, fontWeight: '800' },
  patternCard: { ...cardShadow, minHeight: 158, flexDirection: 'row', overflow: 'hidden', marginBottom: 12, borderRadius: 20, backgroundColor: '#FFFFFF' },
  patternAccent: { width: 6 },
  primaryAccent: { backgroundColor: '#1257E0' },
  cautionAccent: { backgroundColor: '#F2A65A' },
  dangerAccent: { backgroundColor: '#E5484D' },
  patternBody: { flex: 1, padding: 18 },
  patternTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  patternMetric: { color: '#1257E0', fontSize: 12, fontWeight: '800' },
  chevron: { color: '#8B919B', fontSize: 24 },
  confidence: { alignSelf: 'flex-start', marginTop: 6, paddingHorizontal: 9, paddingVertical: 5, overflow: 'hidden', borderRadius: 8, color: '#465163', backgroundColor: '#EEF1F5', fontSize: 10, fontWeight: '800' },
  patternTitle: { marginTop: 9, color: '#17191C', fontSize: 16, lineHeight: 23, fontWeight: '800' },
  patternSummary: { marginTop: 6, color: '#687180', fontSize: 12, lineHeight: 19 },
  lowCard: { ...cardShadow, marginTop: 8, padding: 18, borderRadius: 20, backgroundColor: '#FFFFFF' },
  lowEyebrow: { color: '#238A59', fontSize: 12, fontWeight: '800' },
  lowText: { marginTop: 8, color: '#343941', fontSize: 14, lineHeight: 21, fontWeight: '700' },
  lowNote: { marginTop: 8, color: '#7B8492', fontSize: 12, lineHeight: 18 },
  guideCard: { marginTop: 12, padding: 18, borderWidth: 1, borderColor: '#DCE7FC', borderRadius: 20, backgroundColor: '#EEF3FF' },
  guideTitle: { color: '#315994', fontSize: 14, fontWeight: '800' },
  guideText: { marginTop: 6, color: '#536B9C', fontSize: 12, lineHeight: 19 },
  pressed: { opacity: 0.62, transform: [{ scale: 0.99 }] },
  overlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(16,20,25,0.42)' },
  sheet: { maxHeight: '78%', paddingHorizontal: 22, paddingTop: 10, borderTopLeftRadius: 28, borderTopRightRadius: 28, backgroundColor: '#FFFFFF' },
  grabber: { width: 40, height: 5, alignSelf: 'center', borderRadius: 3, backgroundColor: '#D5D9DF' },
  sheetHeader: { minHeight: 64, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  sheetTitle: { color: '#17191C', fontSize: 20, fontWeight: '800' },
  close: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 22, backgroundColor: '#F3F5F7' },
  closeText: { color: '#687180', fontSize: 27, lineHeight: 30 },
  sheetRow: { minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 16, borderTopWidth: 1, borderTopColor: '#EEF0F3' },
  sheetLabel: { color: '#7B8492', fontSize: 12 },
  sheetValue: { flex: 1, textAlign: 'right', color: '#343941', fontSize: 13, lineHeight: 19, fontWeight: '700' },
});
