import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F7F8FA' }, content: { paddingHorizontal: 20, paddingTop: 24 },
  eyebrow: { color: '#1257E0', fontSize: 13, fontWeight: '800' }, title: { marginTop: 5, color: '#17191C', fontSize: 30, lineHeight: 39, fontWeight: '800', letterSpacing: -1 }, description: { marginTop: 7, color: '#737B88', fontSize: 14, lineHeight: 21 },
  dateCard: { marginTop: 22, padding: 14, borderRadius: 20, backgroundColor: '#FFFFFF' }, cardLabel: { marginLeft: 4, marginBottom: 10, color: '#737B88', fontSize: 12, fontWeight: '700' }, dateRow: { flexGrow: 1, justifyContent: 'space-between', gap: 5 }, dateButton: { width: 42, minHeight: 58, alignItems: 'center', justifyContent: 'center', borderRadius: 14, backgroundColor: '#F7F8FA' }, selectedDateButton: { backgroundColor: '#17191C' }, weekday: { color: '#8B919B', fontSize: 10, fontWeight: '700' }, day: { marginTop: 5, color: '#343941', fontSize: 15, fontWeight: '800' }, selectedDateText: { color: '#FFFFFF' }, pressed: { opacity: 0.55 },
  period: { marginTop: 18, marginBottom: -2, color: '#737B88', fontSize: 12, fontWeight: '700' }, chartCard: { marginTop: 12, padding: 16, borderRadius: 20, backgroundColor: '#FFFFFF' }, chartHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 4 }, chartTitle: { color: '#17191C', fontSize: 16, fontWeight: '800' }, chartValue: { color: '#1257E0', fontSize: 12, fontWeight: '800' },
  statusCard: { minHeight: 220, alignItems: 'center', justifyContent: 'center', marginTop: 18, padding: 24, borderRadius: 20, backgroundColor: '#FFFFFF' }, statusText: { marginTop: 10, textAlign: 'center', color: '#737B88', fontSize: 13, lineHeight: 20 }, errorTitle: { color: '#17191C', fontSize: 17, fontWeight: '800' }, retryButton: { minWidth: 104, minHeight: 44, alignItems: 'center', justifyContent: 'center', marginTop: 14, borderRadius: 12, backgroundColor: '#EEF3FF' }, retryText: { color: '#1257E0', fontSize: 13, fontWeight: '800' },
  patternHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 28, marginBottom: 10 }, sectionTitle: { color: '#17191C', fontSize: 21, fontWeight: '800' }, sectionDescription: { marginTop: 4, color: '#8B919B', fontSize: 12 }, count: { color: '#1257E0', fontSize: 13, fontWeight: '800' }, patternCard: { minHeight: 142, flexDirection: 'row', overflow: 'hidden', marginBottom: 10, borderRadius: 18, backgroundColor: '#FFFFFF' }, patternAccent: { width: 6 }, primaryAccent: { backgroundColor: '#1257E0' }, cautionAccent: { backgroundColor: '#F2A65A' }, dangerAccent: { backgroundColor: '#E5484D' }, patternBody: { flex: 1, padding: 17 }, patternTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, patternMetric: { color: '#1257E0', fontSize: 12, fontWeight: '800' }, chevron: { color: '#9AA0AA', fontSize: 24 }, patternTitle: { marginTop: 6, color: '#17191C', fontSize: 16, lineHeight: 23, fontWeight: '800' }, patternSummary: { marginTop: 6, color: '#737B88', fontSize: 12, lineHeight: 19 },
});
