import { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import ConnectionOverlayChart from '@/components/charts/connection-overlay-chart';
import { AppIcon } from '@/components/app-icon';
import type { ConnectionMetricId, DiscoverSummary } from '@/domain/wellness';
import { useAsyncData } from '@/hooks/use-async-data';
import { wellnessApi } from '@/services/wellness-api';
import { colors, dataColors } from '@/theme/tokens';
import { styles } from './connection-view.styles';

type Period = '7' | '14' | '30';
const EMPTY: DiscoverSummary = { startDate: '', endDate: '', availableDates: [], periodLabel: '', labels: [], sleepValues: [], conditionValues: [], activityValues: [], metrics: [], patterns: [], dayDetails: [], lowRelations: [], moreDataGuide: '', analysisReadiness: { ready: false, recordedDays: 0, requiredDays: 30 }, baseline: { ready: false, recordedDays: 0, targetDays: 14, averageSleep: '', averageSteps: '', averageBedtime: '', discomfortFrequency: '', comparison: '' } };
function dateId() { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`; }

export default function DiscoverScreen() {
  const router = useRouter(); const insets = useSafeAreaInsets(); const [period, setPeriod] = useState<Period>('14'); const [selected, setSelected] = useState<ConnectionMetricId[]>(['sleep', 'discomfort']); const [point, setPoint] = useState<number | null>(null);
  const loader = useCallback(() => wellnessApi.getDiscoverSummary(dateId(), Number(period)), [period]);
  const { data, error, isLoading, reload } = useAsyncData<DiscoverSummary | null>(loader, null);
  const metrics = useMemo(() => data?.metrics.map((metric) => ({ ...metric, color: dataColors[metric.id] })).filter((metric) => selected.includes(metric.id)) ?? [], [data, selected]);
  const toggle = (id: ConnectionMetricId) => setSelected((current) => current.includes(id) ? (current.length === 1 ? current : current.filter((item) => item !== id)) : current.length < 3 ? [...current, id] : current);
  return <SafeAreaView edges={['top']} style={styles.screen}><ScrollView contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + 148 }]} showsVerticalScrollIndicator={false}>
    <Text style={styles.kicker}>DISCOVER / 02</Text><Text style={styles.title}>내 기록의 관계를{`\n`}한눈에 살펴보세요.</Text><Text style={styles.description}>수면과 활동, 불편 기록을 같은 시간축에 놓고 반복되는 흐름을 확인합니다.</Text>
    <View style={styles.periodHeader}><Text style={styles.sectionLabel}>기간</Text><View style={styles.periods}>{(['7', '14', '30'] as Period[]).map((value) => <Pressable key={value} accessibilityRole="button" accessibilityState={{ selected: period === value }} onPress={() => setPeriod(value)} style={[styles.period, period === value && styles.periodSelected]}><Text style={[styles.periodText, period === value && styles.periodTextSelected]}>{value}일</Text></Pressable>)}</View></View>
    {isLoading ? <View style={styles.statusCard}><ActivityIndicator color={colors.primary} /><Text style={styles.statusText}>기록의 관계를 읽고 있어요</Text></View> : error || !data ? <View style={styles.statusCard}><Text style={styles.statusTitle}>커넥션을 불러오지 못했어요</Text><Text style={styles.statusText}>잠시 후 다시 시도해 주세요.</Text><Pressable onPress={() => void reload().catch(() => undefined)} style={styles.retryButton}><Text style={styles.retryText}>다시 시도</Text></Pressable></View> : <>
      <View style={styles.baseline}><Text style={styles.cardKicker}>YOUR BASELINE</Text><View style={styles.baselineTop}><View><Text style={styles.baselineTitle}>{data.baseline.ready ? '나의 평소 상태' : '기준선을 알아가는 중'}</Text><Text style={styles.baselineCopy}>{data.baseline.ready ? data.baseline.comparison : `${data.baseline.recordedDays}/${data.baseline.targetDays}일 기록됨`}</Text></View><Text style={styles.baselineValue}>{data.baseline.averageSleep || '-'}</Text></View><View style={styles.baselineRule}><View style={[styles.baselineFill, { width: `${Math.min(100, data.baseline.recordedDays / data.baseline.targetDays * 100)}%` }]} /></View></View>
      <View style={styles.chartSection}><View style={styles.sectionHead}><View><Text style={styles.cardKicker}>COMPARE</Text><Text style={styles.sectionTitle}>기록 겹쳐보기</Text></View><Text style={styles.selection}>{selected.length}/3</Text></View><View style={styles.metricList}>{data.metrics.map((metric, index) => <Pressable key={metric.id} onPress={() => toggle(metric.id)} style={[styles.metricRow, selected.includes(metric.id) && styles.metricRowSelected]}><View style={[styles.metricDot, { backgroundColor: dataColors[metric.id] }]} /><Text style={styles.metricName}>{String(index + 1).padStart(2, '0')}  {metric.label}</Text><Text style={styles.metricState}>{selected.includes(metric.id) ? '선택됨' : '추가'}</Text></Pressable>)}</View><View style={styles.chart}><ConnectionOverlayChart labels={data.labels} metrics={metrics} onPointPress={setPoint} selectedIndex={point} /></View><Text style={styles.chartHint}>날짜를 선택하면 그날의 기록을 확인할 수 있어요.</Text></View>
      <View style={styles.patternSection}><View style={styles.sectionHead}><View><Text style={styles.cardKicker}>READING</Text><Text style={styles.sectionTitle}>발견된 흐름</Text></View><Text style={styles.selection}>{data.patterns.length}개</Text></View>{data.patterns.length ? data.patterns.map((pattern) => <Pressable key={pattern.id} onPress={() => router.push({ pathname: '/discover/pattern/[patternId]', params: { patternId: pattern.id, endDate: dateId() } })} style={styles.pattern}><View style={[styles.patternBar, { backgroundColor: pattern.tone === 'danger' ? colors.body : colors.primary }]} /><View style={styles.patternCopy}><Text style={styles.patternMeta}>{pattern.metric} · {pattern.confidenceLabel}</Text><Text style={styles.patternTitle}>{pattern.title}</Text><Text style={styles.patternSummary}>{pattern.summary}</Text></View><AppIcon color={colors.textMuted} name="arrow-up-right" size={18} /></Pressable>) : <View style={styles.emptyPattern}><Text style={styles.emptyTitle}>아직 발견된 흐름이 없어요</Text><Text style={styles.emptyCopy}>기록이 쌓이면 생활과 몸 사이의 반복을 보여드려요.</Text></View>}</View>
      <Pressable onPress={() => router.push('/reports/setup')} style={styles.report}><View><Text style={styles.reportTitle}>이 기간의 기록 요약 만들기</Text><Text style={styles.reportCopy}>선택한 기록을 한 장의 리포트로 정리합니다.</Text></View><AppIcon color={colors.primary} name="arrow-up-right" size={18} /></Pressable>
    </>}
  </ScrollView></SafeAreaView>;
}
