import { useCallback, useEffect, useMemo, useState } from 'react';
import { Modal, Pressable, ScrollView, Text, View } from 'react-native';
import DateTimePicker from '@react-native-community/datetimepicker';
import { useRouter } from 'expo-router';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import ConnectionOverlayChart from '@/components/charts/connection-overlay-chart';
import { AppIcon } from '@/components/app-icon';
import { SegmentedControl } from '@/components/ui/segmented-control';
import type { ConnectionMetricId, DiscoverPattern, DiscoverSummary } from '@/domain/wellness';
import { useAsyncData } from '@/hooks/use-async-data';
import { wellnessApi } from '@/services/wellness-api';
import { colors, dataColors } from '@/theme/tokens';
import { styles } from './connection-view.styles';

type Period = '7'|'14'|'30'|'custom';
function dateId(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function daysBetween(start:Date,end:Date){return Math.max(2,Math.min(31,Math.floor((end.getTime()-start.getTime())/86400000)+1))}
export default function DiscoverScreen(){
  const router=useRouter();const insets=useSafeAreaInsets();const[period,setPeriod]=useState<Period>('14');const[customEnd,setCustomEnd]=useState(()=>new Date());const[customStart,setCustomStart]=useState(()=>{const d=new Date();d.setDate(d.getDate()-13);return d});const[selectedMetrics,setSelectedMetrics]=useState<ConnectionMetricId[]>(['sleep','discomfort','posture']);const[selectedIndex,setSelectedIndex]=useState<number|null>(null);const[selectionNotice,setSelectionNotice]=useState('');
  const periodDays=period==='custom'?daysBetween(customStart,customEnd):Number(period);const endDate=period==='custom'?dateId(customEnd):dateId(new Date());const loader=useCallback(()=>wellnessApi.getDiscoverSummary(endDate,periodDays),[endDate,periodDays]);const{data,error,isLoading,reload}=useAsyncData<DiscoverSummary|null>(loader,null);
  useEffect(()=>setSelectedIndex(null),[endDate,periodDays]);
  const visualMetrics=useMemo(()=>data?.metrics.map(metric=>({...metric,color:dataColors[metric.id]}))??[],[data]);
  const metrics=useMemo(()=>visualMetrics.filter(item=>selectedMetrics.includes(item.id)),[visualMetrics,selectedMetrics]);
  const toggleMetric=(id:ConnectionMetricId)=>{setSelectionNotice('');setSelectedMetrics(current=>{if(current.includes(id))return current.length===1?current:current.filter(item=>item!==id);if(current.length>=3){setSelectionNotice('비교 항목은 최대 3개까지 선택할 수 있어요.');return current}return[...current,id]})};
  return <SafeAreaView edges={['top']} style={styles.screen}><ScrollView contentContainerStyle={[styles.content,{paddingBottom:insets.bottom+88}]} showsVerticalScrollIndicator={false}><Text style={styles.kicker}>커넥션 뷰</Text><Text style={styles.title}>따로 남긴 기록에서{`\n`}함께 움직인 변화를 봐요.</Text><Text style={styles.description}>수면, 활동, 불편 기록을 같은 시간축에 놓고 내 생활의 반복을 확인해요.</Text>
    <Text style={styles.sectionLabel}>살펴볼 기간</Text><SegmentedControl onChange={setPeriod} options={[{value:'7',label:'7일'},{value:'14',label:'14일'},{value:'30',label:'30일'},{value:'custom',label:'직접'}]} value={period}/>
    {period==='custom'?<View style={styles.customDates}><View style={styles.datePickerItem}><Text style={styles.datePickerLabel}>시작일</Text><DateTimePicker display="compact" maximumDate={customEnd} mode="date" onChange={(_,value)=>value&&setCustomStart(value)} value={customStart}/></View><View style={styles.datePickerItem}><Text style={styles.datePickerLabel}>종료일</Text><DateTimePicker display="compact" maximumDate={new Date()} minimumDate={customStart} mode="date" onChange={(_,value)=>value&&setCustomEnd(value)} value={customEnd}/></View><Text style={styles.customHint}>최대 31일까지 선택할 수 있어요.</Text></View>:null}
    {isLoading?<ConnectionSkeleton/>:error?<Status><Text style={styles.errorTitle}>커넥션 뷰를 불러오지 못했어요</Text><Text style={styles.statusText}>선택한 기간은 유지돼요. 잠시 후 다시 시도해 주세요.</Text><Pressable accessibilityRole="button" onPress={()=>void reload().catch(()=>undefined)} style={({pressed})=>[styles.retryButton,pressed&&styles.pressed]}><Text style={styles.retryText}>다시 시도</Text></Pressable></Status>:data&&data.sleepValues.length>0?<>
      <BaselineCard data={data}/>
      <View style={styles.chartCard}><View style={styles.cardHeader}><View><Text style={styles.cardIndex}>기록 비교</Text><Text style={styles.cardTitle}>기록 겹쳐보기</Text><Text style={styles.cardDescription}>{data.periodLabel} · 비교할 항목을 최대 3개 선택하세요.</Text></View><Text accessibilityLabel={`선택한 비교 항목 ${selectedMetrics.length}개, 최대 3개`} style={styles.selectedCount}>{selectedMetrics.length}/3</Text></View><View style={styles.metricChips}>{visualMetrics.map((metric,index)=><Pressable accessibilityRole="button" accessibilityState={{selected:selectedMetrics.includes(metric.id)}} key={metric.id} onPress={()=>toggleMetric(metric.id)} style={({pressed})=>[styles.metricChip,selectedMetrics.includes(metric.id)&&styles.selectedMetric,pressed&&styles.pressed]}><Text style={styles.metricIndex}>{String(index+1).padStart(2,'0')}</Text><View style={[styles.metricDot,{backgroundColor:metric.color}]}/><Text style={styles.metricText}>{metric.shortLabel}</Text><Text style={styles.metricState}>{selectedMetrics.includes(metric.id)?'비교 중':'추가'}</Text></Pressable>)}</View>{selectionNotice?<Text accessibilityLiveRegion="polite" style={styles.selectionNotice}>{selectionNotice}</Text>:null}<View style={styles.legend}>{metrics.map(metric=><View key={metric.id} style={styles.legendItem}><View style={[styles.legendLine,{backgroundColor:metric.color}]}/><Text style={styles.legendText}>{metric.label} · {metric.unit}</Text></View>)}</View><View style={styles.chartCanvas}><ConnectionOverlayChart labels={data.labels} metrics={metrics} onPointPress={setSelectedIndex} selectedIndex={selectedIndex}/></View><Text style={styles.chartHint}>날짜를 누르면 그날의 기록을 자세히 볼 수 있어요.</Text><View accessibilityLabel="선택한 지표의 최근 값" style={styles.chartSummary}>{metrics.map((metric,index)=><View key={metric.id} style={styles.chartSummaryRow}><Text style={styles.chartSummaryIndex}>{String(index+1).padStart(2,'0')}</Text><Text style={styles.chartSummaryLabel}>{metric.label}</Text><Text style={styles.chartSummaryValue}>{metric.values.at(-1) ?? '-'} {metric.unit}</Text></View>)}</View></View>
      <View style={styles.patternHeading}><View><Text style={styles.sectionTitle}>상세 분석</Text><Text style={styles.sectionDescription}>30일 이상 기록이 쌓이면 반복 패턴과 근거를 분석해요.</Text></View><Text accessibilityLabel={data.analysisReadiness.ready?`확인 가능한 상세 분석 ${data.patterns.length}개`:`상세 분석 준비 중, ${data.analysisReadiness.recordedDays}일 기록됨`} style={styles.count}>{data.analysisReadiness.ready?`${data.patterns.length}개`:'준비 중'}</Text></View>{!data.analysisReadiness.ready?<View accessibilityRole="summary" style={styles.insufficient}><AppIcon color={colors.textMuted} name="lock" size={22}/><Text style={styles.insufficientTitle}>상세 분석까지 {Math.max(0,data.analysisReadiness.requiredDays-data.analysisReadiness.recordedDays)}일 남았어요</Text><Text style={styles.insufficientText}>현재 차트와 날짜별 값은 바로 확인할 수 있어요. 반복 패턴과 근거 분석은 기록이 최소 {data.analysisReadiness.requiredDays}일 쌓인 뒤 열립니다.</Text><View accessibilityLabel={`${data.analysisReadiness.requiredDays}일 중 ${data.analysisReadiness.recordedDays}일 기록`} accessibilityRole="progressbar" accessibilityValue={{min:0,max:data.analysisReadiness.requiredDays,now:data.analysisReadiness.recordedDays}} style={styles.analysisProgress}><View style={[styles.analysisProgressFill,{width:`${Math.min(100,data.analysisReadiness.recordedDays/data.analysisReadiness.requiredDays*100)}%`}]}/></View><Text style={styles.analysisProgressText}>{data.analysisReadiness.recordedDays}/{data.analysisReadiness.requiredDays}일 기록</Text><Pressable accessibilityRole="button" onPress={()=>router.push('/check/auto')} style={({pressed})=>[styles.insufficientButton,pressed&&styles.pressed]}><Text style={styles.insufficientButtonText}>오늘 상태 기록하기</Text></Pressable></View>:data.patterns.map(pattern=><PatternCard key={pattern.id} pattern={pattern} onPress={()=>router.push({pathname:'/discover/pattern/[patternId]',params:{patternId:pattern.id,endDate}})}/>) }
      <Pressable accessibilityRole="button" onPress={()=>router.push('/reports/setup')} style={({pressed})=>[styles.reportEntry,pressed&&styles.pressed]}><View style={styles.reportCopy}><Text style={styles.reportTitle}>이 기간의 기록 요약 만들기</Text><Text style={styles.reportDescription}>선택한 기간의 기록을 한 화면으로 정리합니다.</Text></View><AppIcon color={colors.primary} name="chevron-right" size={19}/></Pressable>
    </>:<Status><Text style={styles.errorTitle}>아직 발견된 패턴이 없어요</Text><Text style={styles.statusText}>오늘 상태를 기록하면 생활과 몸의 변화를 함께 살펴볼 수 있어요.</Text><Pressable onPress={()=>router.push('/check/auto')} style={styles.retryButton}><Text style={styles.retryText}>첫 기록 시작</Text></Pressable></Status>}
    </ScrollView><Modal animationType="slide" onRequestClose={()=>setSelectedIndex(null)} transparent visible={selectedIndex!==null&&!!data}><Pressable onPress={()=>setSelectedIndex(null)} style={styles.overlay}><Pressable onPress={event=>event.stopPropagation()} style={[styles.sheet,{paddingBottom:Math.max(insets.bottom,20)}]}>{selectedIndex!==null&&data?<DaySheet detail={data.dayDetails[selectedIndex]} onClose={()=>setSelectedIndex(null)}/>:null}</Pressable></Pressable></Modal></SafeAreaView>;
}
function BaselineCard({data}:{data:DiscoverSummary}){const b=data.baseline;return <View style={styles.baseline}><View style={styles.cardHeader}><View><Text style={styles.cardIndex}>개인 기준선</Text><Text style={styles.baselineTitle}>{b.ready?'나의 평소 상태':'기준선을 알아가는 중'}</Text></View><Text style={styles.baselineCount}>{b.recordedDays}/{b.targetDays}일</Text></View>{b.ready?<><View style={styles.baselineGrid}><Base index="01" label="평균 수면" value={b.averageSleep}/><Base index="02" label="평균 걸음" value={b.averageSteps}/><Base index="03" label="평균 취침" value={b.averageBedtime}/><Base index="04" label="목 불편" value={b.discomfortFrequency}/></View><Text style={styles.comparison}>{b.comparison}</Text></>:<><View style={styles.progressTrack}><View style={[styles.progressFill,{width:`${Math.min(100,b.recordedDays/b.targetDays*100)}%`}]}/></View><Text style={styles.baselineGuide}>{data.moreDataGuide}</Text></>}</View>}
function Base({index,label,value}:{index:string;label:string;value:string}){return <View style={styles.base}><Text style={styles.baseIndex}>{index}</Text><Text style={styles.baseValue}>{value}</Text><Text style={styles.baseLabel}>{label}</Text></View>}
function PatternCard({pattern,onPress}:{pattern:DiscoverPattern;onPress:()=>void}){return <Pressable accessibilityRole="button" onPress={onPress} style={({pressed})=>[styles.patternCard,pressed&&styles.pressed]}><View style={[styles.patternAccent,styles[`${pattern.tone}Accent`]]}/><View style={styles.patternBody}><View style={styles.patternTop}><Text style={styles.patternMetric}>{pattern.metric} · {pattern.confidenceLabel}</Text><AppIcon color={colors.textMuted} name="arrow-up-right" size={18}/></View><Text style={styles.patternTitle}>{pattern.title}</Text><Text style={styles.patternSummary}>{pattern.summary}</Text></View></Pressable>}
function DaySheet({detail,onClose}:{detail:DiscoverSummary['dayDetails'][number];onClose:()=>void}){return <><View style={styles.grabber}/><View style={styles.sheetHeader}><Text style={styles.sheetTitle}>{detail.dateLabel}</Text><Pressable accessibilityLabel="날짜 상세 닫기" accessibilityRole="button" onPress={onClose} style={styles.close}><AppIcon color={colors.textMuted} name="close" size={20}/></Pressable></View><SheetRow label="수면" value={`${detail.sleep} · ${detail.posture}`}/><SheetRow label="불편" value={detail.discomfort}/><SheetRow label="활동" value={detail.steps}/><SheetRow label="피부" value={detail.skin}/><SheetRow label="루틴" value={detail.routine}/></>}
function SheetRow({label,value}:{label:string;value:string}){return <View style={styles.sheetRow}><Text style={styles.sheetLabel}>{label}</Text><Text style={styles.sheetValue}>{value}</Text></View>}
function Status({children}:{children:React.ReactNode}){return <View style={styles.statusCard}>{children}</View>}
function ConnectionSkeleton(){return <View accessibilityLabel="기록 관계를 불러오는 중" accessibilityRole="progressbar" style={styles.skeletonWrap}><View style={styles.skeletonBaseline}/><View style={styles.skeletonChart}><View style={styles.skeletonLineShort}/><View style={styles.skeletonLine}/><View style={styles.skeletonGraph}/></View></View>}
