import { StyleSheet } from 'react-native';
import { colors, layout, motion, spacing, typography } from '@/theme/tokens';

export const patternStyles=StyleSheet.create({
  screen:{flex:1,backgroundColor:colors.surface},topBar:{minHeight:60,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:spacing.sm,paddingVertical:spacing.xxs,borderBottomWidth:1,borderBottomColor:colors.divider,backgroundColor:colors.surface},topTitle:{flex:1,flexShrink:1,textAlign:'center',color:colors.text,...typography.label},spacer:{width:layout.minTouch},content:{width:'100%',maxWidth:layout.maxContentWidth,alignSelf:'center',paddingHorizontal:layout.horizontalPadding,paddingTop:spacing.xl},
  center:{flex:1,alignItems:'center',justifyContent:'center',padding:spacing.xl,backgroundColor:colors.canvas},centerText:{marginTop:spacing.sm,color:colors.textMuted,...typography.caption},errorTitle:{color:colors.text,...typography.sectionTitle},retryButton:{minWidth:120,minHeight:48,alignItems:'center',justifyContent:'center',marginTop:spacing.md,borderWidth:1,borderColor:colors.border},retryText:{color:colors.text,...typography.label},
  metric:{alignSelf:'flex-start',color:colors.data,...typography.caption,fontWeight:'700'},title:{marginTop:spacing.xs,color:colors.text,...typography.display},summary:{marginTop:spacing.sm,color:colors.textSecondary,...typography.body},
  confidenceCard:{marginTop:spacing.lg,paddingVertical:spacing.md,borderTopWidth:0,borderBottomWidth:1,borderColor:colors.data},confidenceTop:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},confidenceLabel:{color:colors.textSecondary,...typography.caption,fontWeight:'700'},confidenceBadge:{color:colors.data,...typography.caption,fontWeight:'700'},confidenceInfo:{marginTop:spacing.xs,color:colors.textSecondary,...typography.caption},
  chartCard:{marginTop:spacing.xl,paddingVertical:spacing.lg,borderTopWidth:1,borderBottomWidth:1,borderColor:colors.divider},cardLabel:{color:colors.textMuted,...typography.caption},comparison:{marginTop:spacing.xs,color:colors.text,...typography.sectionTitle},legend:{flexDirection:'row',gap:spacing.md,marginTop:spacing.sm},legendItem:{flexDirection:'row',alignItems:'center',gap:spacing.xs},legendDot:{width:8,height:8,borderRadius:4},legendText:{color:colors.textMuted,fontSize:11},
  section:{marginTop:spacing.xxl},sectionTitle:{marginBottom:spacing.xs,color:colors.text,...typography.sectionTitle},evidenceRow:{minHeight:60,flexDirection:'row',alignItems:'center',gap:spacing.sm,borderBottomWidth:1,borderBottomColor:colors.divider},evidenceIndex:{width:28,color:colors.data,fontSize:12,fontWeight:'700'},evidenceText:{flex:1,color:colors.textSecondary,fontSize:14,lineHeight:21},
  suggestionCard:{marginTop:spacing.xl,paddingVertical:spacing.lg,borderTopWidth:0,borderBottomWidth:1,borderColor:colors.recovery},suggestionLabel:{color:colors.recovery,...typography.caption,fontWeight:'700'},suggestion:{marginTop:spacing.xs,color:colors.text,...typography.sectionTitle},disclaimer:{marginTop:spacing.md,color:colors.textMuted,...typography.caption},actions:{flexDirection:'row',gap:spacing.xs,marginTop:spacing.md},secondaryAction:{flex:1,minHeight:56,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:colors.border},secondaryActionText:{color:colors.text,...typography.caption,fontWeight:'700'},primaryAction:{flex:1,minHeight:56,alignItems:'center',justifyContent:'center',backgroundColor:colors.text},primaryActionText:{color:colors.white,...typography.caption,fontWeight:'700'},pressed:{opacity:motion.pressOpacity},
});
