import { StyleSheet } from 'react-native';

export const patternStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F7F8FA' }, topBar: { height: 56, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 10, backgroundColor: '#FFFFFF' }, topTitle: { color: '#17191C', fontSize: 16, fontWeight: '800' }, spacer: { width: 44 }, content: { padding: 20 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24, backgroundColor: '#FFFFFF' }, centerText: { marginTop: 10, color: '#737B88', fontSize: 13 }, errorTitle: { color: '#17191C', fontSize: 17, fontWeight: '800' }, retryButton: { minWidth: 120, minHeight: 46, alignItems: 'center', justifyContent: 'center', marginTop: 14, borderRadius: 12, backgroundColor: '#EEF3FF' }, retryText: { color: '#1257E0', fontSize: 13, fontWeight: '800' },
  metric: { alignSelf: 'flex-start', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 9, overflow: 'hidden', color: '#1257E0', backgroundColor: '#EAF0FF', fontSize: 12, fontWeight: '800' }, title: { marginTop: 14, color: '#17191C', fontSize: 28, lineHeight: 37, fontWeight: '800', letterSpacing: -0.7 }, summary: { marginTop: 9, color: '#737B88', fontSize: 14, lineHeight: 22 },
  chartCard: { marginTop: 24, padding: 17, borderRadius: 20, backgroundColor: '#FFFFFF' }, cardLabel: { color: '#8B919B', fontSize: 11, fontWeight: '700' }, comparison: { marginTop: 5, color: '#17191C', fontSize: 16, fontWeight: '800' }, legend: { flexDirection: 'row', gap: 14, marginTop: 12 }, legendItem: { flexDirection: 'row', alignItems: 'center', gap: 5 }, legendDot: { width: 8, height: 8, borderRadius: 4 }, legendText: { color: '#737B88', fontSize: 10 },
  section: { marginTop: 14, padding: 18, borderRadius: 20, backgroundColor: '#FFFFFF' }, sectionTitle: { marginBottom: 8, color: '#17191C', fontSize: 17, fontWeight: '800' }, evidenceRow: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 12, borderBottomWidth: 1, borderBottomColor: '#EEF0F3' }, evidenceIndex: { width: 24, height: 24, textAlign: 'center', lineHeight: 24, borderRadius: 12, overflow: 'hidden', color: '#1257E0', backgroundColor: '#EEF3FF', fontSize: 11, fontWeight: '800' }, evidenceText: { flex: 1, color: '#4A4F58', fontSize: 13, lineHeight: 20 },
  suggestionCard: { marginTop: 14, padding: 20, borderRadius: 20, backgroundColor: '#17191C' }, suggestionLabel: { color: '#8EB0F6', fontSize: 12, fontWeight: '800' }, suggestion: { marginTop: 8, color: '#FFFFFF', fontSize: 17, lineHeight: 26, fontWeight: '700' }, disclaimer: { marginTop: 14, color: '#AEB3BC', fontSize: 10, lineHeight: 16 },
});
