import { useState } from 'react';
import { Alert, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { useRouter } from 'expo-router';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import NavigationBackButton from '@/components/navigation-back-button';
import { wellnessApi } from '@/services/wellness-api';
import { styles } from './account-settings.styles';
export default function AccountSettingsScreen(){const router=useRouter();const insets=useSafeAreaInsets();const[current,setCurrent]=useState('');const[next,setNext]=useState('');const[confirm,setConfirm]=useState('');const valid=current.length>=8&&next.length>=8&&next===confirm;const changePassword=()=>{if(!valid)return;setCurrent('');setNext('');setConfirm('');Alert.alert('변경 완료','비밀번호가 변경된 것으로 처리했어요. 실제 인증 API 연결 시 같은 화면 계약을 사용합니다.')};const withdraw=()=>Alert.alert('회원 탈퇴 전 확인','계정과 모든 기록, 피부 사진, 연결 정보가 삭제되며 복구할 수 없어요.',[{text:'취소',style:'cancel'},{text:'탈퇴하기',style:'destructive',onPress:()=>void wellnessApi.deleteAllUserData().then(()=>router.replace('/(auth)/login'))}]);return <SafeAreaView edges={['top']} style={styles.screen}><View style={styles.topBar}><NavigationBackButton accessibilityLabel="나 화면으로 돌아가기" fallbackHref="/(tabs)/me"/><Text style={styles.topTitle}>계정 관리</Text><View style={styles.spacer}/></View><ScrollView contentContainerStyle={[styles.content,{paddingBottom:insets.bottom+40}]}><Text style={styles.sectionTitle}>비밀번호 변경</Text><Field label="현재 비밀번호" value={current} onChange={setCurrent}/><Field label="새 비밀번호" value={next} onChange={setNext}/><Field label="새 비밀번호 확인" value={confirm} onChange={setConfirm}/>{confirm&&next!==confirm?<Text style={styles.error}>새 비밀번호가 서로 다릅니다.</Text>:null}<Pressable accessibilityRole="button" disabled={!valid} onPress={changePassword} style={[styles.primary,!valid&&styles.disabled]}><Text style={styles.primaryText}>비밀번호 변경</Text></Pressable><Text style={styles.sectionTitle}>로그인 상태</Text><Pressable accessibilityRole="button" onPress={()=>router.replace('/(auth)/login')} style={styles.menu}><Text style={styles.menuText}>로그아웃</Text></Pressable><Text style={styles.sectionTitle}>회원 탈퇴</Text><Text style={styles.help}>탈퇴하면 모든 데이터가 삭제되고 복구할 수 없습니다.</Text><Pressable accessibilityRole="button" onPress={withdraw} style={styles.danger}><Text style={styles.dangerText}>회원 탈퇴</Text></Pressable></ScrollView></SafeAreaView>}
function Field({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput accessibilityLabel={label} autoCapitalize="none" onChangeText={onChange} secureTextEntry style={styles.input} value={value}/></View>}
