import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, Switch, Text, View } from 'react-native';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import NavigationBackButton from '@/components/navigation-back-button';
import StateNotice from '@/components/state-notice';
import type { NotificationSettings } from '@/domain/wellness';
import { useAsyncData } from '@/hooks/use-async-data';
import { wellnessApi } from '@/services/wellness-api';
import { styles } from './settings.styles';
import { colors } from '@/theme/tokens';

const TIMES = ['20:00', '21:00', '21:30', '22:00'];
export default function NotificationSettingsScreen() {
  const insets = useSafeAreaInsets(); const { data, error, isLoading, reload } = useAsyncData<NotificationSettings | null>(wellnessApi.getNotificationSettings, null);
  const [form, setForm] = useState<NotificationSettings | null>(null); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false);
  useEffect(() => { if (data) setForm(data); }, [data]);
  const set = <K extends keyof NotificationSettings>(key: K, value: NotificationSettings[K]) => setForm((current) => current ? { ...current, [key]: value } : current);
  const save = async () => { if (!form) return; setSaving(true); setSaved(false); try { await wellnessApi.saveNotificationSettings(form); setSaved(true); } finally { setSaving(false); } };
  const mockPermission = () => { set('osPermission', 'granted'); Alert.alert('알림 권한 확인', '기기 알림 권한이 허용됐어요.'); };
  return <SafeAreaView edges={['top']} style={styles.screen}><Top title="알림 설정"/><ScrollView contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + 120 }]}>{isLoading ? <Center/> : error || !form ? <StateNotice actionLabel="다시 시도" description="알림 설정을 불러오지 못했어요." icon="!" onAction={() => void reload().catch(() => undefined)} title="불러오기 실패" tone="error"/> : <>
    <View style={styles.master}><View style={styles.rowCopy}><Text style={styles.masterTitle}>OS 알림 권한</Text><Text style={styles.masterDescription}>{form.osPermission === 'granted' ? '기기에서 허용됨' : form.osPermission === 'denied' ? '기기 설정에서 차단됨' : '아직 요청하지 않음'}</Text></View><Pressable accessibilityRole="button" onPress={mockPermission} style={styles.time}><Text style={styles.timeText}>{form.osPermission === 'granted' ? '허용됨' : '권한 확인'}</Text></Pressable></View>
    <View style={styles.master}><View><Text style={styles.masterTitle}>앱 내부 알림</Text><Text style={styles.masterDescription}>허용할 알림 종류를 선택하세요</Text></View><Switch onValueChange={(value) => set('enabled', value)} trackColor={{ false: colors.border, true: colors.primaryBorder }} thumbColor={form.enabled ? colors.primary : colors.white} value={form.enabled}/></View>
    <View style={!form.enabled && styles.dim}><Text style={styles.sectionTitle}>알림 종류</Text><View style={styles.group}><Toggle disabled={!form.enabled} label="오늘 상태 기록" description="매일 설정한 시간에 알림" value={form.dailyCheck} onChange={(value) => set('dailyCheck', value)}/><Toggle disabled={!form.enabled} label="추천 루틴" description="오늘의 루틴이 준비되면 알림" value={form.routine} onChange={(value) => set('routine', value)}/><Toggle disabled={!form.enabled} label="주간 기록 요약" description="매주 일요일에 변화 요약" value={form.weeklyReport} onChange={(value) => set('weeklyReport', value)}/><Toggle disabled={!form.enabled} label="다음 날 효과 확인" description="완료한 루틴의 변화를 확인" value={form.nextDayEffect} onChange={(value) => set('nextDayEffect', value)}/><Toggle disabled={!form.enabled} label="증상 지속 확인" description="같은 불편이 반복되면 확인" value={form.persistentSignal} onChange={(value) => set('persistentSignal', value)}/></View><Text style={styles.sectionTitle}>기록 알림 시간</Text><View style={styles.timeRow}>{TIMES.map((time) => <Pressable accessibilityRole="radio" accessibilityState={{ checked: form.reminderTime === time }} disabled={!form.enabled} key={time} onPress={() => set('reminderTime', time)} style={[styles.time, form.reminderTime === time && styles.selectedTime]}><Text style={[styles.timeText, form.reminderTime === time && styles.selectedTimeText]}>{time}</Text></Pressable>)}</View></View>
    {saved ? <Text accessibilityLiveRegion="polite" style={styles.saved}>설정이 저장됐어요.</Text> : null}<View style={styles.mockNotice}><Text style={styles.mockText}>기기 알림이 꺼져 있으면 앱에서 알림을 선택해도 받을 수 없어요.</Text></View></>}</ScrollView>{form ? <View style={[styles.action, { paddingBottom: Math.max(insets.bottom, 12) }]}><Pressable accessibilityRole="button" disabled={saving} onPress={() => void save()} style={styles.primary}>{saving ? <ActivityIndicator color="#FFF"/> : <Text style={styles.primaryText}>설정 저장하기</Text>}</Pressable></View> : null}</SafeAreaView>;
}
function Toggle({ description, disabled, label, onChange, value }: { description: string; disabled: boolean; label: string; onChange: (value: boolean) => void; value: boolean }) { return <View style={styles.row}><View style={styles.rowCopy}><Text style={styles.rowLabel}>{label}</Text><Text style={styles.rowDescription}>{description}</Text></View><Switch accessibilityLabel={label} disabled={disabled} onValueChange={onChange} trackColor={{ false: colors.border, true: colors.primaryBorder }} thumbColor={value ? colors.primary : colors.white} value={value}/></View>; }
function Center() { return <View style={styles.center}><ActivityIndicator color="#285C4D"/></View>; }
function Top({ title }: { title: string }) { return <View style={styles.topBar}><NavigationBackButton accessibilityLabel="나 화면으로 돌아가기" fallbackHref="/(tabs)/me"/><Text style={styles.topTitle}>{title}</Text><View style={styles.spacer}/></View>; }
