import { StyleSheet } from 'react-native';
import { colors, layout, radius, spacing, typography } from '@/theme/tokens';

export const styles=StyleSheet.create({
  screen:{flex:1,backgroundColor:colors.canvas},topBar:{height:56,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:spacing.sm,borderBottomWidth:1,borderBottomColor:colors.divider,backgroundColor:colors.surface},topTitle:{color:colors.text,...typography.label},spacer:{width:layout.minTouch},content:{width:'100%',maxWidth:layout.maxContentWidth,alignSelf:'center',paddingHorizontal:layout.horizontalPadding,paddingTop:spacing.xl},center:{minHeight:440,alignItems:'center',justifyContent:'center'},
  hero:{minHeight:88,flexDirection:'row',alignItems:'center',gap:spacing.sm,marginBottom:spacing.md,paddingVertical:spacing.md,borderBottomWidth:1,borderBottomColor:colors.divider},heroIcon:{width:48,height:48,alignItems:'center',justifyContent:'center',borderRadius:radius.md,backgroundColor:colors.primarySoft},heroIconText:{color:colors.primary,fontSize:22},heroCopy:{flex:1},heroTitle:{color:colors.text,...typography.sectionTitle},heroDescription:{marginTop:spacing.xxs,color:colors.textMuted,...typography.caption},
  sectionTitle:{marginTop:spacing.xxl,marginBottom:spacing.xs,color:colors.text,...typography.sectionTitle},group:{borderTopWidth:1,borderTopColor:colors.divider},row:{minHeight:64,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingVertical:spacing.sm,borderBottomWidth:1,borderBottomColor:colors.divider},rowCopy:{flex:1,paddingRight:spacing.sm},rowLabel:{color:colors.text,fontSize:15,fontWeight:'700'},rowDescription:{marginTop:spacing.xxs,color:colors.textMuted,...typography.caption},
  info:{marginTop:spacing.md,paddingVertical:spacing.md,borderTopWidth:1,borderBottomWidth:1,borderColor:colors.primaryBorder},infoText:{color:colors.textSecondary,...typography.caption},dangerOutline:{minHeight:52,alignItems:'center',justifyContent:'center',marginTop:spacing.lg,borderWidth:1,borderColor:colors.danger,borderRadius:radius.md,backgroundColor:colors.surface},dangerOutlineText:{color:colors.danger,...typography.label},
  busy:{position:'absolute',right:spacing.lg,bottom:spacing.xxl,left:spacing.lg,minHeight:54,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:spacing.sm,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,backgroundColor:colors.surface},busyText:{color:colors.textSecondary,...typography.caption,fontWeight:'700'},
  master:{minHeight:82,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingVertical:spacing.md,borderBottomWidth:1,borderBottomColor:colors.divider},masterTitle:{color:colors.text,...typography.label},masterDescription:{marginTop:spacing.xxs,color:colors.textMuted,...typography.caption},dim:{opacity:.45},timeRow:{flexDirection:'row',gap:spacing.xs},time:{flex:1,minHeight:48,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:colors.border,borderRadius:radius.md,backgroundColor:colors.surface},selectedTime:{borderColor:colors.primary,backgroundColor:colors.primary},timeText:{color:colors.textSecondary,...typography.caption,fontWeight:'800'},selectedTimeText:{color:colors.white},saved:{marginTop:spacing.md,textAlign:'center',color:colors.success,...typography.caption,fontWeight:'800'},
  mockNotice:{marginTop:spacing.md,padding:spacing.md,borderWidth:1,borderColor:'#E7D2BA',borderRadius:radius.lg,backgroundColor:colors.warningSoft},mockText:{color:colors.warning,...typography.caption},action:{position:'absolute',right:0,bottom:0,left:0,paddingHorizontal:layout.compactHorizontalPadding,paddingTop:spacing.sm,borderTopWidth:1,borderTopColor:colors.divider,backgroundColor:colors.surface},primary:{minHeight:56,alignItems:'center',justifyContent:'center',borderRadius:radius.md,backgroundColor:colors.primary},primaryText:{color:colors.white,fontSize:15,fontWeight:'800'},required:{color:colors.primary,fontSize:11},optional:{color:colors.textMuted,fontSize:11},
  infoRow:{minHeight:58,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:colors.divider},infoLabel:{color:colors.textMuted,fontSize:13},infoValue:{color:colors.text,fontSize:13,fontWeight:'700'},dataMenu:{minHeight:58,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:colors.divider},dataMenuText:{color:colors.text,fontSize:14,fontWeight:'700'},dataMenuArrow:{color:colors.textMuted,fontSize:22},deleteButton:{minHeight:52,alignItems:'center',justifyContent:'center',marginTop:spacing.xl,borderRadius:radius.md,backgroundColor:colors.dangerSoft},deleteText:{color:colors.danger,...typography.label},guideTitle:{color:colors.text,...typography.display},guideDescription:{marginTop:spacing.xs,color:colors.textMuted,...typography.body},
});
