import { StyleSheet } from 'react-native';
import { colors, layout, motion, radius, spacing, typography } from '@/theme/tokens';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.surface },
  flex: { flex: 1, backgroundColor: colors.canvas },
  tabHeader: { minHeight: 64, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: layout.horizontalPadding, paddingTop: spacing.sm, paddingBottom: spacing.sm, borderBottomWidth: 1, borderColor: colors.divider },
  tabHeaderCompact: { minHeight: 56, paddingVertical: spacing.xxs },
  tabTitle: { color: colors.text, fontSize: 25, lineHeight: 32, fontWeight: '800', letterSpacing: -.8 },
  scope: { marginTop: spacing.xxs, color: colors.textMuted, ...typography.caption },
  topBar: { minHeight: 60, flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing.xs, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.divider, backgroundColor: colors.surface },
  compactHeaderCopy: { flex: 1 },
  compactTitle: { flex: 1, color: colors.text, ...typography.label },
  compactScope: { marginTop: 1, color: colors.textMuted, fontSize: 10, lineHeight: 14, fontWeight: '600' },
  scopePill: { marginRight: 14, paddingVertical: 6, paddingHorizontal: 10, borderRadius: radius.pill, backgroundColor: colors.primarySoft },
  scopePillText: { color: colors.primaryText, fontSize: 11, lineHeight: 16, fontWeight: '700' },
  reportButton: { width: layout.minTouch, height: layout.minTouch, alignItems: 'center', justifyContent: 'center' },
  list: { width: '100%', maxWidth: layout.maxContentWidth, alignSelf: 'center', paddingHorizontal: layout.horizontalPadding, paddingTop: spacing.lg, paddingBottom: spacing.lg },
  listCompact: { paddingTop: spacing.sm, paddingBottom: spacing.sm },
  emptyList: { flexGrow: 1 },
  start: { flex: 1, justifyContent: 'flex-start', paddingTop: 2, paddingBottom: spacing.xl },welcomeRow:{flexDirection:'row',alignItems:'center',gap:spacing.sm},welcomeBubble:{flex:1,padding:spacing.md,borderRadius:18,borderBottomLeftRadius:4,backgroundColor:colors.surface},
  startCompact: { paddingTop: 0, paddingBottom: spacing.sm },
  welcomeBubbleCompact: { paddingVertical: spacing.sm },
  startKicker: { color: colors.primary, fontSize: 11, lineHeight: 16, fontWeight: '800', letterSpacing: 1.1 },
  startTitle: { maxWidth: 340, marginTop: spacing.sm, color: colors.text, fontSize: 34, lineHeight: 41, fontWeight: '800', letterSpacing: -1.3 },
  startDescription: { maxWidth: 410, color: colors.textSecondary, ...typography.body },
  indexTitle: { display: 'none' },
  indexTitleCompact: { marginTop: spacing.sm, marginBottom: spacing.xxs },
  questionIndex: { gap: spacing.sm, marginTop: 22 },
  questionRow: { minHeight: 52, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingHorizontal:spacing.lg,borderRadius:26,backgroundColor:colors.surface },
  questionPressed: { opacity: .65 },
  questionIcon: { width: 34, height: 34, alignItems: 'center', justifyContent: 'center', borderRadius: 17, backgroundColor: colors.primarySoft },
  questionText: { flex: 1, color: colors.text, fontSize: 15, lineHeight: 22, fontWeight: '600' },
  userEntry: { alignItems: 'flex-end', marginTop: spacing.xs, marginBottom: spacing.xl },
  userBlock: { maxWidth: '82%', paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderRadius: 18, borderBottomRightRadius: 4, backgroundColor: colors.primary },
  userText: { color: colors.primaryText, fontSize: 15, lineHeight: 23, fontWeight: '500' },
  messagePhoto: { width: 186, height: 132, marginBottom: spacing.xs, borderRadius: radius.md, backgroundColor: colors.surfaceStrong },
  answerEntry: { marginBottom: spacing.xxl },
  answerHeading: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs, marginBottom: spacing.xs },
  assistantIcon: { width: 30, height: 30, alignItems: 'center', justifyContent: 'center', borderRadius: 15, backgroundColor: colors.primarySoft },
  answerHeadingText: { color: colors.textSecondary, ...typography.caption, fontWeight: '600' },
  answerBody: { padding:spacing.md,borderWidth: 1,borderColor: colors.border,borderRadius:18,borderTopLeftRadius:4,backgroundColor: colors.surface },
  answerText: { color: colors.text, fontSize: 16, lineHeight: 26, fontWeight: '400' },
  referenceLedger: { overflow: 'hidden', marginTop: spacing.sm, paddingHorizontal: spacing.md, borderRadius: radius.lg, backgroundColor: colors.surfaceSubtle },
  referenceTitle: { paddingVertical: spacing.sm, color: colors.text, ...typography.label },
  referenceRow: { minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.md, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.divider },
  referenceLabel: { flex: 1, color: colors.textMuted, ...typography.caption },
  referenceValue: { maxWidth: '58%', color: colors.text, textAlign: 'right', ...typography.caption, fontWeight:'700' },
  actionRow: { minHeight: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: spacing.sm, paddingHorizontal: spacing.md, borderRadius: radius.md, backgroundColor: colors.primarySoft },
  actionText: { color: colors.data, ...typography.label },
  medicineSheet: { marginTop: spacing.xl, backgroundColor: colors.surfaceSubtle },
  medicineHeader: { padding: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.border },
  medicineSource: { color: colors.data, ...typography.caption, fontWeight:'700' },
  medicineName: { marginTop: spacing.sm, color: colors.text, ...typography.title },
  medicineIngredient: { marginTop: spacing.xxs, color: colors.textSecondary, ...typography.caption },
  medicineSection: { padding: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.border },
  medicineLabel: { color: colors.text, ...typography.label },
  medicineText: { marginTop: spacing.xs, color: colors.textSecondary, ...typography.body },
  caution: { marginTop: spacing.xs, color: colors.textSecondary, ...typography.caption },
  sourceRow: { minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: spacing.md },
  sourceText: { color: colors.data, ...typography.label },
  medicineLimit: { paddingHorizontal: spacing.md, paddingBottom: spacing.md, color: colors.warning, fontSize: 11, lineHeight: 17 },
  reading: { marginBottom: spacing.xl },
  readingLine: { width: '42%', height: 3, backgroundColor: colors.data },
  readingText: { marginTop: spacing.xs, color: colors.textMuted, ...typography.caption },
  errorRow: { minHeight: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: spacing.lg, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.danger },
  errorText: { color: colors.danger, ...typography.caption },
  retry: { minWidth: 84, minHeight: layout.minTouch, alignItems: 'flex-end', justifyContent: 'center' },
  retryText: { color: colors.danger, ...typography.label },
  followUp: { maxHeight: 140, paddingHorizontal: layout.horizontalPadding, paddingTop: spacing.xs, borderTopWidth: 1, borderTopColor: colors.border, backgroundColor: colors.canvas },
  followUpTitle: { marginBottom: spacing.xxs, color: colors.textMuted, fontSize: 11, lineHeight: 16, fontWeight: '700' },
  followUpRow: { minHeight: 46, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.sm, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.divider },
  followUpText: { flex: 1, color: colors.textSecondary, ...typography.caption, fontWeight: '700' },
  attachment: { minHeight: 68, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingHorizontal: layout.horizontalPadding, borderTopWidth: 1, borderTopColor: colors.border, backgroundColor: colors.surfaceSubtle },
  attachmentImage: { width: 46, height: 46, borderRadius: radius.sm },
  attachmentCopy: { flex: 1 },
  attachmentTitle: { color: colors.text, ...typography.label },
  attachmentHint: { marginTop: 1, color: colors.textMuted, fontSize: 11, lineHeight: 16 },
  attachmentRemove: { width: layout.minTouch, height: layout.minTouch, alignItems: 'center', justifyContent: 'center' },
  composer: { paddingHorizontal: layout.horizontalPadding, paddingTop: spacing.sm, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.divider, backgroundColor: colors.surface },
  composerCompact: { paddingTop: spacing.xxs },
  composerLabel: { display: 'none' },
  composerRow: { minHeight: 54, flexDirection: 'row', alignItems: 'flex-end', padding: 3, borderWidth: 1, borderColor: colors.border, borderRadius: radius.pill, backgroundColor: colors.surfaceSubtle },
  attach: { display: 'none' },
  input: { flex: 1, minHeight: 52, maxHeight: 116, paddingHorizontal: spacing.sm, paddingVertical: 14, color: colors.text, fontSize: 15, lineHeight: 22 },
  send: { width: 46, height: 46, alignItems: 'center', justifyContent: 'center', borderRadius: 23, backgroundColor: colors.primary },
  sendDisabled: { backgroundColor: colors.disabled },
  pressed: { opacity: motion.pressOpacity },
});
