import { useRef, useState } from 'react';
import { ActivityIndicator, FlatList, KeyboardAvoidingView, Linking, Platform, Pressable, Text, TextInput, View } from 'react-native';
import { Image } from 'expo-image';
import * as ImagePicker from 'expo-image-picker';
import { useRouter } from 'expo-router';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';

import NavigationBackButton from '@/components/navigation-back-button';
import { AppIcon } from '@/components/app-icon';
import { ChatbotIcon, SendIcon } from '@/components/chatbot-icon';
import type { AssistantMessage, AssistantReply } from '@/domain/wellness';
import { wellnessApi } from '@/services/wellness-api';
import { colors } from '@/theme/tokens';

import { styles } from './assistant.styles';

type ChatItem = AssistantMessage & { action?: AssistantReply['action']; references?: AssistantReply['references']; officialInfo?: AssistantReply['officialInfo']; photoUri?: string };
const INITIAL_MESSAGE: ChatItem = { id: 'welcome', role: 'assistant', createdAt: new Date().toISOString(), text: '안녕하세요. 남겨둔 기록을 함께 살펴보고 이해하기 쉽게 정리해 드릴게요. 무엇이 궁금한가요?' };
const INITIAL_SUGGESTIONS = ['최근 수면 알려줘', '목 불편 기록 알려줘', '오늘 루틴 추천해줘'];

export default function AssistantScreen({ asTab = false }: { asTab?: boolean }) {
  const router = useRouter(); const insets = useSafeAreaInsets(); const listRef = useRef<FlatList<ChatItem>>(null);
  const [messages, setMessages] = useState<ChatItem[]>([INITIAL_MESSAGE]); const [suggestions, setSuggestions] = useState(INITIAL_SUGGESTIONS); const [input, setInput] = useState(''); const [photoUri, setPhotoUri] = useState<string | null>(null); const [pending, setPending] = useState(false); const [failedPrompt, setFailedPrompt] = useState('');
  const send = async (raw: string) => { const text = raw.trim() || (photoUri ? '포장 사진으로 약 정보 확인해줘' : ''); if (!text || pending) return; const userMessage: ChatItem = { id: `user-${Date.now()}`, role: 'user', text, photoUri: photoUri ?? undefined, createdAt: new Date().toISOString() }; const history = [...messages, userMessage]; setMessages(history); setInput(''); setPhotoUri(null); setSuggestions([]); setPending(true); setFailedPrompt(''); try { const reply = await wellnessApi.askRecordAssistant(photoUri ? `${text} 포장사진` : text, history); setMessages(current => [...current, { ...reply.message, action: reply.action, references: reply.references, officialInfo: reply.officialInfo }]); setSuggestions(reply.suggestions); } catch { setFailedPrompt(text); setInput(text); } finally { setPending(false); } };
  const attachMedicinePhoto = async () => { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], allowsEditing: true, quality: .75 }); if (!result.canceled) { setPhotoUri(result.assets[0].uri); if (!input) setInput('이 약 정보를 확인해줘'); } };
  return <SafeAreaView edges={['top']} style={styles.screen}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : 'height'} keyboardVerticalOffset={0} style={styles.flex}>{asTab?<View style={styles.tabHeader}><View style={styles.tabBotIcon}><ChatbotIcon size={20}/></View><View><Text style={styles.tabTitle}>웰니스 챗</Text><View style={styles.onlineRow}><View style={styles.onlineDot}/><Text style={styles.onlineText}>내 기록을 바탕으로 답변</Text></View></View></View>:<View style={styles.topBar}><NavigationBackButton accessibilityLabel="오늘 화면으로 돌아가기" fallbackHref="/(tabs)/home" /><View style={styles.headerCopy}><Text style={styles.topTitle}>웰니스 챗</Text><View style={styles.onlineRow}><View style={styles.onlineDot}/><Text style={styles.onlineText}>내 기록을 바탕으로 답변</Text></View></View><View style={styles.spacer}/></View>}
    <FlatList ref={listRef} data={messages} keyExtractor={item=>item.id} keyboardDismissMode="interactive" keyboardShouldPersistTaps="handled" contentContainerStyle={styles.list} onContentSizeChange={()=>listRef.current?.scrollToEnd({animated:true})} renderItem={({item})=><Message item={item} onAction={route=>router.push(route)}/>} ListFooterComponent={<>{pending?<View accessibilityLiveRegion="polite" style={styles.typing}><BotAvatar/><View style={styles.typingBubble}><ActivityIndicator color="#285C4D" size="small"/><Text style={styles.typingText}>답변을 작성하고 있어요</Text></View></View>:null}{failedPrompt?<View style={styles.errorCard}><Text style={styles.errorText}>답변을 가져오지 못했어요.</Text><Pressable accessibilityRole="button" onPress={()=>void send(failedPrompt)} style={styles.retry}><Text style={styles.retryText}>다시 시도</Text></Pressable></View>:null}</>}/>
    {suggestions.length>0?<View style={styles.suggestionWrap}><Text style={styles.suggestionLabel}>이어서 물어보기</Text><FlatList horizontal data={suggestions} keyExtractor={item=>item} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.suggestions} renderItem={({item})=><Pressable accessibilityRole="button" onPress={()=>void send(item)} style={({pressed})=>[styles.suggestion,pressed&&styles.pressed]}><Text style={styles.suggestionText}>{item}</Text></Pressable>}/></View>:null}
    {photoUri ? <View style={styles.attachment}><Image accessibilityLabel="첨부한 약 포장 사진" source={{ uri: photoUri }} style={styles.attachmentImage}/><Text style={styles.attachmentText}>약 포장 사진</Text><Pressable accessibilityLabel="첨부 사진 제거" accessibilityRole="button" onPress={() => setPhotoUri(null)} style={styles.attachmentRemove}><AppIcon color={colors.text} name="close" size={18}/></Pressable></View> : null}
    <View style={[styles.composer,{paddingBottom:asTab?10:Math.max(insets.bottom,10)}]}><Pressable accessibilityLabel="약 포장 사진 첨부" accessibilityRole="button" onPress={() => void attachMedicinePhoto()} style={styles.attach}><AppIcon color={colors.textSecondary} name="camera" size={22}/></Pressable><TextInput accessibilityLabel="웰니스 챗에 메시지" blurOnSubmit={false} editable={!pending} maxLength={300} multiline onChangeText={setInput} onSubmitEditing={()=>void send(input)} placeholder="기록이나 약 이름을 물어보세요" placeholderTextColor="#6E776F" returnKeyType="send" style={styles.input} value={input}/><Pressable accessibilityLabel="메시지 보내기" accessibilityRole="button" disabled={(!input.trim()&&!photoUri)||pending} onPress={()=>void send(input)} style={[styles.send,((!input.trim()&&!photoUri)||pending)&&styles.sendDisabled]}><SendIcon/></Pressable></View>
  </KeyboardAvoidingView></SafeAreaView>;
}

function Message({ item, onAction }: { item: ChatItem; onAction: (route: NonNullable<AssistantReply['action']>['route']) => void }) {
  const assistant = item.role === 'assistant';
  return <View style={[styles.messageRow,!assistant&&styles.userRow]}>{assistant?<BotAvatar/>:null}<View style={styles.messageColumn}>{item.photoUri ? <Image accessibilityLabel="사용자가 첨부한 약 포장 사진" source={{ uri: item.photoUri }} style={styles.messagePhoto}/> : null}<View style={[styles.bubble,assistant?styles.assistantBubble:styles.userBubble]}><Text accessibilityLiveRegion={assistant?'polite':'none'} style={[styles.messageText,!assistant&&styles.userText]}>{item.text}</Text></View>{assistant&&item.references?.length?<View style={styles.referenceBox}><Text style={styles.referenceTitle}>참고한 내 기록</Text>{item.references.map(reference=><View key={reference.label} style={styles.referenceRow}><Text style={styles.referenceLabel}>{reference.label}</Text><Text style={styles.referenceValue}>{reference.value}</Text></View>)}</View>:null}{item.officialInfo ? <View style={styles.medicineCard}><Text style={styles.medicineEyebrow}>공식 의약품 정보</Text><Text style={styles.medicineName}>{item.officialInfo.productName}</Text><Text style={styles.medicineIngredient}>{item.officialInfo.ingredient}</Text><Text style={styles.medicineLabel}>효능·효과</Text><Text style={styles.medicineText}>{item.officialInfo.efficacy}</Text><Text style={styles.medicineLabel}>복용 전 확인</Text>{item.officialInfo.cautions.map((caution) => <Text key={caution} style={styles.caution}>· {caution}</Text>)}<Pressable accessibilityRole="link" onPress={() => void Linking.openURL(item.officialInfo!.sourceUrl)} style={styles.sourceLink}><Text style={styles.sourceText}>{item.officialInfo.sourceLabel}</Text><AppIcon color={colors.primary} name="chevron-right" size={16}/></Pressable><Text style={styles.medicineLimit}>포장 사진만으로 제품이나 복용 가능 여부를 확정하지 않아요.</Text></View> : null}{item.action?<Pressable accessibilityRole="button" onPress={()=>onAction(item.action!.route)} style={({pressed})=>[styles.actionButton,pressed&&styles.pressed]}><Text style={styles.actionText}>{item.action.label}</Text><AppIcon color={colors.primary} name="chevron-right" size={17}/></Pressable>:null}</View></View>;
}

function BotAvatar() { return <View accessibilityLabel="웰니스 챗" style={styles.avatar}><ChatbotIcon color={colors.primary} size={18}/></View>; }
