import { StyleSheet } from 'react-native';
import { colors, layout, motion, radius, spacing, typography } from '@/theme/tokens';

export const styles=StyleSheet.create({
  screen:{flex:1,backgroundColor:colors.canvas},flex:{flex:1},
  topBar:{height:56,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:spacing.sm,borderBottomWidth:1,borderBottomColor:colors.divider,backgroundColor:colors.surface},
  tabHeader:{minHeight:70,paddingHorizontal:layout.horizontalPadding,paddingTop:spacing.sm,paddingBottom:spacing.xs,borderBottomWidth:1,borderBottomColor:colors.divider,backgroundColor:colors.canvas},
  tabBotIcon:{display:'none'},tabTitle:{color:colors.text,fontSize:22,lineHeight:30,fontWeight:'700'},headerCopy:{alignItems:'center'},topTitle:{color:colors.text,...typography.label},
  onlineRow:{flexDirection:'row',alignItems:'center',gap:spacing.xs,marginTop:spacing.xxs},onlineDot:{display:'none'},onlineText:{color:colors.textMuted,...typography.caption},spacer:{width:layout.minTouch},
  list:{width:'100%',maxWidth:layout.maxContentWidth,alignSelf:'center',flexGrow:1,paddingHorizontal:layout.compactHorizontalPadding,paddingTop:spacing.md,paddingBottom:spacing.md},
  messageRow:{flexDirection:'row',alignItems:'flex-start',gap:spacing.xs,marginBottom:spacing.lg},userRow:{justifyContent:'flex-end'},avatar:{width:30,height:30,alignItems:'center',justifyContent:'center',borderRadius:15,backgroundColor:colors.surfaceStrong},messageColumn:{maxWidth:'78%'},
  bubble:{paddingHorizontal:spacing.md,paddingVertical:spacing.sm,borderRadius:radius.lg},assistantBubble:{borderTopLeftRadius:radius.sm,backgroundColor:colors.surfaceSubtle},userBubble:{borderTopRightRadius:radius.sm,backgroundColor:colors.primary},messageText:{color:colors.textSecondary,...typography.body},userText:{color:colors.white},messagePhoto:{width:180,height:130,marginBottom:spacing.xs,borderRadius:radius.lg,backgroundColor:colors.surfaceStrong},
  referenceBox:{marginTop:spacing.xs,paddingVertical:spacing.sm,borderTopWidth:1,borderBottomWidth:1,borderColor:colors.primaryBorder},referenceTitle:{marginBottom:spacing.xs,color:colors.primary,...typography.caption,fontWeight:'800'},referenceRow:{minHeight:36,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:spacing.sm},referenceLabel:{flex:1,color:colors.textMuted,...typography.caption},referenceValue:{color:colors.text,...typography.caption,fontWeight:'800'},
  medicineCard:{marginTop:spacing.sm,paddingVertical:spacing.md,borderTopWidth:1,borderBottomWidth:1,borderColor:colors.divider},medicineEyebrow:{color:colors.primary,...typography.caption,fontWeight:'800'},medicineName:{marginTop:spacing.xs,color:colors.text,...typography.sectionTitle},medicineIngredient:{marginTop:spacing.xxs,color:colors.textSecondary,fontSize:13},medicineLabel:{marginTop:spacing.md,color:colors.text,...typography.label},medicineText:{marginTop:spacing.xxs,color:colors.textSecondary,fontSize:13,lineHeight:20},caution:{marginTop:spacing.xs,color:colors.textSecondary,...typography.caption},sourceLink:{minHeight:layout.minTouch,flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:spacing.sm,borderTopWidth:1,borderTopColor:colors.divider},sourceText:{flex:1,color:colors.primary,...typography.caption,fontWeight:'800'},medicineLimit:{padding:spacing.sm,borderRadius:radius.md,backgroundColor:colors.warningSoft,color:colors.warning,fontSize:11,lineHeight:17},
  actionButton:{minHeight:layout.minTouch,flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:spacing.xs,paddingHorizontal:spacing.sm,borderWidth:1,borderColor:colors.primaryBorder,borderRadius:radius.md,backgroundColor:colors.primarySoft},actionText:{color:colors.primary,...typography.caption,fontWeight:'800'},
  typing:{flexDirection:'row',alignItems:'center',gap:spacing.xs,marginBottom:spacing.md},typingBubble:{minHeight:44,flexDirection:'row',alignItems:'center',gap:spacing.xs,paddingHorizontal:spacing.sm,borderRadius:radius.lg,borderTopLeftRadius:radius.sm,backgroundColor:colors.surface},typingText:{color:colors.textMuted,...typography.caption},errorCard:{alignItems:'center',marginBottom:spacing.sm,padding:spacing.sm,borderRadius:radius.md,backgroundColor:colors.dangerSoft},errorText:{color:colors.danger,fontSize:13},retry:{minHeight:layout.minTouch,justifyContent:'center',paddingHorizontal:spacing.sm},retryText:{color:colors.danger,...typography.label},
  suggestionWrap:{borderTopWidth:1,borderTopColor:colors.divider,backgroundColor:colors.surface},suggestionLabel:{paddingHorizontal:layout.compactHorizontalPadding,paddingTop:spacing.xs,color:colors.textMuted,...typography.caption,fontWeight:'800'},suggestions:{gap:spacing.xs,paddingHorizontal:layout.compactHorizontalPadding,paddingVertical:spacing.xs},suggestion:{minHeight:layout.minTouch,justifyContent:'center',paddingHorizontal:spacing.sm,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,backgroundColor:colors.surface},suggestionText:{color:colors.textSecondary,...typography.caption,fontWeight:'700'},
  attachment:{minHeight:62,flexDirection:'row',alignItems:'center',gap:spacing.sm,paddingHorizontal:layout.compactHorizontalPadding,borderTopWidth:1,borderTopColor:colors.divider,backgroundColor:colors.surface},attachmentImage:{width:46,height:46,borderRadius:radius.sm},attachmentText:{flex:1,color:colors.text,...typography.label},attachmentRemove:{width:layout.minTouch,height:layout.minTouch,alignItems:'center',justifyContent:'center'},
  composer:{flexDirection:'row',alignItems:'flex-end',gap:spacing.xs,paddingHorizontal:spacing.sm,paddingTop:spacing.sm,borderTopWidth:1,borderTopColor:colors.divider,backgroundColor:colors.surface},attach:{width:48,height:48,alignItems:'center',justifyContent:'center',borderRadius:radius.md,backgroundColor:colors.surfaceSubtle},input:{flex:1,maxHeight:108,minHeight:48,paddingHorizontal:spacing.md,paddingVertical:spacing.sm,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,backgroundColor:colors.surface,color:colors.text,fontSize:15,lineHeight:21},send:{width:48,height:48,alignItems:'center',justifyContent:'center',borderRadius:radius.md,backgroundColor:colors.primary},sendDisabled:{opacity:.38},pressed:{opacity:motion.pressOpacity},
});
