import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, Text, View } from 'react-native';
import { useFocusEffect, useRouter } from 'expo-router';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import type { RecordsMonth, WellnessRecordSummary } from '@/domain/wellness';
import { useAsyncData } from '@/hooks/use-async-data';
import { wellnessApi } from '@/services/wellness-api';
import { AppIcon } from '@/components/app-icon';
import { colors } from '@/theme/tokens';
import { styles } from './records-calendar.styles';

const WEEKDAYS = ['일', '월', '화', '수', '목', '금', '토'];
const EMPTY: RecordsMonth = { year: 0, month: 0, records: [], stats: { recordedDays: 0, averageSleep: '-', discomfortDays: 0 } };
const id = (year: number, month: number, day: number) => `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;

export default function RecordsCalendarScreen() {
  const router = useRouter(); const insets = useSafeAreaInsets(); const today = useMemo(() => new Date(), []); const todayId = id(today.getFullYear(), today.getMonth() + 1, today.getDate());
  const [cursor, setCursor] = useState({ year: today.getFullYear(), month: today.getMonth() + 1 }); const [selected, setSelected] = useState(todayId);
  const [filter, setFilter] = useState<'all' | 'discomfort' | 'routine'>('all');
  const loader = useCallback(() => wellnessApi.getRecordsMonth(cursor.year, cursor.month), [cursor]); const { data, error, isLoading, reload } = useAsyncData(loader, EMPTY);
  useFocusEffect(useCallback(() => { void reload().catch(() => undefined); }, [reload]));
  const visibleRecords = useMemo(() => data.records.filter((item) => filter === 'all' || (filter === 'discomfort' ? item.bodyParts.length > 0 : item.routineCompleted)), [data.records, filter]);
  const map = useMemo(() => new Map(visibleRecords.map((record) => [record.date, record])), [visibleRecords]); const record = map.get(selected); const days = new Date(cursor.year, cursor.month, 0).getDate(); const leading = new Date(cursor.year, cursor.month - 1, 1).getDay(); const cells = Array.from({ length: Math.ceil((leading + days) / 7) * 7 }, (_, index) => index < leading || index >= leading + days ? null : index - leading + 1);
  const move = (delta: number) => { const next = new Date(cursor.year, cursor.month - 1 + delta, 1); setCursor({ year: next.getFullYear(), month: next.getMonth() + 1 }); };
  useEffect(() => { if (!isLoading && data.year === cursor.year && data.month === cursor.month) setSelected(cursor.year === today.getFullYear() && cursor.month === today.getMonth() + 1 ? todayId : data.records[0]?.date ?? id(cursor.year, cursor.month, 1)); }, [cursor, data, isLoading, today, todayId]);
  const openRecord = (date: string, existing?: WellnessRecordSummary) => { if (!existing || date === todayId) router.push({ pathname: '/check/auto', params: { date, mode: existing ? 'edit' : 'create' } }); else setSelected(date); };
  return <SafeAreaView edges={['top']} style={styles.screen}><ScrollView contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + 148 }]} showsVerticalScrollIndicator={false}>
    <View style={styles.pageHeader}><Text accessibilityRole="header" style={styles.title}>기록</Text><Pressable accessibilityRole="button" onPress={() => router.push('/reports/setup')} style={styles.summaryPill}><Text style={styles.summaryPillText}>요약 만들기</Text></Pressable></View>
    <View accessibilityRole="tablist" style={styles.filters}>{([['all', '전체'], ['discomfort', '불편 있음'], ['routine', '루틴 완료']] as const).map(([value, label]) => <Pressable accessibilityRole="tab" accessibilityState={{ selected: filter === value }} key={value} onPress={() => setFilter(value)} style={filter === value ? styles.filterSelected : styles.filter}><Text style={filter === value ? styles.filterSelectedText : styles.filterText}>{label}</Text></Pressable>)}</View>
    <View style={styles.calendar}><View style={styles.monthBar}><Pressable accessibilityLabel="이전 달" onPress={() => move(-1)} style={styles.monthButton}><AppIcon color={colors.text} name="chevron-left" size={20} /></Pressable><Text style={styles.month}>{cursor.year}년 {cursor.month}월</Text><Pressable accessibilityLabel="다음 달" disabled={cursor.year === today.getFullYear() && cursor.month >= today.getMonth() + 1} onPress={() => move(1)} style={styles.monthButton}><AppIcon color={colors.text} name="chevron-right" size={20} /></Pressable></View><View style={styles.week}>{WEEKDAYS.map((day, index) => <Text key={day} style={[styles.weekday, index === 0 && styles.sundayHeader, index === 6 && styles.saturdayHeader]}>{day}</Text>)}</View>{isLoading ? <View style={styles.calendarState}><ActivityIndicator color={colors.primary} /></View> : error ? <View style={styles.calendarState}><Text style={styles.stateText}>기록을 불러오지 못했어요.</Text><Pressable onPress={() => void reload().catch(() => undefined)}><Text style={styles.retryText}>다시 시도</Text></Pressable></View> : <View style={styles.grid}>{cells.map((day, index) => { if (!day) return <View key={`empty-${index}`} style={styles.day} />; const date = id(cursor.year, cursor.month, day); const entry = map.get(date); const future = date > todayId; const chosen = date === selected; return <Pressable key={date} disabled={future} onPress={() => openRecord(date, entry)} style={[styles.day, chosen && styles.daySelected, future && styles.dayFuture]}><Text style={[styles.dayText, index % 7 === 0 && styles.sundayText, index % 7 === 6 && styles.saturdayText, chosen && styles.dayTextSelected]}>{day}</Text>{entry ? <View style={[styles.dot, entry.conditionTone === 'danger' ? styles.dotCoral : entry.conditionTone === 'caution' ? styles.dotCaution : styles.dotBlue]} /> : date === todayId ? <View style={styles.today} /> : null}</Pressable>; })}</View>}<View style={styles.legend}><Legend color={colors.primary} label="불편 없음"/><Legend color="#F5A623" label="가벼움"/><Legend color={colors.body} label="뚜렷함"/></View></View>
    <RecordReadout date={selected} record={record} isToday={selected === todayId} onCreate={() => router.push({ pathname: '/check/auto', params: { date: selected, mode: 'create' } })} onEdit={() => router.push({ pathname: '/check/auto', params: { date: selected, mode: 'edit' } })} onOpen={() => router.push({ pathname: '/records/[date]', params: { date: selected } })} />
    <Pressable onPress={() => router.push('/reports/setup')} style={styles.report}><View><Text style={styles.reportTitle}>기록 요약 만들기</Text><Text style={styles.reportDescription}>선택한 기간의 변화를 한 장으로 정리합니다.</Text></View><AppIcon color={colors.primary} name="arrow-up-right" size={18} /></Pressable>
  </ScrollView></SafeAreaView>;
}
function RecordReadout({ date, isToday, onCreate, onEdit, onOpen, record }: { date: string; isToday: boolean; onCreate: () => void; onEdit: () => void; onOpen: () => void; record?: WellnessRecordSummary }) { const [, month, day] = date.split('-').map(Number); return <View style={styles.readout}><Text style={styles.readoutDate}>{month}월 {day}일</Text>{record ? <><View style={styles.readoutTop}><View><Text style={styles.readoutLabel}>CONDITION</Text><Text style={styles.readoutTitle}>{record.condition}</Text></View><Text style={styles.readoutTone}>{record.bodyParts.join(', ') || '불편 없음'}</Text></View><Row label="수면" value={record.sleepDuration} /><Row label="걸음" value={record.steps} /><Row label="메모" value={record.memo || '남겨진 메모 없음'} /><View style={styles.readoutActions}>{isToday ? <Pressable onPress={onEdit} style={styles.primaryAction}><Text style={styles.primaryActionText}>수정하기</Text></Pressable> : null}<Pressable onPress={onOpen} style={styles.secondaryAction}><Text style={styles.secondaryActionText}>전체 기록 보기</Text></Pressable></View></> : <><Text style={styles.emptyTitle}>{isToday ? '오늘 기록을 시작해 주세요.' : '이 날의 상태를 기록해 보세요.'}</Text><Text style={styles.emptyCopy}>기록이 쌓일수록 나의 변화가 더 선명해집니다.</Text><Pressable onPress={onCreate} style={styles.primaryAction}><Text style={styles.primaryActionText}>기록 시작하기</Text></Pressable></>}</View>; }
function Row({ label, value }: { label: string; value: string }) { return <View style={styles.row}><Text style={styles.rowLabel}>{label}</Text><Text style={styles.rowValue}>{value}</Text></View>; }
function Legend({ color, label }: { color: string; label: string }) { return <View style={styles.legendItem}><View style={[styles.legendDot, { backgroundColor: color }]}/><Text style={styles.legendText}>{label}</Text></View>; }
