import { StyleSheet } from 'react-native';
import { colors, layout, radius, spacing, typography } from '@/theme/tokens';

export const detailStyles=StyleSheet.create({
  screen:{flex:1,backgroundColor:colors.canvas},center:{flex:1,alignItems:'center',justifyContent:'center',padding:spacing.xl,backgroundColor:colors.canvas},centerText:{marginTop:spacing.sm,color:colors.textMuted,...typography.caption},errorTitle:{color:colors.text,...typography.sectionTitle},retryButton:{minWidth:120,minHeight:48,alignItems:'center',justifyContent:'center',marginTop:spacing.md,borderWidth:1,borderColor:colors.border},retryText:{color:colors.text,...typography.label},
  topBar:{minHeight:60,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:spacing.sm,paddingVertical:spacing.xxs,borderBottomWidth:1,borderBottomColor:colors.divider,backgroundColor:colors.surface},topTitle:{flex:1,flexShrink:1,color:colors.text,...typography.label},topAction:{minWidth:layout.minTouch,minHeight:layout.minTouch,alignItems:'center',justifyContent:'center'},topActionText:{color:colors.primary,...typography.caption,fontWeight:'700'},topSpacer:{width:layout.minTouch},content:{width:'100%',maxWidth:layout.maxContentWidth,alignSelf:'center'},
  bodyOverview:{minHeight:184,flexDirection:'row',alignItems:'center',gap:18,paddingHorizontal:layout.horizontalPadding,backgroundColor:colors.surface},bodyFigure:{width:92,alignItems:'center'},bodySummary:{flex:1},discomfortBadge:{paddingVertical:6,paddingHorizontal:12,borderRadius:16,color:colors.danger,backgroundColor:colors.dangerSoft,...typography.caption,fontWeight:'700'},bodyPartRow:{flexDirection:'row',alignItems:'center',gap:8,marginTop:8},bodyDot:{width:7,height:7,borderRadius:4,backgroundColor:colors.danger},bodyPartText:{color:colors.text,...typography.caption,fontWeight:'700'},
  date:{color:colors.body,...typography.caption,fontWeight:'700',letterSpacing:.8},condition:{maxWidth:430,marginTop:spacing.xs,color:colors.text,...typography.display},tagRow:{flexDirection:'row',flexWrap:'wrap',gap:spacing.md,marginTop:spacing.md,paddingVertical:spacing.sm,borderTopWidth:1,borderBottomWidth:1,borderColor:colors.divider},tag:{color:colors.textSecondary,...typography.caption,fontWeight:'700'},
  section:{marginTop:10,paddingHorizontal:layout.horizontalPadding,paddingTop:16,backgroundColor:colors.surface},sectionHead:{minHeight:34,flexDirection:'row',alignItems:'center',gap:8},sectionIcon:{width:28,height:28,alignItems:'center',justifyContent:'center',borderRadius:10,backgroundColor:colors.primarySoft},sectionIconDanger:{backgroundColor:colors.dangerSoft},sectionTitle:{flex:1,color:colors.text,...typography.label},sourceBadge:{paddingHorizontal:9,paddingVertical:5,overflow:'hidden',borderRadius:radius.pill,color:colors.textMuted,backgroundColor:colors.surfaceSubtle,fontSize:10.5,lineHeight:15,fontWeight:'700'},sectionBody:{marginTop:4},infoRow:{minHeight:54,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:spacing.md,borderBottomWidth:1,borderBottomColor:colors.divider},infoLabel:{color:colors.textMuted,fontSize:13},infoValue:{flex:1,textAlign:'right',color:colors.text,fontSize:14,fontWeight:'700'},infoDanger:{color:colors.danger},memoCard:{marginTop:10,padding:layout.horizontalPadding,backgroundColor:colors.surface},memoText:{marginTop:spacing.xs,color:colors.textSecondary,...typography.body},
  reportEntry:{minHeight:72,flexDirection:'row',alignItems:'center',gap:spacing.md,marginTop:spacing.xxl,paddingHorizontal:layout.horizontalPadding,paddingVertical:spacing.md,borderTopWidth:1,borderBottomWidth:1,borderColor:colors.divider,backgroundColor:colors.surface},reportCopy:{flex:1},reportTitle:{color:colors.text,...typography.label},reportDescription:{marginTop:spacing.xxs,color:colors.textMuted,...typography.caption},recordActions:{paddingHorizontal:layout.horizontalPadding,paddingTop:spacing.xl,paddingBottom:spacing.xl,backgroundColor:colors.surface},editRecord:{minHeight:52,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:colors.border,borderRadius:radius.pill},editRecordText:{color:colors.text,...typography.label},deleteRecord:{minHeight:48,alignItems:'center',justifyContent:'center',marginTop:spacing.sm},deleteRecordText:{color:colors.danger,...typography.label},pressed:{opacity:.62},
});
