import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#FFFFFF' },
  content: { paddingHorizontal: 24, paddingTop: 24 },
  eyebrow: { color: '#1257E0', fontSize: 13, fontWeight: '800' },
  title: { marginTop: 4, color: '#17191C', fontSize: 30, lineHeight: 40, fontWeight: '800', letterSpacing: -1 },
  description: { marginTop: 6, color: '#737B88', fontSize: 14, lineHeight: 21 },
  statsRow: { flexDirection: 'row', gap: 8, marginTop: 22 },
  statCard: { flex: 1, minHeight: 76, alignItems: 'center', justifyContent: 'center', borderRadius: 14, backgroundColor: '#F7F8FA' },
  statValue: { color: '#17191C', fontSize: 16, fontWeight: '800' },
  statLabel: { marginTop: 5, color: '#8B919B', fontSize: 10.5, fontWeight: '700' },
  calendarCard: { marginTop: 16, paddingHorizontal: 12, paddingTop: 10, paddingBottom: 14, borderWidth: 1, borderColor: '#E7EAEF', borderRadius: 20, backgroundColor: '#FFFFFF' },
  monthHeader: { height: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  monthButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 12 },
  disabledMonthButton: { opacity: 0.35 },
  monthChevron: { color: '#17191C', fontSize: 32, lineHeight: 34, fontWeight: '400' },
  disabledMonthChevron: { color: '#A4A9B2' },
  monthTitle: { color: '#17191C', fontSize: 17, fontWeight: '800' },
  weekRow: { flexDirection: 'row', marginTop: 2 },
  weekday: { width: '14.2857%', paddingVertical: 8, textAlign: 'center', color: '#8B919B', fontSize: 11, fontWeight: '700' },
  calendarGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  dayCell: { width: '14.2857%', height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 12 },
  selectedDayCell: { backgroundColor: '#17191C' },
  dayText: { color: '#343941', fontSize: 14, fontWeight: '700' },
  selectedDayText: { color: '#FFFFFF' },
  sunday: { color: '#E5484D' },
  saturday: { color: '#1257E0' },
  recordDot: { position: 'absolute', bottom: 5, width: 4, height: 4, borderRadius: 2 },
  goodDot: { backgroundColor: '#31A36B' },
  cautionDot: { backgroundColor: '#F2A65A' },
  dangerDot: { backgroundColor: '#E5484D' },
  todayDot: { position: 'absolute', bottom: 5, width: 4, height: 4, borderRadius: 2, backgroundColor: '#B8BEC8' },
  calendarLoading: { minHeight: 220, alignItems: 'center', justifyContent: 'center' },
  loadingText: { marginTop: 10, color: '#8B919B', fontSize: 12, fontWeight: '600' },
  errorText: { color: '#4A4F58', fontSize: 14, fontWeight: '700' },
  retryButton: { minWidth: 96, minHeight: 44, alignItems: 'center', justifyContent: 'center', marginTop: 10, borderRadius: 12, backgroundColor: '#EEF3FF' },
  retryText: { color: '#1257E0', fontSize: 13, fontWeight: '800' },
  detailCard: { marginTop: 16, padding: 18, borderRadius: 18, backgroundColor: '#F7F8FA' },
  detailHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 },
  detailDate: { color: '#8B919B', fontSize: 12, fontWeight: '700' },
  detailCondition: { marginTop: 5, color: '#17191C', fontSize: 20, fontWeight: '800' },
  conditionBadge: { maxWidth: 130, paddingHorizontal: 9, paddingVertical: 6, borderRadius: 9 },
  dangerBadge: { backgroundColor: '#FDECEC' },
  cautionBadge: { backgroundColor: '#FFF2E8' },
  goodBadge: { backgroundColor: '#EAF7F0' },
  conditionBadgeText: { color: '#4A4F58', fontSize: 11, fontWeight: '800' },
  detailDivider: { height: 1, marginVertical: 14, backgroundColor: '#E3E6EA' },
  detailRow: { minHeight: 36, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  detailLabel: { color: '#737B88', fontSize: 13 },
  detailValue: { color: '#17191C', fontSize: 13, fontWeight: '700' },
  memoBox: { marginTop: 10, padding: 12, borderRadius: 12, backgroundColor: '#FFFFFF' },
  memoLabel: { color: '#8B919B', fontSize: 11, fontWeight: '700' },
  memoText: { marginTop: 5, color: '#4A4F58', fontSize: 13, lineHeight: 20 },
  detailButton: { minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, marginTop: 14, borderRadius: 12, backgroundColor: '#FFFFFF' },
  detailButtonText: { color: '#1257E0', fontSize: 13, fontWeight: '800' },
  detailButtonChevron: { color: '#1257E0', fontSize: 20 },
  emptyDetail: { marginTop: 16, alignItems: 'center', padding: 22, borderWidth: 1, borderColor: '#E7EAEF', borderRadius: 18, borderStyle: 'dashed' },
  emptyTitle: { marginTop: 8, color: '#17191C', fontSize: 18, fontWeight: '800' },
  emptyDescription: { marginTop: 6, textAlign: 'center', color: '#737B88', fontSize: 13, lineHeight: 20 },
  recordButton: { minWidth: 150, minHeight: 46, alignItems: 'center', justifyContent: 'center', marginTop: 16, borderRadius: 12, backgroundColor: '#17191C' },
  recordButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: '800' },
  pressed: { opacity: 0.55 },
});
