import { StyleSheet } from 'react-native';
import { colors, layout, motion, radius, spacing, typography } from '@/theme/tokens';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.canvas },
  content: { width: '100%', maxWidth: layout.maxContentWidth, alignSelf: 'center', paddingHorizontal: layout.horizontalPadding, paddingTop: spacing.xl },
  eyebrow: { color: colors.primary, ...typography.caption, fontWeight: '800' },
  title: { marginTop: spacing.xxs, color: colors.text, ...typography.display },
  description: { marginTop: spacing.xs, color: colors.textMuted, ...typography.body },
  reportEntry: { minHeight: 76, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: spacing.lg, paddingHorizontal: spacing.md, borderWidth: 1, borderColor: colors.primaryBorder, borderRadius: radius.lg, backgroundColor: colors.primarySoft },
  reportEntryTitle: { color: colors.text, ...typography.label },
  reportEntryDescription: { marginTop: spacing.xxs, color: colors.textSecondary, ...typography.caption },
  reportEntryArrow: { color: colors.primary, fontSize: 26 },
  statsRow: { flexDirection: 'row', marginTop: spacing.xl, paddingVertical: spacing.xs, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.divider },
  statCard: { flex: 1, minHeight: 64, alignItems: 'center', justifyContent: 'center' },
  statValue: { color: colors.text, fontSize: 16, fontWeight: '800' },
  statLabel: { marginTop: spacing.xxs, color: colors.textMuted, ...typography.caption, fontWeight: '700' },
  calendarCard: { marginTop: spacing.md, paddingHorizontal: spacing.xs, paddingTop: spacing.xs, paddingBottom: spacing.sm, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.divider },
  monthHeader: { height: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  monthButton: { width: layout.minTouch, height: layout.minTouch, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md },
  disabledMonthButton: { opacity: 0.35 },
  monthChevron: { color: colors.text, fontSize: 32, lineHeight: 34 },
  disabledMonthChevron: { color: colors.textMuted },
  monthTitle: { color: colors.text, fontSize: 17, fontWeight: '800' },
  weekRow: { flexDirection: 'row', marginTop: spacing.xxs },
  weekday: { width: '14.2857%', paddingVertical: spacing.xs, textAlign: 'center', color: colors.textMuted, fontSize: 11, fontWeight: '700' },
  calendarGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  dayCell: { width: '14.2857%', height: layout.minTouch, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md },
  selectedDayCell: { backgroundColor: colors.primary },
  dayText: { color: colors.textSecondary, fontSize: 14, fontWeight: '700' },
  selectedDayText: { color: colors.white },
  sunday: { color: colors.danger },
  saturday: { color: colors.primary },
  recordDot: { position: 'absolute', bottom: 5, width: 4, height: 4, borderRadius: 2 },
  goodDot: { backgroundColor: colors.success },
  cautionDot: { backgroundColor: colors.warning },
  dangerDot: { backgroundColor: colors.danger },
  todayDot: { position: 'absolute', bottom: 5, width: 4, height: 4, borderRadius: 2, backgroundColor: colors.textMuted },
  calendarLoading: { minHeight: 220, alignItems: 'center', justifyContent: 'center' },
  loadingText: { marginTop: spacing.sm, color: colors.textMuted, ...typography.caption },
  errorText: { color: colors.textSecondary, ...typography.label },
  retryButton: { minWidth: 96, minHeight: layout.minTouch, alignItems: 'center', justifyContent: 'center', marginTop: spacing.sm, borderRadius: radius.md, backgroundColor: colors.primarySoft },
  retryText: { color: colors.primary, ...typography.label },
  detailCard: { marginTop: spacing.md, paddingVertical: spacing.lg, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.divider },
  detailHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: spacing.sm },
  detailDate: { color: colors.textMuted, ...typography.caption },
  detailCondition: { marginTop: spacing.xxs, color: colors.text, ...typography.sectionTitle },
  conditionBadge: { maxWidth: 130, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs, borderRadius: radius.md },
  dangerBadge: { backgroundColor: colors.dangerSoft }, cautionBadge: { backgroundColor: colors.warningSoft }, goodBadge: { backgroundColor: colors.successSoft },
  conditionBadgeText: { color: colors.textSecondary, fontSize: 11, fontWeight: '800' },
  detailDivider: { height: 1, marginVertical: spacing.md, backgroundColor: colors.divider },
  detailRow: { minHeight: layout.minTouch, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  detailLabel: { color: colors.textMuted, fontSize: 13 }, detailValue: { color: colors.text, fontSize: 13, fontWeight: '700' },
  memoBox: { marginTop: spacing.sm, paddingVertical: spacing.sm, borderTopWidth: 1, borderColor: colors.divider },
  memoLabel: { color: colors.textMuted, ...typography.caption }, memoText: { marginTop: spacing.xxs, color: colors.textSecondary, fontSize: 13, lineHeight: 20 },
  detailButton: { minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.xs, marginTop: spacing.sm, borderWidth: 1, borderColor: colors.primaryBorder, borderRadius: radius.md, backgroundColor: colors.surface },
  detailButtonText: { color: colors.primary, ...typography.label }, detailButtonChevron: { color: colors.primary, fontSize: 20 },
  emptyDetail: { marginTop: spacing.md, alignItems: 'center', paddingVertical: spacing.xl, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.divider },
  emptyTitle: { marginTop: spacing.xs, color: colors.text, ...typography.sectionTitle }, emptyDescription: { marginTop: spacing.xs, textAlign: 'center', color: colors.textMuted, fontSize: 13, lineHeight: 20 },
  recordButton: { minWidth: 150, minHeight: 48, alignItems: 'center', justifyContent: 'center', marginTop: spacing.md, borderRadius: radius.md, backgroundColor: colors.primary },
  recordButtonText: { color: colors.white, ...typography.label }, pressed: { opacity: motion.pressOpacity },
});
