import { StyleSheet } from 'react-native';
import { colors, layout, spacing, typography } from '@/theme/tokens';

export const detailStyles=StyleSheet.create({
  screen:{flex:1,backgroundColor:colors.canvas},center:{flex:1,alignItems:'center',justifyContent:'center',padding:spacing.xl,backgroundColor:colors.canvas},centerText:{marginTop:spacing.sm,color:colors.textMuted,...typography.caption},errorTitle:{color:colors.text,...typography.sectionTitle},retryButton:{minWidth:120,minHeight:48,alignItems:'center',justifyContent:'center',marginTop:spacing.md,borderWidth:1,borderColor:colors.border},retryText:{color:colors.text,...typography.label},
  topBar:{minHeight:60,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:spacing.sm,paddingVertical:spacing.xxs,borderBottomWidth:1,borderBottomColor:colors.divider,backgroundColor:colors.surface},topTitle:{flex:1,flexShrink:1,textAlign:'center',color:colors.text,...typography.label},topSpacer:{width:layout.minTouch},content:{width:'100%',maxWidth:layout.maxContentWidth,alignSelf:'center',paddingHorizontal:layout.horizontalPadding,paddingTop:spacing.xl},
  date:{color:colors.body,...typography.caption,fontWeight:'700',letterSpacing:.8},condition:{maxWidth:430,marginTop:spacing.xs,color:colors.text,...typography.display},tagRow:{flexDirection:'row',flexWrap:'wrap',gap:spacing.md,marginTop:spacing.md,paddingVertical:spacing.sm,borderTopWidth:1,borderBottomWidth:1,borderColor:colors.divider},tag:{color:colors.textSecondary,...typography.caption,fontWeight:'700'},
  section:{marginTop:spacing.xxl},sectionTitle:{color:colors.text,...typography.sectionTitle},sectionBody:{marginTop:spacing.sm,borderTopWidth:1,borderTopColor:colors.border},infoRow:{minHeight:58,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:spacing.md,borderBottomWidth:1,borderBottomColor:colors.divider},infoLabel:{color:colors.textMuted,fontSize:13},infoValue:{flex:1,textAlign:'right',color:colors.text,fontSize:14,fontWeight:'700'},memoCard:{marginTop:spacing.xxl,paddingVertical:spacing.md,borderTopWidth:0,borderBottomWidth:1,borderColor:colors.warning},memoText:{marginTop:spacing.xs,color:colors.textSecondary,...typography.body},
  reportEntry:{minHeight:72,flexDirection:'row',alignItems:'center',gap:spacing.md,marginTop:spacing.xxl,paddingVertical:spacing.md,borderTopWidth:1,borderBottomWidth:1,borderColor:colors.divider},reportCopy:{flex:1},reportTitle:{color:colors.text,...typography.label},reportDescription:{marginTop:spacing.xxs,color:colors.textMuted,...typography.caption},pressed:{opacity:.62},
});
