import { ActivityIndicator, Pressable, ScrollView, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import NavigationBackButton from '@/components/navigation-back-button';
import type { SignalSummary } from '@/domain/wellness';
import { useAsyncData } from '@/hooks/use-async-data';
import { wellnessApi } from '@/services/wellness-api';
import { styles } from './signal.styles';
export default function SignalScreen(){const router=useRouter();const insets=useSafeAreaInsets();const{data,error,isLoading,reload}=useAsyncData<SignalSummary|null>(wellnessApi.getSignalSummary,null);if(isLoading)return <SafeAreaView edges={['top','bottom']} style={styles.center}><ActivityIndicator color="#EF7442"/></SafeAreaView>;if(error||!data)return <SafeAreaView edges={['top','bottom']} style={styles.center}><Text style={styles.errorTitle}>안내를 불러오지 못했어요</Text><Pressable onPress={()=>void reload().catch(()=>undefined)} style={styles.retry}><Text style={styles.retryText}>다시 시도</Text></Pressable></SafeAreaView>;return <SafeAreaView edges={['top']} style={styles.screen}><View style={styles.topBar}><NavigationBackButton accessibilityLabel="이전 화면으로" fallbackHref="/(tabs)/home"/><Text style={styles.topTitle}>지속 신호</Text><View style={styles.spacer}/></View><ScrollView contentContainerStyle={[styles.content,{paddingBottom:insets.bottom+40}]}><View style={styles.signalIcon}><Text style={styles.signalMark}>!</Text></View><Text style={styles.eyebrow}>기록에서 확인된 신호</Text><Text style={styles.title}>{data.title}</Text><Text style={styles.description}>{data.description}</Text><View style={styles.metric}><Text style={styles.metricValue}>{data.durationLabel}</Text><Text style={styles.metricLabel}>반복 기록 {data.occurrences}회</Text></View><Section title="확인된 기록">{data.evidence.map(item=><Row key={item} text={item}/>)}</Section><Section title="이렇게 대응해 보세요">{data.guidance.map(item=><Row key={item} text={item}/>)}</Section><View style={styles.notice}><Text style={styles.noticeText}>이 안내는 진단이 아니라 기록에서 반복된 흐름을 알려드리는 기능이에요.</Text></View><Pressable accessibilityRole="button" onPress={()=>router.push('/reports/setup')} style={styles.reportButton}><Text style={styles.reportText}>기록 요약 만들기</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>router.dismissTo('/(tabs)/home')} style={styles.homeButton}><Text style={styles.homeText}>오늘 화면으로</Text></Pressable></ScrollView></SafeAreaView>}
function Section({children,title}:{children:React.ReactNode;title:string}){return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>}function Row({text}:{text:string}){return <View style={styles.row}><Text style={styles.bullet}>•</Text><Text style={styles.rowText}>{text}</Text></View>}
