import { StyleSheet } from 'react-native';
import { colors, layout, motion, radius, spacing, typography } from '@/theme/tokens';

export const styles=StyleSheet.create({
  screen:{flex:1,backgroundColor:colors.surface},center:{flex:1,alignItems:'center',justifyContent:'center',padding:layout.horizontalPadding,backgroundColor:colors.surface},content:{width:'100%',maxWidth:layout.maxContentWidth,alignSelf:'center',padding:layout.horizontalPadding,backgroundColor:colors.surface},
  signalIcon:{width:44,height:44,alignItems:'center',justifyContent:'center',borderRadius:22,backgroundColor:colors.warningSoft},eyebrow:{marginTop:spacing.lg,color:colors.warning,...typography.caption,fontWeight:'600'},title:{marginTop:spacing.xs,color:colors.text,...typography.title},description:{marginTop:spacing.sm,color:colors.textSecondary,...typography.body},
  metric:{marginTop:spacing.xl,padding:spacing.lg,borderRadius:radius.lg,backgroundColor:colors.warningSoft},metricValue:{color:colors.warning,...typography.title},metricLabel:{marginTop:spacing.xs,color:colors.textMuted,...typography.caption},
  section:{marginTop:spacing.xl},sectionTitle:{marginBottom:spacing.xs,color:colors.text,...typography.sectionTitle},row:{flexDirection:'row',alignItems:'flex-start',gap:spacing.sm,marginTop:spacing.xs,padding:spacing.md,borderRadius:radius.md,backgroundColor:colors.surfaceSubtle},rowIcon:{width:24,height:24,alignItems:'center',justifyContent:'center'},rowText:{flex:1,color:colors.textSecondary,fontSize:14,lineHeight:21},
  notice:{flexDirection:'row',alignItems:'flex-start',gap:spacing.sm,marginTop:spacing.lg,padding:spacing.md,borderRadius:radius.md,backgroundColor:colors.surfaceSubtle},noticeText:{flex:1,color:colors.textSecondary,...typography.caption},
  reportButton:{minHeight:layout.ctaHeight,alignItems:'center',justifyContent:'center',marginTop:spacing.lg,borderRadius:radius.pill,backgroundColor:colors.primary},reportText:{color:colors.primaryText,fontSize:16,fontWeight:'700'},homeButton:{minHeight:48,alignItems:'center',justifyContent:'center'},homeText:{color:colors.textMuted,...typography.label},
  loadingText:{marginTop:spacing.sm,color:colors.textMuted,...typography.caption},errorTitle:{marginTop:spacing.md,color:colors.text,...typography.sectionTitle},errorDescription:{marginTop:spacing.xs,color:colors.textMuted,textAlign:'center',...typography.caption},retry:{minHeight:layout.minTouch,alignItems:'center',justifyContent:'center',marginTop:spacing.md,paddingHorizontal:spacing.lg,borderRadius:radius.md,backgroundColor:colors.primarySoft},retryText:{color:colors.primary,...typography.label},pressed:{opacity:motion.pressOpacity},
});
