import { StyleSheet } from 'react-native';
import { colors, layout, motion, radius, spacing, typography } from '@/theme/tokens';

export const styles = StyleSheet.create({
  screen:{flex:1,backgroundColor:colors.canvas},
  topBar:{minHeight:56,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:spacing.sm,paddingVertical:spacing.xxs,backgroundColor:colors.surface},topTitle:{flex:1,flexShrink:1,color:colors.text,textAlign:'center',fontSize:17,lineHeight:24,fontWeight:'700'},topSpacer:{width:layout.minTouch},
  content:{width:'100%',maxWidth:layout.maxContentWidth,alignSelf:'center',padding:layout.horizontalPadding},center:{flex:1,alignItems:'center',justifyContent:'center',padding:spacing.xl,backgroundColor:colors.canvas},loadingText:{marginTop:spacing.sm,color:colors.textMuted,...typography.caption},errorTitle:{color:colors.text,...typography.sectionTitle},retryButton:{minWidth:110,minHeight:layout.minTouch,alignItems:'center',justifyContent:'center',marginTop:spacing.md,borderRadius:radius.md,backgroundColor:colors.primarySoft},retryText:{color:colors.primary,...typography.label},
  hero:{marginTop:spacing.sm,padding:spacing.lg,borderRadius:radius.xl,backgroundColor:colors.recoverySoft},heroCopy:{maxWidth:390},heroVisual:{alignSelf:'center',marginTop:spacing.md},kicker:{color:colors.recovery,...typography.caption,fontWeight:'600'},target:{marginTop:spacing.sm,color:colors.recovery,...typography.label},title:{maxWidth:390,marginTop:spacing.xs,color:colors.text,...typography.title},description:{maxWidth:420,marginTop:spacing.xs,color:colors.textMuted,...typography.body},
  metaRow:{flexDirection:'row',flexWrap:'wrap',gap:spacing.xs,marginTop:spacing.md},meta:{paddingHorizontal:spacing.sm,paddingVertical:spacing.xs,borderRadius:radius.pill,backgroundColor:colors.surface,color:colors.recovery,fontSize:12,fontWeight:'600'},
  reasonCard:{marginTop:spacing.md,padding:spacing.md,borderRadius:radius.lg,backgroundColor:colors.surfaceSubtle},reasonLabel:{color:colors.recovery,...typography.caption,fontWeight:'600'},reason:{maxWidth:440,marginTop:spacing.xs,color:colors.textSecondary,...typography.body},
  sectionTitle:{marginTop:spacing.xl,marginBottom:spacing.sm,color:colors.text,...typography.sectionTitle},stepRow:{minHeight:88,flexDirection:'row',alignItems:'center',gap:spacing.sm,marginTop:spacing.xs,padding:spacing.md,borderRadius:radius.lg,backgroundColor:colors.surfaceSubtle},stepIndex:{width:32,height:32,flexShrink:0,alignItems:'center',justifyContent:'center',borderRadius:16,backgroundColor:colors.recoverySoft},stepIndexText:{color:colors.recovery,fontSize:12,lineHeight:16,fontWeight:'700'},stepCopy:{flex:1,flexShrink:1},stepTitle:{color:colors.text,fontSize:15,lineHeight:21,fontWeight:'600'},stepInstruction:{marginTop:spacing.xxs,color:colors.textMuted,fontSize:12,lineHeight:18},stepTime:{flexShrink:0,color:colors.textSecondary,fontSize:12,lineHeight:18,fontWeight:'600'},
  caution:{marginTop:spacing.lg,padding:spacing.md,borderRadius:radius.md,backgroundColor:colors.warningSoft},cautionLabel:{color:colors.warning,...typography.caption,fontWeight:'600'},cautionText:{marginTop:spacing.xs,color:colors.textSecondary,fontSize:12,lineHeight:19},
  bottomAction:{position:'absolute',right:0,bottom:0,left:0,paddingHorizontal:layout.horizontalPadding,paddingTop:spacing.sm,borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:colors.divider,backgroundColor:colors.surface},primaryButton:{minHeight:layout.ctaHeight,alignItems:'center',justifyContent:'center',borderRadius:radius.md,backgroundColor:colors.primary},primaryText:{color:colors.white,fontSize:16,fontWeight:'700'},pressed:{opacity:motion.pressOpacity},
});
