import { StyleSheet } from 'react-native';

import { colors, layer, layout, motion, radius, spacing, typography } from '@/theme/tokens';

export const styles = StyleSheet.create({
  screen: { flex: 1, overflow: 'hidden', backgroundColor: colors.surface },
  scrollContent: { flexGrow: 1, width: '100%', maxWidth: layout.maxContentWidth, alignSelf: 'center', overflow: 'hidden' },
  page: { width: '100%', paddingHorizontal: layout.horizontalPadding },
  loginBrand: { alignItems: 'center' },
  header: { alignItems: 'center', marginTop: 16 },
  title: { alignSelf: 'stretch', flexShrink: 1, color: colors.text, textAlign: 'center', ...typography.display },
  description: { alignSelf: 'stretch', flexShrink: 1, marginTop: spacing.xs, color: colors.textSecondary, textAlign: 'center', ...typography.body },
  form: { marginTop: 32, gap: 10 },
  forgotButton: { minHeight: layout.minTouch, alignSelf: 'flex-end', justifyContent: 'center' },
  forgotText: { color: colors.textSecondary, ...typography.caption },
  errorBand: { padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.dangerSoft },
  errorText: { color: colors.danger, ...typography.caption },
  actions: { marginTop: 16 },
  primaryButton: { minHeight: layout.ctaHeight, alignItems: 'center', justifyContent: 'center', borderRadius: radius.pill, backgroundColor: colors.primary },
  primaryButtonText: { color: colors.primaryText, ...typography.label, fontWeight: '700' },
  disabledButton: { backgroundColor: colors.disabled },
  signupRow: { minHeight: 62, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 14 },
  linkDivider: { width: 1, height: 14, backgroundColor: colors.divider },
  signupText: { color: colors.textMuted, ...typography.caption },
  signupLink: { color: colors.primaryPressed, ...typography.caption, fontWeight: '700' },
  social: { gap: spacing.sm },
  socialDivider: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, marginVertical: spacing.xs },
  socialRule: { flex: 1, height: 1, backgroundColor: colors.divider },
  socialLabel: { color: colors.textMuted, ...typography.caption },
  socialButton: { minHeight: 50, alignItems: 'center', justifyContent: 'center', borderRadius: radius.pill },
  kakao: { backgroundColor: '#FEE500' },
  naver: { backgroundColor: '#03C75A' },
  apple: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface },
  kakaoText: { color: '#191919', ...typography.label },
  socialWhite: { color: colors.white, ...typography.label },
  appleText: { color: colors.text, ...typography.label },
  preview: { paddingTop: spacing.xl, alignItems: 'center' },
  previewRule: { width: '100%', height: 1, backgroundColor: colors.divider },
  previewTitle: { marginTop: spacing.md, color: colors.textMuted, ...typography.caption },
  testAccount: { marginTop: spacing.xxs, color: colors.primaryPressed, ...typography.caption },
  previewButton: { minHeight: layout.minTouch, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  previewButtonText: { color: colors.text, ...typography.label },
  previewArrow: { color: colors.body, fontSize: 22, fontWeight: '700' },
  pressed: { opacity: motion.pressOpacity },
  modalRoot: { flex: 1, justifyContent: 'flex-end' },
  scrim: { ...StyleSheet.absoluteFillObject, zIndex: layer.sheet, backgroundColor: colors.scrim },
  resetSheet: { zIndex: layer.modal, paddingHorizontal: layout.horizontalPadding, paddingTop: spacing.sm, borderTopLeftRadius: radius.sheet, borderTopRightRadius: radius.sheet, backgroundColor: colors.surface },
  sheetHandle: { width: 38, height: 4, alignSelf: 'center', borderRadius: 2, backgroundColor: colors.border },
  resetTitle: { marginTop: spacing.lg, color: colors.text, ...typography.title },
  resetDescription: { marginTop: spacing.xs, color: colors.textSecondary, ...typography.body },
  resetField: { marginTop: spacing.xl },
  resetSuccess: { marginTop: spacing.md, color: colors.recovery, ...typography.caption },
  resetButton: { minHeight: layout.ctaHeight, alignItems: 'center', justifyContent: 'center', marginTop: spacing.lg, borderRadius: radius.pill, backgroundColor: colors.primary },
  resetButtonText: { color: colors.primaryText, ...typography.label },
});
