import { StyleSheet } from 'react-native';
import { colors, layer, layout, motion, radius, spacing, typography } from '@/theme/tokens';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.surface },
  scrollContent: { flexGrow: 1, width: '100%', maxWidth: layout.maxContentWidth, alignSelf: 'center', paddingHorizontal: layout.horizontalPadding },
  header: { marginTop: 56 },
  title: { maxWidth: 500, color: colors.text, ...typography.display },
  description: { maxWidth: 380, marginTop: spacing.sm, color: colors.textSecondary, ...typography.body },
  form: { marginTop: spacing.xxxl, gap: spacing.lg },
  forgotButton: { minHeight: layout.minTouch, alignSelf: 'flex-end', justifyContent: 'center' },
  forgotText: { color: colors.textSecondary, ...typography.caption, fontWeight: '700' },
  errorBand: { marginTop: spacing.xs, padding: spacing.sm, borderRadius: radius.md, backgroundColor: colors.dangerSoft },
  errorText: { color: colors.danger, ...typography.caption },
  actions: { marginTop: 'auto', paddingTop: spacing.xxxl },
  primaryButton: { minHeight: layout.ctaHeight, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colors.primary },
  primaryButtonText: { color: colors.white, fontSize: 16, fontWeight:'700' },
  disabledButton: { backgroundColor: colors.disabled },
  signupRow: { minHeight: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.xs },
  signupText: { color: colors.textMuted, ...typography.caption },
  signupLink: { color: colors.primary, ...typography.caption, fontWeight:'700' },
  preview: { paddingTop: spacing.lg },
  previewRule: { height: 1, backgroundColor: colors.divider },
  previewTitle: { marginTop: spacing.md, color: colors.textMuted, ...typography.caption },
  testAccount: { marginTop: spacing.xs, color: colors.primary, ...typography.label },
  previewButton: { minHeight: layout.minTouch, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  previewButtonText: { color: colors.text, ...typography.label },
  previewArrow: { color: colors.body, fontSize: 22, fontWeight: '700' },
  pressed: { opacity: motion.pressOpacity },
  modalRoot: { flex: 1, justifyContent: 'flex-end' },
  scrim: { ...StyleSheet.absoluteFillObject, zIndex: layer.sheet, backgroundColor: colors.scrim },
  resetSheet: { zIndex: layer.modal, paddingHorizontal: layout.horizontalPadding, paddingTop: spacing.sm, borderTopLeftRadius: radius.sheet, borderTopRightRadius: radius.sheet, backgroundColor: colors.surface },
  sheetHandle: { width: 38, height: 4, alignSelf: 'center', borderRadius: 2, backgroundColor: colors.border },
  resetTitle: { marginTop: spacing.lg, color: colors.text, ...typography.title },
  resetDescription: { marginTop: spacing.xs, color: colors.textSecondary, ...typography.body },
  resetField: { marginTop: spacing.xl },
  resetSuccess: { marginTop: spacing.md, color: colors.recovery, ...typography.caption },
  resetButton: { minHeight: layout.ctaHeight, alignItems: 'center', justifyContent: 'center', marginTop: spacing.lg, borderRadius: radius.md, backgroundColor: colors.primary },
  resetButtonText: { color: colors.white, ...typography.label },
});
