import { StyleSheet } from 'react-native';
import { colors, layout, motion, radius, spacing, typography } from '@/theme/tokens';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.surface },
  scrollContent: { flexGrow: 1, width: '100%', maxWidth: layout.maxContentWidth, alignSelf: 'center' },
  topBar: { minHeight: 64, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: spacing.xs },
  topTitle: { flex: 1, color: colors.text, ...typography.label },
  topSpacer: { width: layout.minTouch },
  header: { display: 'none' },
  title: { maxWidth: 500, color: colors.text, ...typography.display },
  description: { maxWidth: 460, marginTop: spacing.sm, color: colors.textSecondary, ...typography.body },
  form: { marginTop: 10, paddingHorizontal: layout.horizontalPadding, gap: 16 },
  fieldLabel: { marginBottom: spacing.xs, color: colors.textSecondary, ...typography.caption },
  emailRow: { flexDirection: 'row', gap: spacing.sm },
  emailInput: { flex: 1, minHeight: layout.controlHeight, paddingHorizontal: spacing.lg, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, color: colors.text, fontSize: 15 },
  verifyButton: { minWidth: 86, minHeight: layout.controlHeight, alignItems: 'center', justifyContent: 'center', paddingHorizontal: spacing.md, borderRadius: radius.pill, backgroundColor: colors.primarySoft },
  verifyDisabled: { opacity: 0.45 },
  verifyButtonText: { color: colors.primaryPressed, ...typography.caption, fontWeight: '700' },
  fieldError: { marginTop: spacing.xs, color: colors.danger, ...typography.caption },
  codeField: { minHeight: layout.controlHeight, flexDirection: 'row', alignItems: 'center', borderWidth: 1.5, borderColor: colors.primary, borderRadius: radius.md, paddingHorizontal: spacing.lg },
  codeFieldDone: { backgroundColor: colors.primarySoft },
  codeInput: { flex: 1, color: colors.text, fontSize: 17, fontWeight: '700', letterSpacing: 4 },
  timer: { color: colors.primaryPressed, ...typography.caption, fontWeight: '700' },
  codeHint: { marginTop: spacing.xs, color: colors.textMuted, ...typography.caption },
  verifiedText: { marginTop: spacing.xs, color: colors.primaryPressed, ...typography.caption },
  passwordRules: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md, marginTop: -spacing.sm },
  profileHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, profileHint: { color: colors.textMuted, ...typography.caption }, profileRow: { flexDirection: 'row', gap: 10 }, profileField: { flex: 1, minHeight: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md }, profilePlaceholder: { color: colors.placeholder, fontSize: 15 }, profileChevron: { color: colors.textMuted, fontSize: 18 },
  ruleItem: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  ruleDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.border },
  ruleDotChecked: { backgroundColor: colors.recovery },
  ruleText: { color: colors.textMuted, ...typography.caption },
  ruleTextChecked: { color: colors.recovery },
  agreementSection: { marginTop: spacing.xxl, marginHorizontal: layout.horizontalPadding, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.divider },
  agreementRow: { minHeight: 78, flexDirection: 'row', alignItems: 'center', gap: spacing.md },
  checkbox: { width: 26, height: 26, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: radius.sm },
  checkboxChecked: { borderColor: colors.brand, backgroundColor: colors.brand },
  agreementCopy: { flex: 1 },
  agreementTitle: { color: colors.text, ...typography.label },
  agreementDescription: { marginTop: spacing.xxs, color: colors.textMuted, ...typography.caption },
  agreementDetailButton: { minHeight: layout.minTouch, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: colors.divider },
  agreementDetailText: { color: colors.textSecondary, ...typography.caption, fontWeight: '700' },
  agreementDetail: { gap: spacing.xs, paddingVertical: spacing.md, borderTopWidth: 1, borderTopColor: colors.divider },
  detailText: { color: colors.textSecondary, ...typography.caption },
  errorBand: { marginHorizontal: layout.horizontalPadding, marginTop: spacing.md, padding: spacing.sm, borderRadius: radius.md, backgroundColor: colors.dangerSoft },
  errorText: { color: colors.danger, ...typography.caption },
  footer: { marginTop: 22, paddingHorizontal: layout.horizontalPadding, paddingTop: 10, borderTopWidth: 1, borderTopColor: colors.divider },
  notice: { marginBottom: spacing.md, color: colors.textMuted, ...typography.caption, textAlign: 'center' },
  nextButton: { minHeight: layout.ctaHeight, alignItems: 'center', justifyContent: 'center', borderRadius: radius.pill, backgroundColor: colors.primary },
  nextButtonText: { color: colors.primaryText, fontSize: 16, fontWeight:'700' },
  disabledButton: { backgroundColor: colors.disabled },
  pressed: { opacity: motion.pressOpacity },
});
