import { StyleSheet } from 'react-native';
import { colors, layout, motion, radius, spacing, typography } from '@/theme/tokens';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.surface },
  scrollContent: { flexGrow: 1, width: '100%', maxWidth: layout.maxContentWidth, alignSelf: 'center' },
  topBar: { minHeight: 64, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: spacing.xs },
  topSpacer: { width: layout.minTouch },
  header: { paddingHorizontal: layout.horizontalPadding, paddingTop: spacing.xl },
  title: { maxWidth: 500, color: colors.text, ...typography.display },
  description: { maxWidth: 460, marginTop: spacing.sm, color: colors.textSecondary, ...typography.body },
  form: { marginTop: spacing.xxl, paddingHorizontal: layout.horizontalPadding, gap: spacing.lg },
  passwordRules: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md, marginTop: -spacing.sm },
  ruleItem: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  ruleDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.border },
  ruleDotChecked: { backgroundColor: colors.recovery },
  ruleText: { color: colors.textMuted, ...typography.caption },
  ruleTextChecked: { color: colors.recovery },
  agreementSection: { marginTop: spacing.xxl, marginHorizontal: layout.horizontalPadding, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.divider },
  agreementRow: { minHeight: 78, flexDirection: 'row', alignItems: 'center', gap: spacing.md },
  checkbox: { width: 26, height: 26, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: radius.sm },
  checkboxChecked: { borderColor: colors.brand, backgroundColor: colors.brand },
  agreementCopy: { flex: 1 },
  agreementTitle: { color: colors.text, ...typography.label },
  agreementDescription: { marginTop: spacing.xxs, color: colors.textMuted, ...typography.caption },
  agreementDetailButton: { minHeight: layout.minTouch, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: colors.divider },
  agreementDetailText: { color: colors.textSecondary, ...typography.caption, fontWeight: '700' },
  agreementDetail: { gap: spacing.xs, paddingVertical: spacing.md, borderTopWidth: 1, borderTopColor: colors.divider },
  detailText: { color: colors.textSecondary, ...typography.caption },
  errorBand: { marginHorizontal: layout.horizontalPadding, marginTop: spacing.md, padding: spacing.sm, borderRadius: radius.md, backgroundColor: colors.dangerSoft },
  errorText: { color: colors.danger, ...typography.caption },
  footer: { marginTop: 'auto', paddingHorizontal: layout.horizontalPadding, paddingTop: spacing.xxl },
  notice: { marginBottom: spacing.md, color: colors.textMuted, ...typography.caption, textAlign: 'center' },
  nextButton: { minHeight: layout.ctaHeight, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colors.primary },
  nextButtonText: { color: colors.white, fontSize: 16, fontWeight:'700' },
  disabledButton: { backgroundColor: colors.disabled },
  pressed: { opacity: motion.pressOpacity },
});
