import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Alert, Linking, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { Image } from 'expo-image';
import * as ImagePicker from 'expo-image-picker';
import { SafeAreaView } from 'react-native-safe-area-context';

import { AppIcon } from '@/components/app-icon';
import { CheckFlowHeader, CheckIntro } from '@/components/ui/check-screen-header';
import { useDailyCheck } from '@/context/daily-check-context';
import { wellnessApi } from '@/services/wellness-api';
import { colors } from '@/theme/tokens';
import { toLocalDateId } from '@/utils/date';
import { BODY_ZONE_LABELS } from './SelectableBodyMap';
import { styles } from './activity-skin-check.styles';

const SIT_HOURS = ['<1h', '1–3h', '3–5h', '5–8h', '8h+'] as const;
const ACTIVITIES = ['가벼운 산책', '운동함', '무거운 것 듦', '야근', '음주', '스트레스 많음', '외출 안 함'] as const;
const SKIN = ['좋음', '보통', '건조', '번들거림'] as const;
const SPOTS = ['이마', '볼', '턱', '목', '등'] as const;

export default function ActivitySkinCheckScreen() {
  const router=useRouter(); const {completeStep,draft,skipStep,updateDraft}=useDailyCheck(); const[busy,setBusy]=useState(false); const[photoError,setPhotoError]=useState('');
  const canComplete=Boolean(draft.activity&&draft.skinStates[0]);
  const toggleActivity=(value:string)=>updateDraft({activities:draft.activities.includes(value)?draft.activities.filter(item=>item!==value):[...draft.activities,value]});
  const toggleSpot=(value:string)=>updateDraft({troubleSpots:draft.troubleSpots.includes(value)?draft.troubleSpots.filter(item=>item!==value):[...draft.troubleSpots,value]});
  const choosePhoto=async(source:'camera'|'library')=>{setPhotoError('');try{const permission=source==='camera'?await ImagePicker.requestCameraPermissionsAsync():await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted){Alert.alert('권한이 필요해요','기기 설정에서 사진 접근을 허용해 주세요.',[{text:'취소',style:'cancel'},{text:'설정 열기',onPress:()=>void Linking.openSettings()}]);return;}const result=source==='camera'?await ImagePicker.launchCameraAsync({mediaTypes:['images'],allowsEditing:true,quality:.75}):await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:true,quality:.75});if(!result.canceled&&result.assets[0]?.uri)updateDraft({skinPhotoUri:result.assets[0].uri});}catch{setPhotoError('사진을 불러오지 못했어요. 사진 없이 계속할 수 있어요.');}};
  const submit=async(skipped=false)=>{if((!canComplete&&!skipped)||busy)return;setBusy(true);try{await wellnessApi.saveDailyCheck({date:draft.targetDate??toLocalDateId(),autoRecords:{...draft.autoRecords,source:draft.autoSource},condition:draft.condition,conditionTags:draft.conditionTags,discomfort:{bodyParts:[...draft.bodyParts],intensity:draft.intensity,feelings:draft.discomfortFeelings,headache:draft.headache,areas:draft.bodyParts.map(id=>({id,label:BODY_ZONE_LABELS[id]??id,view:id.startsWith('back-')?'back':'front',intensity:draft.bodyAreaIntensities[id]??1,feelings:draft.bodyAreaFeelings[id]??[]}))},sleep:{satisfaction:draft.sleepSatisfaction,posture:draft.sleepPosture,pillow:draft.pillow,minutes:draft.sleepMinutes},activitySkin:skipped?{activity:null,activities:[],skinStates:[],trouble:false,troubleSpots:[],memo:'',photoUri:null}:{activity:draft.activity,activities:draft.activities,skinStates:draft.skinStates,trouble:draft.skinTrouble,troubleSpots:draft.troubleSpots,memo:draft.memo,photoUri:draft.skinPhotoUri},skippedSteps:skipped&&!draft.skippedSteps.includes('activitySkin')?[...draft.skippedSteps,'activitySkin']:draft.skippedSteps});if(skipped)skipStep('activitySkin');else completeStep('activitySkin');router.replace('/check/review');}catch{Alert.alert('저장하지 못했어요','네트워크 상태를 확인하고 다시 시도해 주세요.');}finally{setBusy(false)}};
  return <SafeAreaView edges={['top','bottom']} style={styles.screen}><CheckFlowHeader backLabel="수면 기록으로 돌아가기" fallbackHref="/check/sleep" step={5}/><ScrollView automaticallyAdjustKeyboardInsets contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}><CheckIntro description="작은 변화도 쌓이면 내 몸의 패턴을 찾는 데 도움이 돼요." inset={false} step={5} title="오늘 하루는\n어땠나요?"/>
    <Text style={styles.sectionTitle}>오래 앉아 있던 시간</Text><View style={styles.segment}>{SIT_HOURS.map(item=><Pressable accessibilityRole="radio" accessibilityState={{checked:draft.activity===item}} key={item} onPress={()=>updateDraft({activity:item})} style={[styles.segmentItem,draft.activity===item&&styles.segmentItemOn]}><Text style={[styles.segmentText,draft.activity===item&&styles.segmentTextOn]}>{item}</Text></Pressable>)}</View>
    <Text style={styles.sectionTitle}>오늘 한 활동 <Text style={styles.optional}>(여러 개 선택)</Text></Text><View style={styles.chips}>{ACTIVITIES.map(item=><Pressable accessibilityRole="checkbox" accessibilityState={{checked:draft.activities.includes(item)}} key={item} onPress={()=>toggleActivity(item)} style={[styles.chip,draft.activities.includes(item)&&styles.chipOn]}><Text style={[styles.chipText,draft.activities.includes(item)&&styles.chipTextOn]}>{item}</Text></Pressable>)}</View>
    <Text style={styles.sectionTitle}>피부 상태</Text><View style={styles.segment}>{SKIN.map(item=><Pressable accessibilityRole="radio" accessibilityState={{checked:draft.skinStates[0]===item}} key={item} onPress={()=>updateDraft({skinStates:[item]})} style={[styles.segmentItem,draft.skinStates[0]===item&&styles.segmentItemOn]}><Text style={[styles.segmentText,draft.skinStates[0]===item&&styles.segmentTextOn]}>{item}</Text></Pressable>)}</View>
    <Pressable accessibilityRole="switch" accessibilityState={{checked:draft.skinTrouble}} onPress={()=>updateDraft({skinTrouble:!draft.skinTrouble,troubleSpots:draft.skinTrouble?[]:draft.troubleSpots})} style={styles.trouble}><View><Text style={styles.troubleTitle}>트러블이 있었나요?</Text><Text style={styles.troubleBody}>부위와 사진은 선택해서 남길 수 있어요.</Text></View><View style={[styles.toggle,draft.skinTrouble&&styles.toggleOn]}><View style={[styles.knob,draft.skinTrouble&&styles.knobOn]}/></View></Pressable>
    {draft.skinTrouble?<View style={styles.troubleBodyBlock}><Text style={styles.subTitle}>트러블 부위</Text><View style={styles.chips}>{SPOTS.map(item=><Pressable accessibilityRole="checkbox" accessibilityState={{checked:draft.troubleSpots.includes(item)}} key={item} onPress={()=>toggleSpot(item)} style={[styles.chip,draft.troubleSpots.includes(item)&&styles.chipDanger]}><Text style={[styles.chipText,draft.troubleSpots.includes(item)&&styles.chipDangerText]}>{item}</Text></Pressable>)}</View><Text style={styles.subTitle}>사진 추가 <Text style={styles.optional}>(선택)</Text></Text>{draft.skinPhotoUri?<View style={styles.photoPreview}><Image contentFit="cover" source={{uri:draft.skinPhotoUri}} style={styles.photo}/><Pressable accessibilityLabel="사진 삭제" onPress={()=>updateDraft({skinPhotoUri:null})} style={styles.removePhoto}><AppIcon color={colors.white} name="close" size={16}/></Pressable></View>:<View style={styles.photoActions}><Pressable accessibilityLabel="촬영하기" onPress={()=>void choosePhoto('camera')} style={styles.photoAction}><AppIcon color={colors.primaryPressed} name="camera" size={22}/></Pressable><Pressable accessibilityLabel="앨범에서 선택" onPress={()=>void choosePhoto('library')} style={styles.photoAction}><AppIcon color={colors.primaryPressed} name="image" size={22}/></Pressable></View>}{photoError?<Text style={styles.error}>{photoError}</Text>:null}</View>:null}
    <Text style={styles.sectionTitle}>메모 <Text style={styles.optional}>(선택)</Text></Text><TextInput maxLength={150} multiline onChangeText={memo=>updateDraft({memo})} placeholder="평소와 달랐던 점을 적어주세요." placeholderTextColor={colors.textMuted} style={styles.memo} value={draft.memo}/><Text style={styles.count}>{draft.memo.length} / 150</Text>
  </ScrollView><View style={styles.footer}><Pressable accessibilityRole="button" accessibilityState={{disabled:!canComplete,busy}} disabled={!canComplete||busy} onPress={()=>void submit()} style={[styles.completeButton,(!canComplete||busy)&&styles.disabledButton]}><Text style={[styles.completeText,!canComplete&&styles.disabledText]}>{busy?'저장 중…':'검토하기'}</Text></Pressable></View></SafeAreaView>;
}
