import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#FFFFFF' }, progressTrack: { height: 3, backgroundColor: '#E9EAE5' }, progressValue: { width: '100%', height: '100%', backgroundColor: '#285C4D' }, content: { width: '100%', maxWidth: 560, alignSelf: 'center', paddingHorizontal: 24, paddingBottom: 28 },
  topBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingTop: 14 }, backButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', marginLeft: -8 }, backIcon: { color: '#18201C', fontSize: 36, lineHeight: 38 }, skipButton: { minHeight: 44, justifyContent: 'center' }, skipText: { color: '#6E776F', fontSize: 14, fontWeight: '700' }, pressed: { opacity: 0.62 },
  step: { marginTop: 14, color: '#285C4D', fontSize: 13, fontWeight: '700' }, title: { marginTop: 10, color: '#18201C', fontSize: 26, lineHeight: 36, fontWeight: '800', letterSpacing: -0.9 }, description: { marginTop: 10, color: '#46514A', fontSize: 14, lineHeight: 22 }, sectionTitle: { marginTop: 26, marginBottom: 12, color: '#18201C', fontSize: 15, fontWeight: '800' }, optional: { color: '#6E776F', fontSize: 13, fontWeight: '600' },
  cardList: { borderBottomWidth: 1, borderBottomColor: '#ECEEEC' }, card: { minHeight: 70, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 2, paddingVertical: 12, borderTopWidth: 1, borderTopColor: '#ECEEEC' }, selectedCard: { borderTopColor: '#176B52', backgroundColor: '#EFF6F3' }, radio: { width: 21, height: 21, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, borderColor: '#C4C8CF', borderRadius: 11 }, selectedRadio: { borderColor: '#176B52', backgroundColor: '#176B52' }, radioDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#FFFFFF' }, cardCopy: { flex: 1, marginLeft: 13 }, cardTitle: { color: '#171A18', fontSize: 14, fontWeight: '700' }, cardDetail: { marginTop: 3, color: '#7A817D', fontSize: 12, lineHeight: 17 },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 }, chip: { minHeight: 42, justifyContent: 'center', paddingHorizontal: 16, borderWidth: 1, borderColor: '#D8DCD6', borderRadius: 21 }, selectedChip: { borderColor: '#285C4D', backgroundColor: '#E6EEE9' }, chipText: { color: '#46514A', fontSize: 13, fontWeight: '700' }, selectedChipText: { color: '#285C4D' },
  photoHelp: { marginTop: -6, marginBottom: 12, color: '#6E776F', fontSize: 12, lineHeight: 18 }, photoActions: { flexDirection: 'row', gap: 10 }, photoAction: { flex: 1, minHeight: 82, alignItems: 'center', justifyContent: 'center', gap: 7, borderWidth: 1, borderColor: '#D8DCD6', borderRadius: 14, backgroundColor: '#FFFFFF' }, photoActionText: { color: '#46514A', fontSize: 13, fontWeight: '800' }, photoPreview: { position: 'relative', height: 180, overflow: 'hidden', borderRadius: 16, backgroundColor: '#E9EAE5' }, photo: { width: '100%', height: '100%' }, removePhoto: { position: 'absolute', top: 10, right: 10, width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 22, backgroundColor: 'rgba(23,25,28,.72)' },
  memo: { minHeight: 100, paddingHorizontal: 15, paddingVertical: 13, borderWidth: 1, borderColor: '#D8DCD6', borderRadius: 12, color: '#18201C', fontSize: 14, lineHeight: 21 }, count: { marginTop: 6, color: '#858D86', fontSize: 11, textAlign: 'right' },
  footer: { paddingHorizontal: 24, paddingTop: 10, paddingBottom: 20, backgroundColor: '#FFFFFF' }, completeButton: { height: 56, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: '#285C4D' }, disabledButton: { backgroundColor: '#D8DCD6' }, completeText: { color: '#FFFFFF', fontSize: 16.5, fontWeight: '800' }, disabledText: { color: '#858D86' },
});
