import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#FFFFFF' }, progressTrack: { height: 3, backgroundColor: '#EEF0F3' }, progressValue: { width: '100%', height: '100%', backgroundColor: '#1257E0' }, content: { paddingHorizontal: 24, paddingBottom: 28 },
  topBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingTop: 14 }, backButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', marginLeft: -8 }, backIcon: { color: '#17191C', fontSize: 36, lineHeight: 38 }, skipButton: { minHeight: 44, justifyContent: 'center' }, skipText: { color: '#8B919B', fontSize: 14, fontWeight: '700' }, pressed: { opacity: 0.55 },
  step: { marginTop: 14, color: '#1257E0', fontSize: 13, fontWeight: '700' }, title: { marginTop: 10, color: '#17191C', fontSize: 26, lineHeight: 36, fontWeight: '800', letterSpacing: -0.9 }, description: { marginTop: 10, color: '#4A4F58', fontSize: 14, lineHeight: 22 }, sectionTitle: { marginTop: 26, marginBottom: 12, color: '#17191C', fontSize: 15, fontWeight: '800' }, optional: { color: '#8B919B', fontSize: 13, fontWeight: '600' },
  cardList: { gap: 9 }, card: { minHeight: 70, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 12, borderWidth: 1, borderColor: '#E3E6EA', borderRadius: 14 }, selectedCard: { borderColor: '#1257E0', backgroundColor: '#F2F6FF' }, radio: { width: 21, height: 21, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, borderColor: '#C4C8CF', borderRadius: 11 }, selectedRadio: { borderColor: '#1257E0', backgroundColor: '#1257E0' }, radioDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#FFFFFF' }, cardCopy: { flex: 1, marginLeft: 13 }, cardTitle: { color: '#17191C', fontSize: 14, fontWeight: '800' }, cardDetail: { marginTop: 3, color: '#8B919B', fontSize: 12, lineHeight: 17 },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 }, chip: { minHeight: 42, justifyContent: 'center', paddingHorizontal: 16, borderWidth: 1, borderColor: '#E3E6EA', borderRadius: 21 }, selectedChip: { borderColor: '#1257E0', backgroundColor: '#F2F6FF' }, chipText: { color: '#4A4F58', fontSize: 13, fontWeight: '700' }, selectedChipText: { color: '#1257E0' },
  memo: { minHeight: 100, paddingHorizontal: 15, paddingVertical: 13, borderWidth: 1, borderColor: '#E3E6EA', borderRadius: 12, color: '#17191C', fontSize: 14, lineHeight: 21 }, count: { marginTop: 6, color: '#A4A9B2', fontSize: 11, textAlign: 'right' },
  footer: { paddingHorizontal: 24, paddingTop: 10, paddingBottom: 20, backgroundColor: '#FFFFFF' }, completeButton: { height: 56, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: '#17191C' }, disabledButton: { backgroundColor: '#E3E6EA' }, completeText: { color: '#FFFFFF', fontSize: 16.5, fontWeight: '800' }, disabledText: { color: '#A4A9B2' },
});
