import { StyleSheet } from 'react-native';
import { colors, layout, motion, radius, spacing, typography } from '@/theme/tokens';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.canvas },
  scrollContent: { flexGrow: 1, width: '100%', maxWidth: layout.maxContentWidth, alignSelf: 'center', paddingBottom: 128 },
  closeButton: { width: layout.minTouch, height: layout.minTouch, alignItems: 'center', justifyContent: 'center' },
  loadingState: { minHeight: 240, alignItems: 'center', justifyContent: 'center' },
  loadingText: { marginTop: spacing.sm, color: colors.textMuted, ...typography.caption },
  errorState: { marginHorizontal: layout.horizontalPadding, marginTop: spacing.xxl, alignItems: 'flex-start', paddingVertical: spacing.xl, borderTopWidth: StyleSheet.hairlineWidth, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: colors.divider },
  errorTitle: { marginTop: spacing.md, color: colors.text, ...typography.sectionTitle },
  errorDescription: { marginTop: spacing.xs, color: colors.textSecondary, ...typography.body },
  errorActions: { width: '100%', flexDirection: 'row', gap: spacing.xs, marginTop: spacing.lg },
  errorPrimary: { flex: 1, minHeight: 50, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colors.primary },
  errorPrimaryText: { color: colors.white, ...typography.label },
  errorSecondary: { flex: 1, minHeight: 50, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: radius.md },
  errorSecondaryText: { color: colors.text, ...typography.label },
  retryLink: { minHeight: layout.minTouch, justifyContent: 'center', marginTop: spacing.xs },
  retryText: { color: colors.brand, ...typography.caption, fontWeight:'700' },
  recordCard: { marginHorizontal: layout.horizontalPadding, marginTop: spacing.xxxl,borderTopWidth:0,borderBottomWidth:1,borderColor:colors.data },
  recordRow: { minHeight: 68, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.border },
  lastRecordRow: {},
  recordLabel: { color: colors.textSecondary, ...typography.label },
  recordValue: { color: colors.text, fontSize: 18, fontWeight:'700' },
  recordInput: { minWidth: 120, minHeight: 44, paddingHorizontal: spacing.sm,borderWidth:1,borderColor:colors.border,borderRadius:radius.sm,backgroundColor:colors.surface, color: colors.text, fontSize: 16, fontWeight:'700', textAlign: 'right' },
  sourceRow: { minHeight: 56, flexDirection: 'row', alignItems: 'center', gap: spacing.xs, marginHorizontal: layout.horizontalPadding },
  sourceText: { color: colors.textMuted, ...typography.caption },
  footer: { position: 'absolute', right: 0, bottom: 0, left: 0, flexDirection: 'row', gap: spacing.xs, paddingHorizontal: layout.horizontalPadding, paddingTop: spacing.sm, paddingBottom: spacing.lg, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.divider, backgroundColor: colors.surface },
  editButton: { flex: 1, minHeight: layout.ctaHeight, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: radius.md },
  editText: { color: colors.text, ...typography.label },
  confirmButton: { flex: 2, minHeight: layout.ctaHeight, alignItems: 'center', justifyContent: 'center', borderRadius: radius.sm, backgroundColor: colors.primary },
  confirmText: { color: colors.white, fontSize: 16, fontWeight:'700' },
  pressed: { opacity: motion.pressOpacity },
});
