import { StyleSheet } from 'react-native';
import { colors, layout, motion, radius, spacing, typography } from '@/theme/tokens';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.surface },
  scrollContent: { flexGrow: 1, width: '100%', maxWidth: layout.maxContentWidth, alignSelf: 'center', paddingBottom: 128 },
  closeButton: { width: layout.minTouch, height: layout.minTouch, alignItems: 'center', justifyContent: 'center' },
  loadingState: { minHeight: 240, alignItems: 'center', justifyContent: 'center' },
  loadingText: { marginTop: spacing.sm, color: colors.textMuted, ...typography.caption },
  errorState: { marginHorizontal: layout.horizontalPadding, marginTop: spacing.xxl, alignItems: 'flex-start', paddingVertical: spacing.xl, borderTopWidth: StyleSheet.hairlineWidth, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: colors.divider },
  errorTitle: { marginTop: spacing.md, color: colors.text, ...typography.sectionTitle },
  errorDescription: { marginTop: spacing.xs, color: colors.textSecondary, ...typography.body },
  errorActions: { width: '100%', flexDirection: 'row', gap: spacing.xs, marginTop: spacing.lg },
  errorPrimary: { flex: 1, minHeight: 50, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colors.primary },
  errorPrimaryText: { color: colors.white, ...typography.label },
  errorSecondary: { flex: 1, minHeight: 50, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: radius.md },
  errorSecondaryText: { color: colors.text, ...typography.label },
  retryLink: { minHeight: layout.minTouch, justifyContent: 'center', marginTop: spacing.xs },
  retryText: { color: colors.brand, ...typography.caption, fontWeight:'700' },
  statusRow: { flexDirection: 'row', gap: 6, marginHorizontal: layout.horizontalPadding, marginTop: spacing.lg },
  statusChip: { flex: 1, minHeight: 38, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 6, borderWidth: 1, borderColor: colors.border, borderRadius: radius.pill },
  statusChipActive: { borderWidth: 2, borderColor: colors.text, backgroundColor: colors.text },
  statusText: { color: colors.textMuted, fontSize: 10.5, lineHeight: 15, fontWeight: '700' },
  statusTextActive: { color: colors.white },
  recordList: { marginHorizontal: layout.horizontalPadding, marginTop: spacing.lg, gap: spacing.sm },
  recordRow: { minHeight: 78, flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingHorizontal: spacing.lg, paddingVertical: 13, borderWidth: 1, borderColor: colors.border, borderRadius: 18, backgroundColor: colors.surface },
  lastRecordRow: {},
  recordIcon: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 13, backgroundColor: colors.surfaceSubtle },
  recordCopy: { flex: 1, minWidth: 0 },
  recordLabel: { color: colors.textSecondary, ...typography.label },
  recordSource: { marginTop: 2, color: colors.textMuted, fontSize: 11, lineHeight: 16, fontWeight: '600' },
  recordValue: { maxWidth: '34%', color: colors.text, textAlign: 'right', fontSize: 18, fontWeight:'700', fontVariant: ['tabular-nums'] },
  recordInput: { width: 120, maxWidth: '42%', minWidth: 0, minHeight: 44, flexShrink: 1, paddingHorizontal: spacing.sm,borderWidth:1,borderColor:colors.border,borderRadius:radius.sm,backgroundColor:colors.surface, color: colors.text, fontSize: 16, fontWeight:'700', textAlign: 'right' },
  guide: { marginHorizontal: layout.horizontalPadding, marginTop: spacing.md, padding: spacing.md, borderRadius: radius.md, color: colors.textMuted, backgroundColor: colors.surfaceSubtle, ...typography.caption },
  footer: { position: 'absolute', right: 0, bottom: 0, left: 0, flexDirection: 'row', gap: spacing.xs, paddingHorizontal: layout.horizontalPadding, paddingTop: spacing.sm, paddingBottom: spacing.lg, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.divider, backgroundColor: colors.surface },
  editButton: { flex: 1, minHeight: layout.ctaHeight, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: radius.pill },
  editText: { color: colors.text, ...typography.label },
  confirmButton: { flex: 1, minHeight: layout.ctaHeight, alignItems: 'center', justifyContent: 'center', borderRadius: radius.pill, backgroundColor: colors.primary },
  confirmText: { color: colors.white, fontSize: 16, fontWeight:'700' },
  pressed: { opacity: motion.pressOpacity },
});
