import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#FFFFFF' },
  progressTrack: { height: 3, backgroundColor: '#E9EAE5' },
  progressValue: { width: '20%', height: '100%', backgroundColor: '#285C4D' },
  scrollContent: { flexGrow: 1, paddingBottom: 24 },
  topBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 24, paddingTop: 14 },
  closeButton: { width: 32, height: 32, alignItems: 'center', justifyContent: 'center' },
  closeIcon: { color: '#18201C', fontSize: 30, fontWeight: '300', lineHeight: 32 },
  skipButton: { minHeight: 44, justifyContent: 'center' },
  skipText: { color: '#6E776F', fontSize: 14, fontWeight: '700' },
  header: { paddingHorizontal: 24, paddingTop: 20 },
  step: { color: '#285C4D', fontSize: 13, fontWeight: '700' },
  title: { marginTop: 10, color: '#18201C', fontSize: 26, fontWeight: '800', letterSpacing: -0.9, lineHeight: 36 },
  description: { marginTop: 10, color: '#46514A', fontSize: 14, lineHeight: 22 },
  recordCard: { marginHorizontal: 24, marginTop: 24, borderTopWidth: 1, borderBottomWidth: 1, borderColor: '#ECEEEC' },
  recordRow: { minHeight: 58, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: '#E9EAE5' },
  lastRecordRow: { borderBottomWidth: 0 },
  recordLabel: { color: '#46514A', fontSize: 14, fontWeight: '600' },
  recordValue: { color: '#18201C', fontSize: 18, fontWeight: '800' },
  recordInput: { minWidth: 120, minHeight: 44, paddingHorizontal: 10, borderWidth: 1, borderColor: '#285C4D', borderRadius: 8, color: '#18201C', fontSize: 16, fontWeight: '700', textAlign: 'right' },
  sourceRow: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 24, paddingTop: 12 },
  sourceIcon: { color: '#285C4D', fontSize: 13 },
  sourceText: { color: '#6E776F', fontSize: 12, fontWeight: '600' },
  footer: { flexDirection: 'row', gap: 9, paddingHorizontal: 24, paddingTop: 10, paddingBottom: 20, backgroundColor: '#FFFFFF' },
  editButton: { flex: 1, height: 56, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: '#FFFFFF' },
  editText: { color: '#18201C', fontSize: 16, fontWeight: '700' },
  confirmButton: { flex: 1.4, height: 56, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: '#285C4D' },
  confirmText: { color: '#FFFFFF', fontSize: 16.5, fontWeight: '800' },
  pressed: { opacity: 0.62 },
});
