import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#FFFFFF' },
  progressTrack: { height: 3, backgroundColor: '#EEF0F3' },
  progressValue: { width: '40%', height: '100%', backgroundColor: '#1257E0' },
  scrollContent: { paddingBottom: 24 },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 14,
  },
  backButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', marginLeft: -8 },
  backIcon: { color: '#17191C', fontSize: 36, fontWeight: '300', lineHeight: 38 },
  skipButton: { minWidth: 60, minHeight: 44, alignItems: 'flex-end', justifyContent: 'center' },
  skipText: { color: '#8B919B', fontSize: 14, fontWeight: '700' },
  header: { paddingHorizontal: 24, paddingTop: 14 },
  step: { color: '#1257E0', fontSize: 13, fontWeight: '700' },
  title: { marginTop: 10, color: '#17191C', fontSize: 26, fontWeight: '800', letterSpacing: -0.9, lineHeight: 36 },
  description: { marginTop: 10, color: '#4A4F58', fontSize: 14, lineHeight: 22 },
  conditionList: { gap: 10, paddingHorizontal: 24, paddingTop: 24 },
  conditionCard: {
    minHeight: 74,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#E3E6EA',
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
  },
  selectedConditionCard: { borderWidth: 2, borderColor: '#1257E0', paddingHorizontal: 17, paddingVertical: 13, backgroundColor: '#F5F8FF' },
  radio: { width: 22, height: 22, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, borderColor: '#C4C8CF', borderRadius: 11 },
  selectedRadio: { borderColor: '#1257E0', backgroundColor: '#1257E0' },
  radioDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#FFFFFF' },
  conditionCopy: { flex: 1, marginLeft: 14 },
  conditionTitle: { color: '#17191C', fontSize: 15, fontWeight: '800', lineHeight: 21 },
  conditionDescription: { marginTop: 2, color: '#8B919B', fontSize: 12.5, fontWeight: '500', lineHeight: 18 },
  recentSection: { paddingHorizontal: 24, paddingTop: 24 },
  recentTitle: { color: '#4A4F58', fontSize: 13, fontWeight: '700' },
  tags: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 10 },
  tag: { minHeight: 36, justifyContent: 'center', paddingHorizontal: 13, borderRadius: 18, backgroundColor: '#F4F5F7' },
  selectedTag: { backgroundColor: '#E8F0FF' },
  tagText: { color: '#4A4F58', fontSize: 13, fontWeight: '600' },
  selectedTagText: { color: '#1257E0' },
  footer: { paddingHorizontal: 24, paddingTop: 10, paddingBottom: 20, backgroundColor: '#FFFFFF' },
  nextButton: { height: 56, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: '#17191C' },
  disabledNextButton: { backgroundColor: '#E3E6EA' },
  nextButtonText: { color: '#FFFFFF', fontSize: 16.5, fontWeight: '800' },
  disabledNextButtonText: { color: '#A4A9B2' },
  pressed: { opacity: 0.55 },
});
