import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#FFFFFF' },
  progressTrack: { height: 3, backgroundColor: '#E9EAE5' },
  progressValue: { width: '40%', height: '100%', backgroundColor: '#285C4D' },
  scrollContent: { paddingBottom: 24 },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 14,
  },
  backButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', marginLeft: -8 },
  backIcon: { color: '#18201C', fontSize: 36, fontWeight: '300', lineHeight: 38 },
  skipButton: { minWidth: 60, minHeight: 44, alignItems: 'flex-end', justifyContent: 'center' },
  skipText: { color: '#6E776F', fontSize: 14, fontWeight: '700' },
  header: { paddingHorizontal: 24, paddingTop: 14 },
  step: { color: '#285C4D', fontSize: 13, fontWeight: '700' },
  title: { marginTop: 10, color: '#18201C', fontSize: 26, fontWeight: '800', letterSpacing: -0.9, lineHeight: 36 },
  description: { marginTop: 10, color: '#46514A', fontSize: 14, lineHeight: 22 },
  conditionList: { paddingHorizontal: 24, paddingTop: 24, borderBottomWidth: 1, borderBottomColor: '#ECEEEC' },
  conditionCard: {
    minHeight: 74,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 2,
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: '#ECEEEC',
    backgroundColor: '#FFFFFF',
  },
  selectedConditionCard: { borderTopColor: '#176B52', backgroundColor: '#EFF6F3' },
  radio: { width: 22, height: 22, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, borderColor: '#C4C8CF', borderRadius: 11 },
  selectedRadio: { borderColor: '#285C4D', backgroundColor: '#285C4D' },
  radioDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#FFFFFF' },
  conditionCopy: { flex: 1, marginLeft: 14 },
  conditionTitle: { color: '#18201C', fontSize: 15, fontWeight: '800', lineHeight: 21 },
  conditionDescription: { marginTop: 2, color: '#6E776F', fontSize: 12.5, fontWeight: '500', lineHeight: 18 },
  recentSection: { paddingHorizontal: 24, paddingTop: 24 },
  recentTitle: { color: '#46514A', fontSize: 13, fontWeight: '700' },
  tags: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 10 },
  tag: { minHeight: 36, justifyContent: 'center', paddingHorizontal: 13, borderRadius: 18, backgroundColor: '#FFFFFF' },
  selectedTag: { backgroundColor: '#E6EEE9' },
  tagText: { color: '#46514A', fontSize: 13, fontWeight: '600' },
  selectedTagText: { color: '#285C4D' },
  footer: { paddingHorizontal: 24, paddingTop: 10, paddingBottom: 20, backgroundColor: '#FFFFFF' },
  nextButton: { height: 56, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: '#285C4D' },
  disabledNextButton: { backgroundColor: '#D8DCD6' },
  nextButtonText: { color: '#FFFFFF', fontSize: 16.5, fontWeight: '800' },
  disabledNextButtonText: { color: '#858D86' },
  pressed: { opacity: 0.62 },
});
