import { StyleSheet } from 'react-native';
import { colors, layout, motion, radius, spacing, typography } from '@/theme/tokens';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.surface },
  content: { width: '100%', maxWidth: layout.maxContentWidth, alignSelf: 'center', paddingHorizontal: layout.horizontalPadding, paddingBottom: 132 },
  topBar: { minHeight: 56, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginHorizontal: -spacing.sm },
  backButton: { width: layout.minTouch, height: layout.minTouch },
  skipButton: { minHeight: layout.minTouch, justifyContent: 'center', paddingHorizontal: spacing.sm },
  skipText: { color: colors.textSecondary, ...typography.label },
  sectionTitle: { marginTop: spacing.xxl, color: colors.text, ...typography.sectionTitle },
  sectionDescription: { marginTop: spacing.xs, color: colors.textMuted, ...typography.caption },
  intensityBlock: { marginTop: spacing.md,borderTopWidth:0,borderBottomWidth:1,borderColor:colors.body,paddingVertical:spacing.md },
  areaHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  areaCard: { marginTop: spacing.lg, paddingTop: spacing.lg, borderTopWidth: 1, borderTopColor: colors.divider },
  areaTitle: { color: colors.text, ...typography.sectionTitle },
  removeText: { color: colors.textMuted, ...typography.caption, fontWeight: '700' },
  areaValue: { color: colors.brand, ...typography.caption, fontWeight:'700' },
  scaleRow: { flexDirection: 'row',marginTop: spacing.md, borderTopWidth: 1,borderBottomWidth:1, borderColor: colors.text },
  scaleButton: { flex: 1, minHeight: 52, alignItems: 'center', justifyContent: 'center', borderRightWidth: 1, borderRightColor: colors.divider, backgroundColor: colors.surface },
  selectedScaleButton: { backgroundColor: colors.body },
  scaleText: { color: colors.text, fontSize: 16, fontWeight:'700', fontVariant: ['tabular-nums'] },
  selectedScaleText: { color: colors.white },
  scaleLabels: { flexDirection: 'row', justifyContent: 'space-between', marginTop: spacing.xs },
  scaleLabel: { color: colors.textMuted, fontSize: 11, lineHeight: 16 },
  feelTitle: { marginTop: spacing.lg, color: colors.textSecondary, ...typography.caption, fontWeight: '700' },
  intensityHelp: { marginTop: spacing.sm, color: colors.textMuted, ...typography.caption },
  optional: { color: colors.textMuted, ...typography.caption },
  chipGroup: { flexDirection: 'row', flexWrap: 'wrap', gap:spacing.xs, marginTop: spacing.sm },
  chip: { minHeight:44,justifyContent:'center',paddingHorizontal:spacing.sm,borderBottomWidth:1,borderColor:colors.border,backgroundColor:colors.surface },
  selectedChip: { borderBottomWidth:3,borderColor:colors.body },
  chipText: { color: colors.textSecondary, ...typography.caption, fontWeight: '700' },
  selectedChipText: { color: colors.danger },
  selectedPartChip:{minHeight:44,flexDirection:'row',alignItems:'center',gap:spacing.xs,paddingHorizontal:spacing.md,borderRadius:radius.pill,backgroundColor:colors.bodySoft},selectedPartText:{color:colors.danger,...typography.caption,fontWeight:'700'},remove:{color:colors.danger,fontSize:18,lineHeight:20,fontWeight:'600'},
  headache: { minHeight: 72, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: spacing.xxl, paddingVertical: spacing.md, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.divider },
  headacheTitle: { color: colors.text, ...typography.label },
  headacheDescription: { marginTop: 2, color: colors.textMuted, ...typography.caption },
  toggle: { width: 48, height: 28, justifyContent: 'center', padding: 3, borderRadius: radius.pill, backgroundColor: colors.surfaceStrong },
  toggleOn: { backgroundColor: colors.primary },
  knob: { width: 22, height: 22, borderRadius: radius.pill, backgroundColor: colors.white },
  knobOn: { alignSelf: 'flex-end' },
  footer: { position: 'absolute', right: 0, bottom: 0, left: 0, paddingHorizontal: layout.horizontalPadding, paddingTop: spacing.sm, paddingBottom: spacing.lg, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.divider, backgroundColor: colors.surface },
  nextButton: { minHeight: layout.ctaHeight, alignItems: 'center', justifyContent: 'center', borderRadius: radius.pill, backgroundColor: colors.primary },
  disabledButton: { backgroundColor: colors.disabled },
  nextText: { color: colors.primaryText, fontSize: 16, fontWeight:'700' },
  disabledText: { color: colors.disabledText },
  pressed: { opacity: motion.pressOpacity },
});
