import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#FFFFFF' }, progressTrack: { height: 3, backgroundColor: '#E9EAE5' }, progressValue: { width: '80%', height: '100%', backgroundColor: '#285C4D' },
  content: { width: '100%', maxWidth: 560, alignSelf: 'center', paddingHorizontal: 24, paddingBottom: 28 }, topBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingTop: 14 }, backButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', marginLeft: -8 }, backIcon: { color: '#18201C', fontSize: 36, lineHeight: 38 }, skipButton: { minHeight: 44, justifyContent: 'center' }, skipText: { color: '#6E776F', fontSize: 14, fontWeight: '700' }, pressed: { opacity: 0.62 },
  step: { marginTop: 14, color: '#285C4D', fontSize: 13, fontWeight: '700' }, title: { marginTop: 10, color: '#18201C', fontSize: 26, lineHeight: 36, fontWeight: '800', letterSpacing: -0.9 }, description: { marginTop: 10, color: '#46514A', fontSize: 14, lineHeight: 22 }, sectionTitle: { marginTop: 26, marginBottom: 12, color: '#18201C', fontSize: 15, fontWeight: '800' }, optional: { color: '#6E776F', fontSize: 13, fontWeight: '600' },
  sectionDescription: { marginTop: -6, marginBottom: 12, color: '#7A817D', fontSize: 13, lineHeight: 20 }, intensityBlock: { marginBottom: 12, paddingVertical: 16, borderTopWidth: 1, borderBottomWidth: 1, borderColor: '#ECEEEC' }, areaHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 }, areaTitle: { color: '#171A18', fontSize: 15, fontWeight: '700' }, areaValue: { color: '#176B52', fontSize: 13, fontWeight: '700' }, intensityHelp: { marginTop: 9, color: '#4E5551', fontSize: 12, textAlign: 'center' },
  chipGroup: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 }, chip: { minWidth: 72, minHeight: 44, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 17, borderWidth: 1, borderColor: '#D8DCD6', borderRadius: 22 }, selectedChip: { borderColor: '#285C4D', backgroundColor: '#E6EEE9' }, chipText: { color: '#46514A', fontSize: 14, fontWeight: '700' }, selectedChipText: { color: '#285C4D' },
  scaleRow: { flexDirection: 'row', justifyContent: 'space-between' }, scaleButton: { width: 52, height: 52, alignItems: 'center', justifyContent: 'center', borderRadius: 26, backgroundColor: '#FFFFFF' }, selectedScaleButton: { backgroundColor: '#285C4D' }, scaleText: { color: '#46514A', fontSize: 16, fontWeight: '800' }, selectedScaleText: { color: '#FFFFFF' }, scaleLabels: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8 }, scaleLabel: { color: '#6E776F', fontSize: 11 },
  footer: { paddingHorizontal: 24, paddingTop: 10, paddingBottom: 20, backgroundColor: '#FFFFFF' }, nextButton: { height: 56, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: '#285C4D' }, disabledButton: { backgroundColor: '#D8DCD6' }, nextText: { color: '#FFFFFF', fontSize: 16.5, fontWeight: '800' }, disabledText: { color: '#858D86' },
});
