import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#FFFFFF' }, progressTrack: { height: 3, backgroundColor: '#EEF0F3' }, progressValue: { width: '80%', height: '100%', backgroundColor: '#1257E0' },
  content: { paddingHorizontal: 24, paddingBottom: 28 }, topBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingTop: 14 }, backButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', marginLeft: -8 }, backIcon: { color: '#17191C', fontSize: 36, lineHeight: 38 }, skipButton: { minHeight: 44, justifyContent: 'center' }, skipText: { color: '#8B919B', fontSize: 14, fontWeight: '700' }, pressed: { opacity: 0.55 },
  step: { marginTop: 14, color: '#1257E0', fontSize: 13, fontWeight: '700' }, title: { marginTop: 10, color: '#17191C', fontSize: 26, lineHeight: 36, fontWeight: '800', letterSpacing: -0.9 }, description: { marginTop: 10, color: '#4A4F58', fontSize: 14, lineHeight: 22 }, sectionTitle: { marginTop: 26, marginBottom: 12, color: '#17191C', fontSize: 15, fontWeight: '800' }, optional: { color: '#8B919B', fontSize: 13, fontWeight: '600' },
  sectionDescription: { marginTop: -6, marginBottom: 12, color: '#687180', fontSize: 13, lineHeight: 20 }, intensityBlock: { marginBottom: 12, padding: 16, borderWidth: 1, borderColor: '#DDE2E8', borderRadius: 16, backgroundColor: '#F7F8FA' }, areaHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 }, areaTitle: { color: '#17191C', fontSize: 15, fontWeight: '800' }, areaValue: { color: '#1257E0', fontSize: 13, fontWeight: '800' }, intensityHelp: { marginTop: 9, color: '#465163', fontSize: 12, textAlign: 'center' },
  chipGroup: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 }, chip: { minWidth: 72, minHeight: 44, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 17, borderWidth: 1, borderColor: '#E3E6EA', borderRadius: 22 }, selectedChip: { borderColor: '#1257E0', backgroundColor: '#F2F6FF' }, chipText: { color: '#4A4F58', fontSize: 14, fontWeight: '700' }, selectedChipText: { color: '#1257E0' },
  scaleRow: { flexDirection: 'row', justifyContent: 'space-between' }, scaleButton: { width: 52, height: 52, alignItems: 'center', justifyContent: 'center', borderRadius: 26, backgroundColor: '#F4F5F7' }, selectedScaleButton: { backgroundColor: '#1257E0' }, scaleText: { color: '#4A4F58', fontSize: 16, fontWeight: '800' }, selectedScaleText: { color: '#FFFFFF' }, scaleLabels: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8 }, scaleLabel: { color: '#8B919B', fontSize: 11 },
  footer: { paddingHorizontal: 24, paddingTop: 10, paddingBottom: 20, backgroundColor: '#FFFFFF' }, nextButton: { height: 56, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: '#17191C' }, disabledButton: { backgroundColor: '#E3E6EA' }, nextText: { color: '#FFFFFF', fontSize: 16.5, fontWeight: '800' }, disabledText: { color: '#A4A9B2' },
});
