import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#FFFFFF' }, progressTrack: { height: 3, backgroundColor: '#EEF0F3' }, progressValue: { width: '80%', height: '100%', backgroundColor: '#1257E0' }, content: { paddingHorizontal: 24, paddingBottom: 28 },
  topBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingTop: 14 }, backButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', marginLeft: -8 }, backIcon: { color: '#17191C', fontSize: 36, lineHeight: 38 }, skipButton: { minHeight: 44, justifyContent: 'center' }, skipText: { color: '#8B919B', fontSize: 14, fontWeight: '700' }, pressed: { opacity: 0.55 },
  step: { marginTop: 14, color: '#1257E0', fontSize: 13, fontWeight: '700' }, title: { marginTop: 10, color: '#17191C', fontSize: 26, lineHeight: 36, fontWeight: '800', letterSpacing: -0.9 }, description: { marginTop: 10, color: '#4A4F58', fontSize: 14, lineHeight: 22 }, sectionTitle: { marginTop: 26, marginBottom: 12, color: '#17191C', fontSize: 15, fontWeight: '800' }, optional: { color: '#8B919B', fontSize: 13, fontWeight: '600' },
  ratingRow: { flexDirection: 'row', justifyContent: 'space-between' }, ratingButton: { width: 56, height: 68, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#E3E6EA', borderRadius: 14 }, selectedRating: { borderColor: '#1257E0', backgroundColor: '#1257E0' }, ratingFace: { fontSize: 22 }, ratingNumber: { marginTop: 4, color: '#8B919B', fontSize: 12, fontWeight: '700' }, selectedText: { color: '#FFFFFF' },
  optionList: { gap: 8 }, option: { minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, borderWidth: 1, borderColor: '#E3E6EA', borderRadius: 12 }, selectedOption: { borderColor: '#1257E0', backgroundColor: '#F2F6FF' }, optionText: { color: '#4A4F58', fontSize: 14, fontWeight: '700' }, selectedOptionText: { color: '#1257E0' }, radio: { width: 20, height: 20, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, borderColor: '#C4C8CF', borderRadius: 10 }, selectedRadio: { borderColor: '#1257E0', backgroundColor: '#1257E0' }, radioDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#FFFFFF' }, pillowRow: { flexDirection: 'row', gap: 8 }, pillow: { flex: 1, minHeight: 48, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#E3E6EA', borderRadius: 12 },
  footer: { paddingHorizontal: 24, paddingTop: 10, paddingBottom: 20, backgroundColor: '#FFFFFF' }, nextButton: { height: 56, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: '#17191C' }, disabledButton: { backgroundColor: '#E3E6EA' }, nextText: { color: '#FFFFFF', fontSize: 16.5, fontWeight: '800' }, disabledText: { color: '#A4A9B2' },
});
