import { StyleSheet } from 'react-native';
import { colors, layout, motion, radius, spacing, typography } from '@/theme/tokens';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.canvas },
  content: { width: '100%', maxWidth: layout.maxContentWidth, alignSelf: 'center', paddingHorizontal: layout.horizontalPadding, paddingBottom: 132 },
  topBar: { minHeight: 56, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginHorizontal: -spacing.sm },
  backButton: { width: layout.minTouch, height: layout.minTouch },
  skipButton: { minHeight: layout.minTouch, justifyContent: 'center', paddingHorizontal: spacing.sm },
  skipText: { color: colors.textSecondary, ...typography.label },
  sectionTitle: { marginTop: spacing.xxxl, marginBottom: spacing.md, color: colors.text, ...typography.sectionTitle },
  ratingRow: { flexDirection: 'row', borderTopWidth:1,borderBottomWidth: 1,borderColor:colors.border },
  ratingButton: { flex: 1, minHeight: 58, alignItems: 'center', justifyContent: 'center', borderRightWidth: 1, borderRightColor: colors.divider, backgroundColor: colors.surface },
  selectedRating: { backgroundColor: colors.data },
  ratingNumber: { color: colors.text, fontSize: 18, fontWeight:'700', fontVariant: ['tabular-nums'] },
  selectedText: { color: colors.white },
  ratingLabels: { flexDirection: 'row', justifyContent: 'space-between', marginTop: spacing.xs },
  ratingLabel: { color: colors.textMuted, fontSize: 11 },
  postureGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs },
  postureCard: { width: '48.7%', minHeight: 164, padding: spacing.sm, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface },
  postureCardWide: { width: '100%', minHeight: 58, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  selectedPostureCard: { borderWidth:2,borderColor: colors.data },
  postureLabelRow: { minHeight: 36, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.xs },
  optionText: { flex: 1, color: colors.textSecondary, ...typography.caption, fontWeight: '700' },
  selectedOptionText: { color: colors.text },
  radio: { width: 16, height: 16, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: radius.pill },
  selectedRadio: { borderColor: colors.data, backgroundColor: colors.data },
  radioDot: { width: 6, height: 6, borderRadius: radius.pill, backgroundColor: colors.white },
  optional: { color: colors.textMuted, ...typography.caption },
  pillowRow: { flexDirection: 'row', borderTopWidth: 1,borderBottomWidth:1, borderColor: colors.text },
  pillow: { flex: 1, minHeight: 56, alignItems: 'center', justifyContent: 'center', borderRightWidth: 1, borderRightColor: colors.divider, backgroundColor: colors.surface },
  selectedOption: { backgroundColor: colors.data },
  footer: { position: 'absolute', right: 0, bottom: 0, left: 0, paddingHorizontal: layout.horizontalPadding, paddingTop: spacing.sm, paddingBottom: spacing.lg, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.divider, backgroundColor: colors.surface },
  nextButton: { minHeight: layout.ctaHeight, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.body },
  disabledButton: { backgroundColor: colors.disabled },
  nextText: { color: colors.white, fontSize: 16, fontWeight:'700' },
  disabledText: { color: colors.disabledText },
  pressed: { opacity: motion.pressOpacity },
});
