import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#FFFFFF' }, progressTrack: { height: 3, backgroundColor: '#E9EAE5' }, progressValue: { width: '60%', height: '100%', backgroundColor: '#285C4D' }, content: { width: '100%', maxWidth: 560, alignSelf: 'center', paddingHorizontal: 24, paddingBottom: 28 },
  topBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingTop: 14 }, backButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', marginLeft: -8 }, backIcon: { color: '#18201C', fontSize: 36, lineHeight: 38 }, skipButton: { minHeight: 44, justifyContent: 'center' }, skipText: { color: '#6E776F', fontSize: 14, fontWeight: '700' }, pressed: { opacity: 0.62 },
  step: { marginTop: 14, color: '#285C4D', fontSize: 13, fontWeight: '700' }, title: { marginTop: 10, color: '#18201C', fontSize: 26, lineHeight: 36, fontWeight: '800', letterSpacing: -0.9 }, description: { marginTop: 10, color: '#46514A', fontSize: 14, lineHeight: 22 }, sectionTitle: { marginTop: 26, marginBottom: 12, color: '#18201C', fontSize: 15, fontWeight: '800' }, optional: { color: '#6E776F', fontSize: 13, fontWeight: '600' },
  ratingRow: { flexDirection: 'row', justifyContent: 'space-between' }, ratingButton: { width: 56, height: 56, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#D8DCD6', borderRadius: 14 }, selectedRating: { borderColor: '#285C4D', backgroundColor: '#285C4D' }, ratingFace: { fontSize: 22 }, ratingNumber: { color: '#46514A', fontSize: 16, fontWeight: '800' }, selectedText: { color: '#FFFFFF' }, ratingLabels: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8 }, ratingLabel: { color: '#6E776F', fontSize: 12 },
  optionList: { gap: 8 }, option: { minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, borderWidth: 1, borderColor: '#D8DCD6', borderRadius: 12 }, selectedOption: { borderColor: '#285C4D', backgroundColor: '#E6EEE9' }, optionText: { color: '#46514A', fontSize: 14, fontWeight: '700' }, selectedOptionText: { color: '#285C4D' }, radio: { width: 20, height: 20, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, borderColor: '#C4C8CF', borderRadius: 10 }, selectedRadio: { borderColor: '#285C4D', backgroundColor: '#285C4D' }, radioDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#FFFFFF' }, pillowRow: { flexDirection: 'row', gap: 8 }, pillow: { flex: 1, minHeight: 48, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#D8DCD6', borderRadius: 12 },
  postureGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  postureCard: { width: '48%', minHeight: 124, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 10, paddingVertical: 10, borderWidth: 1, borderColor: '#DDE0DC', borderRadius: 10, backgroundColor: '#FFFFFF' },
  postureCardWide: { width: '100%', minHeight: 112 },
  selectedPostureCard: { borderWidth: 2, borderColor: '#285C4D', backgroundColor: '#E6EEE9' },
  postureLabelRow: { width: '100%', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 2, paddingHorizontal: 4 },
  footer: { paddingHorizontal: 24, paddingTop: 10, paddingBottom: 20, backgroundColor: '#FFFFFF' }, nextButton: { height: 56, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: '#285C4D' }, disabledButton: { backgroundColor: '#D8DCD6' }, nextText: { color: '#FFFFFF', fontSize: 16.5, fontWeight: '800' }, disabledText: { color: '#858D86' },
});
