import { StyleSheet } from 'react-native';
import { colors, layout, radius, spacing, typography } from '@/theme/tokens';

const common = { screen: { flex: 1, backgroundColor: colors.canvas }, topBar: { height: 56, flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'space-between' as const, paddingHorizontal: 10, borderBottomWidth: 1, borderBottomColor: colors.divider, backgroundColor: colors.surface }, topTitle: { fontSize: 16, fontWeight: '800' as const, color: colors.text }, spacer: { width: 44 } };

export const setupStyles = StyleSheet.create({
  ...common,
  content: { padding: layout.horizontalPadding }, eyebrow: { color: colors.primary, fontSize: 12, fontWeight: '800' }, title: { marginTop: 7, color: colors.text, ...typography.title }, description: { marginTop: 8, color: colors.textSecondary, fontSize: 14, lineHeight: 21 }, sectionTitle: { marginTop: 28, marginBottom: 11, color: colors.text, fontSize: 15, fontWeight: '800' },
  periodRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, period: { width: '48%', minHeight: 48, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, backgroundColor: colors.surface }, selectedPeriod: { borderColor: colors.primary, backgroundColor: colors.primary }, periodText: { color: colors.textSecondary, fontSize: 13, fontWeight: '800' }, selectedPeriodText: { color: colors.white },
  customDates: { gap: 8, padding: 12, borderRadius: radius.lg, backgroundColor: colors.surface }, dateField: { minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 14, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md }, dateLabel: { color: colors.textSecondary, fontSize: 13 }, dateValue: { color: colors.text, fontSize: 14, fontWeight: '800' }, dateDone: { minHeight: 44, alignItems: 'center', justifyContent: 'center' }, dateDoneText: { color: colors.primary, fontSize: 14, fontWeight: '800' },
  options: { overflow: 'hidden', borderRadius: radius.lg, backgroundColor: colors.surface }, option: { minHeight: 66, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 17, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: colors.divider }, optionCopy: { flex: 1, paddingRight: 10 }, optionLabel: { color: colors.text, fontSize: 14, fontWeight: '700' }, optionDescription: { marginTop: 3, color: colors.textMuted, fontSize: 12, lineHeight: 18 },
  privacy: { marginTop: 16, padding: 16, borderRadius: radius.lg, backgroundColor: colors.primarySoft }, privacyTitle: { color: colors.primary, fontSize: 13, fontWeight: '800' }, privacyText: { marginTop: 5, color: colors.textSecondary, fontSize: 12, lineHeight: 18 }, action: { position: 'absolute', right: 0, bottom: 0, left: 0, paddingHorizontal: 20, paddingTop: 12, borderTopWidth: 1, borderTopColor: colors.divider, backgroundColor: colors.surface }, primary: { minHeight: 56, alignItems: 'center', justifyContent: 'center', borderRadius: radius.lg, backgroundColor: colors.primary }, disabled: { opacity: .35 }, primaryText: { color: colors.white, fontSize: 15, fontWeight: '800' },
});

export const previewStyles = StyleSheet.create({
  ...common,
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, loading: { marginTop: 10, color: colors.textSecondary, fontSize: 13 }, errorTitle: { color: colors.text, fontSize: 17, fontWeight: '800' }, retry: { minHeight: 44, marginTop: 14, paddingHorizontal: 16, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colors.primarySoft }, retryText: { color: colors.primary, fontWeight: '800' }, content: { padding: 20 },
  reportCard: { padding: 22, borderWidth: 1, borderColor: colors.border, borderRadius: radius.xl, backgroundColor: colors.surface }, brandRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, brand: { color: colors.primary, fontSize: 17, fontWeight: '900' }, period: { color: colors.textSecondary, fontSize: 12, fontWeight: '800' }, userName: { marginTop: 18, color: colors.text, fontSize: 17, fontWeight: '800' }, created: { marginTop: 4, color: colors.textMuted, fontSize: 12 }, headline: { marginTop: 20, color: colors.text, fontSize: 22, lineHeight: 31, fontWeight: '800' }, divider: { height: 1, marginVertical: 19, backgroundColor: colors.divider }, metric: { paddingVertical: 10 }, metricLabel: { color: colors.textMuted, fontSize: 12, fontWeight: '700' }, metricValue: { marginTop: 4, color: colors.text, fontSize: 19, fontWeight: '800' }, change: { marginTop: 3, color: colors.primary, fontSize: 12, fontWeight: '700' },
  areaBox: { marginTop: 12, padding: 14, borderRadius: radius.md, backgroundColor: colors.surfaceSubtle }, areaLabel: { color: colors.textSecondary, fontSize: 12, fontWeight: '800' }, tags: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 8 }, tag: { paddingHorizontal: 9, paddingVertical: 5, overflow: 'hidden', borderRadius: radius.sm, color: colors.textSecondary, backgroundColor: colors.surfaceStrong, fontSize: 12, fontWeight: '800' }, routineRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 14, padding: 15, borderRadius: radius.md, backgroundColor: colors.primarySoft }, routineLabel: { color: colors.textSecondary, fontSize: 13, fontWeight: '700' }, routineValue: { color: colors.primary, fontSize: 16, fontWeight: '800' }, feedback: { marginTop: 8, color: colors.textSecondary, fontSize: 13, lineHeight: 20 }, note: { marginTop: 18, color: colors.textMuted, fontSize: 12, lineHeight: 18 },
  expertButton: { minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 12, paddingHorizontal: 16, borderRadius: radius.md, backgroundColor: colors.primarySoft }, expertButtonText: { color: colors.primary, fontSize: 14, fontWeight: '800' }, shareInfo: { marginTop: 14, textAlign: 'center', color: colors.textMuted, fontSize: 12 }, status: { marginTop: 8, color: colors.success, fontSize: 13, fontWeight: '700', textAlign: 'center' },
  action: { position: 'absolute', right: 0, bottom: 0, left: 0, paddingHorizontal: 16, paddingTop: 10, borderTopWidth: 1, borderTopColor: colors.divider, backgroundColor: colors.surface }, actionRow: { flexDirection: 'row', gap: 6 }, actionItem: { flex: 1, minHeight: 58, alignItems: 'center', justifyContent: 'center', gap: 4, borderRadius: radius.md, backgroundColor: colors.surfaceSubtle }, actionText: { color: colors.text, fontSize: 12, fontWeight: '700' }, pressed: { opacity: .58 },
  expertScreen: { flex: 1, backgroundColor: colors.canvas }, expertTop: { minHeight: 56, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20 }, expertTitle: { color: colors.text, fontSize: 18, fontWeight: '800' }, closeButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, expertContent: { padding: 20 },
});
