import { useState } from 'react';
import { Pressable, ScrollView, Switch, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import NavigationBackButton from '@/components/navigation-back-button';
import type { ReportOptions, ReportPeriod } from '@/domain/wellness';
import { setupStyles as styles } from './report.styles';
export default function ReportSetupScreen(){const router=useRouter();const insets=useSafeAreaInsets();const[options,setOptions]=useState<ReportOptions>({period:'7days',includeSleep:true,includeActivity:true,includeDiscomfort:true,includeRoutines:true});const set=<K extends keyof ReportOptions>(key:K,value:ReportOptions[K])=>setOptions(current=>({...current,[key]:value}));const count=[options.includeSleep,options.includeActivity,options.includeDiscomfort,options.includeRoutines].filter(Boolean).length;const next=()=>router.push({pathname:'/reports/preview',params:{period:options.period,sleep:String(options.includeSleep),activity:String(options.includeActivity),discomfort:String(options.includeDiscomfort),routines:String(options.includeRoutines)}});return <SafeAreaView edges={['top']} style={styles.screen}><View style={styles.topBar}><NavigationBackButton accessibilityLabel="이전 화면으로" fallbackHref="/(tabs)/records"/><Text style={styles.topTitle}>요약 설정</Text><View style={styles.spacer}/></View><ScrollView contentContainerStyle={[styles.content,{paddingBottom:insets.bottom+120}]}><Text style={styles.eyebrow}>기록 요약</Text><Text style={styles.title}>어떤 기록을{`\n`}요약할까요?</Text><Text style={styles.description}>원하는 기간과 항목을 선택하면 읽기 쉬운 카드로 정리해요.</Text><Text style={styles.sectionTitle}>기간</Text><View style={styles.periodRow}>{([['7days','7일'],['14days','14일'],['30days','30일']]as Array<[ReportPeriod,string]>).map(([id,label])=><Pressable accessibilityRole="button" accessibilityState={{selected:options.period===id}} key={id} onPress={()=>set('period',id)} style={[styles.period,options.period===id&&styles.selectedPeriod]}><Text style={[styles.periodText,options.period===id&&styles.selectedPeriodText]}>최근 {label}</Text></Pressable>)}</View><Text style={styles.sectionTitle}>포함할 항목</Text><View style={styles.options}><Option label="수면 시간과 흐름" value={options.includeSleep} onChange={value=>set('includeSleep',value)}/><Option label="걸음 수와 활동량" value={options.includeActivity} onChange={value=>set('includeActivity',value)}/><Option label="불편 부위와 강도" value={options.includeDiscomfort} onChange={value=>set('includeDiscomfort',value)}/><Option label="루틴 실행 기록" value={options.includeRoutines} onChange={value=>set('includeRoutines',value)}/></View><View style={styles.privacy}><Text style={styles.privacyTitle}>개인정보 안내</Text><Text style={styles.privacyText}>선택한 항목만 요약 카드에 포함되며, 공유는 사용자가 직접 실행할 때만 이루어져요.</Text></View></ScrollView><View style={[styles.action,{paddingBottom:Math.max(insets.bottom,12)}]}><Pressable accessibilityRole="button" disabled={count===0} onPress={next} style={[styles.primary,count===0&&styles.disabled]}><Text style={styles.primaryText}>요약 미리보기 · {count}개 항목</Text></Pressable></View></SafeAreaView>}
function Option({label,value,onChange}:{label:string;value:boolean;onChange:(value:boolean)=>void}){return <View style={styles.option}><Text style={styles.optionLabel}>{label}</Text><Switch accessibilityLabel={label} onValueChange={onChange} trackColor={{false:'#DDE1E7',true:'#8EB0F6'}} thumbColor={value?'#1257E0':'#FFF'} value={value}/></View>}
