import { StyleSheet } from 'react-native';
import { colors, layout, radius, spacing, typography } from '@/theme/tokens';

const common = { screen: { flex: 1, backgroundColor: colors.surface }, topBar: { minHeight: 56, flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'space-between' as const, paddingHorizontal: 10, paddingVertical: spacing.xxs, backgroundColor: colors.surface }, topTitle: { flex: 1, flexShrink: 1, textAlign: 'center' as const, fontSize: 17, lineHeight: 24, fontWeight:'700' as const, color: colors.text }, spacer: { width: 44 } };

export const setupStyles = StyleSheet.create({
  ...common,
  content: { width: '100%', maxWidth: layout.maxContentWidth, alignSelf: 'center', padding: layout.horizontalPadding }, eyebrow: { color: colors.data, ...typography.caption, fontWeight:'700' }, title: { maxWidth: 320, marginTop: 7, color: colors.text, ...typography.display }, description: { maxWidth: 340, marginTop: 8, color: colors.textSecondary, ...typography.body }, sectionTitle: { marginTop: 36, marginBottom: 10, color: colors.text, ...typography.sectionTitle },
  periodRow: { flexDirection: 'row',gap:spacing.xxs,padding:spacing.xxs,borderRadius:radius.md,backgroundColor:colors.surfaceSubtle }, period: { flex: 1, minHeight: 42, alignItems: 'center', justifyContent: 'center',borderRadius:radius.sm }, selectedPeriod: { backgroundColor:colors.surface }, periodText: { color: colors.textMuted, fontSize: 13, fontWeight:'600' }, selectedPeriodText: { color: colors.primary,fontWeight:'700' },
  customDates: { gap: 8, marginTop: spacing.sm, paddingVertical: spacing.sm }, dateField: { minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',borderBottomWidth:1,borderBottomColor:colors.border }, dateLabel: { color: colors.textSecondary, fontSize: 13 }, dateValue: { color: colors.text, fontSize: 14, fontWeight:'700' }, dateError:{color:colors.danger,...typography.caption},dateDone: { minHeight: 44, alignItems: 'center', justifyContent: 'center' }, dateDoneText: { color: colors.data, fontSize: 14, fontWeight:'700' },
  options: { overflow:'hidden',borderRadius:radius.lg,backgroundColor:colors.surfaceSubtle }, option: { minHeight: 70, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal:spacing.md,paddingVertical: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.divider }, optionCopy: { flex: 1, paddingRight: 10 }, optionLabel: { color: colors.text, fontSize: 15, fontWeight: '600' }, optionDescription: { marginTop: 3, color: colors.textMuted, ...typography.caption },
  privacy: { marginTop: 16, padding: 16,borderRadius:radius.md,backgroundColor:colors.primarySoft }, privacyTitle: { color: colors.primary, fontSize: 13, fontWeight:'700' }, privacyText: { marginTop: 5, color: colors.textSecondary, fontSize: 12, lineHeight: 18 }, action: { position: 'absolute', right: 0, bottom: 0, left: 0, paddingHorizontal: 20, paddingTop: 12, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.divider, backgroundColor: colors.surface }, primary: { minHeight: layout.ctaHeight, alignItems: 'center', justifyContent: 'center',borderRadius:radius.md, backgroundColor: colors.primary }, disabled: { opacity: .35 }, primaryText: { color: colors.white, fontSize: 15, fontWeight:'700' },
});

export const previewStyles = StyleSheet.create({
  ...common,
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, loading: { marginTop: 10, color: colors.textSecondary, fontSize: 13 }, errorTitle: { color: colors.text, fontSize: 17, fontWeight:'700' }, retry: { minHeight: 44, marginTop: 14, paddingHorizontal: 16, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colors.primarySoft }, retryText: { color: colors.primary, fontWeight:'700' }, content: { width: '100%', maxWidth: layout.maxContentWidth, alignSelf: 'center', padding: 20 },
  reportCard: { padding:spacing.lg,borderRadius:radius.xl,backgroundColor:colors.surfaceSubtle }, brandRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, brand: { color: colors.primary, fontSize: 17, fontWeight:'700' }, period: { color: colors.textSecondary, fontSize: 12, fontWeight: '600' }, userName: { marginTop: 24, color: colors.text, fontSize: 15, fontWeight: '600' }, created: { marginTop: 3, color: colors.textMuted, fontSize: 12 }, headline: { maxWidth: 330, marginTop: 18, color: colors.text, fontSize: 24, lineHeight: 34, fontWeight:'700' }, divider: { height: 1, marginVertical: 20, backgroundColor: colors.divider }, metric: { paddingVertical: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.divider }, metricLabel: { color: colors.textMuted, fontSize: 12, fontWeight: '600' }, metricValue: { marginTop: 4, color: colors.text, fontSize: 20, fontWeight:'700' }, change: { marginTop: 3, color: colors.data, fontSize: 12, fontWeight: '600' },
  areaBox: { paddingVertical: 16, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: colors.divider }, areaLabel: { color: colors.textSecondary, fontSize: 12, fontWeight:'700' }, tags: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 8 }, tag: { paddingHorizontal: 9, paddingVertical: 5, overflow: 'hidden', borderRadius: radius.sm, color: colors.textSecondary, backgroundColor: colors.surfaceStrong, fontSize: 12, fontWeight:'700' }, routineRow: { minHeight: 60, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: StyleSheet.hairlineWidth, borderColor: colors.divider }, routineLabel: { color: colors.textSecondary, fontSize: 13, fontWeight: '700' }, routineValue: { color: colors.recovery, fontSize: 16, fontWeight:'700' }, feedback: { marginTop: 10, color: colors.textSecondary, fontSize: 13, lineHeight: 20 }, note: { marginTop: 22, color: colors.textMuted, fontSize: 12, lineHeight: 18 },
  expertButton: { minHeight: 56, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 12, borderTopWidth: StyleSheet.hairlineWidth, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: colors.divider }, expertButtonText: { color: colors.primary, fontSize: 14, fontWeight:'700' }, shareInfo: { marginTop: 14, textAlign: 'center', color: colors.textMuted, fontSize: 12 }, status: { marginTop: 8, color: colors.success, fontSize: 13, fontWeight: '700', textAlign: 'center' },
  action: { position: 'absolute', right: 0, bottom: 0, left: 0, paddingHorizontal: 16, paddingTop: 10, borderTopWidth: 1, borderTopColor: colors.divider, backgroundColor: colors.surface }, actionRow: { flexDirection: 'row', gap: 6 }, actionItem: { flex: 1, minHeight: 58, alignItems: 'center', justifyContent: 'center', gap: 4, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, backgroundColor: colors.surface }, actionText: { color: colors.text, fontSize: 12, fontWeight: '700' }, disabledAction:{opacity:.45},pressed: { opacity: .58 },
  expertScreen: { flex: 1, backgroundColor: colors.canvas }, expertTop: { minHeight: 56, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20 }, expertTitle: { color: colors.text, fontSize: 18, fontWeight:'700' }, closeButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, expertContent: { padding: 20 },
});
