import { useCallback } from 'react';
import { ActivityIndicator, Pressable, ScrollView, Share, Text, View } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import NavigationBackButton from '@/components/navigation-back-button';
import type { HealthReport, ReportOptions, ReportPeriod } from '@/domain/wellness';
import { useAsyncData } from '@/hooks/use-async-data';
import { wellnessApi } from '@/services/wellness-api';
import { previewStyles as styles } from './report.styles';
export default function ReportPreviewScreen(){const insets=useSafeAreaInsets();const params=useLocalSearchParams<{period?:string;sleep?:string;activity?:string;discomfort?:string;routines?:string}>();const options:ReportOptions={period:(params.period as ReportPeriod)||'7days',includeSleep:params.sleep!=='false',includeActivity:params.activity!=='false',includeDiscomfort:params.discomfort!=='false',includeRoutines:params.routines!=='false'};const key=JSON.stringify(options);const loader=useCallback(()=>wellnessApi.createHealthReport(options),[key]);const{data,error,isLoading,reload}=useAsyncData<HealthReport|null>(loader,null);const share=async()=>{if(!data)return;const metrics=data.highlights.map(item=>`${item.label}: ${item.value} (${item.change})`).join('\n');await Share.share({title:'몸기록 요약',message:`몸기록 ${data.periodLabel} 요약\n${data.headline}\n${metrics}\n루틴 ${data.routineCount}회\n\n${data.note}`});};return <SafeAreaView edges={['top']} style={styles.screen}><View style={styles.topBar}><NavigationBackButton accessibilityLabel="요약 설정으로 돌아가기" fallbackHref="/reports/setup"/><Text style={styles.topTitle}>요약 미리보기</Text><View style={styles.spacer}/></View>{isLoading?<View style={styles.center}><ActivityIndicator color="#1257E0"/><Text style={styles.loading}>요약을 만드는 중</Text></View>:error||!data?<View style={styles.center}><Text style={styles.errorTitle}>요약을 만들지 못했어요</Text><Pressable onPress={()=>void reload().catch(()=>undefined)} style={styles.retry}><Text style={styles.retryText}>다시 시도</Text></Pressable></View>:<><ScrollView contentContainerStyle={[styles.content,{paddingBottom:insets.bottom+120}]}><View style={styles.reportCard}><View style={styles.brandRow}><Text style={styles.brand}>몸기록</Text><Text style={styles.period}>{data.periodLabel}</Text></View><Text style={styles.created}>{data.createdAtLabel} 생성</Text><Text style={styles.headline}>{data.headline}</Text><View style={styles.divider}/>{data.highlights.map(item=><View key={item.label} style={styles.metric}><Text style={styles.metricLabel}>{item.label}</Text><Text style={styles.metricValue}>{item.value}</Text><Text style={styles.change}>{item.change}</Text></View>)}{data.options.includeDiscomfort?<View style={styles.areaBox}><Text style={styles.areaLabel}>주요 불편 부위</Text><View style={styles.tags}>{data.discomfortAreas.map(area=><Text key={area} style={styles.tag}>{area}</Text>)}</View></View>:null}{data.options.includeRoutines?<View style={styles.routineRow}><Text style={styles.routineLabel}>루틴 실행</Text><Text style={styles.routineValue}>{data.routineCount}회</Text></View>:null}<Text style={styles.note}>{data.note}</Text></View><Text style={styles.shareInfo}>공유 시 위 카드의 텍스트 정보만 전달돼요.</Text></ScrollView><View style={[styles.action,{paddingBottom:Math.max(insets.bottom,12)}]}><Pressable accessibilityRole="button" onPress={()=>void share()} style={styles.primary}><Text style={styles.primaryText}>요약 공유하기</Text></Pressable></View></>}</SafeAreaView>}
