import { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, Modal, Pressable, ScrollView, Text, View } from 'react-native';
import { useFocusEffect, useRouter } from 'expo-router';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';

import { AppIcon } from '@/components/app-icon';
import { Momi } from '@/components/momi';
import StateNotice from '@/components/state-notice';
import type { BodyMapPart, HomeSummary } from '@/domain/wellness';
import { useAsyncData } from '@/hooks/use-async-data';
import { wellnessApi } from '@/services/wellness-api';
import { colors } from '@/theme/tokens';
import HomeAvatar from './HomeAvatar';
import { styles } from './home.styles';

const EMPTY_HOME: HomeSummary = { dateLabel: '', conditionLabel: '', evidence: '', tags: [], recentRecords: [], tips: [], insight: { text: '', tags: [] }, routine: { title: '', description: '', duration: '', intensity: '' }, sleepTrend: { values: [], averageLabel: '', periodLabel: '' }, bodyHighlights: [], bodyDetails: { neck: { title: '', lines: [] }, shoulder: { title: '', lines: [] }, chest: { title: '', lines: [] }, upperArm: { title: '', lines: [] }, forearm: { title: '', lines: [] }, abdomen: { title: '', lines: [] }, hip: { title: '', lines: [] }, thigh: { title: '', lines: [] }, knee: { title: '', lines: [] }, calf: { title: '', lines: [] } }, streakDays: 0, checkState: 'not-started' };
const PART_LABELS: Record<string, string> = { neck: '목', shoulder: '어깨', chest: '가슴', upperArm: '윗팔', forearm: '아래팔', abdomen: '복부', hip: '골반', thigh: '허벅지', knee: '무릎', calf: '종아리' };
const WEEKDAYS = ['일', '월', '화', '수', '목', '금', '토'];

export default function HomeScreen() {
  const router = useRouter(); const insets = useSafeAreaInsets(); const { data, error, isLoading, reload } = useAsyncData(wellnessApi.getHomeSummary, EMPTY_HOME); const home = useMemo(() => ({ ...EMPTY_HOME, ...data }), [data]); const done = home.checkState === 'completed';
  useFocusEffect(useCallback(() => { void reload().catch(() => undefined); }, [reload]));
  if (isLoading) return <SafeAreaView style={styles.screen}><View style={styles.loading}><ActivityIndicator color={colors.primary} /><Text style={styles.loadingText}>오늘의 기록을 준비하고 있어요</Text></View></SafeAreaView>;
  if (error) return <SafeAreaView style={styles.screen}><View style={styles.error}><StateNotice actionLabel="다시 불러오기" description="작성 중인 기록은 그대로 있어요." icon="!" onAction={() => void reload().catch(() => undefined)} title="홈을 불러오지 못했어요" tone="error" /></View></SafeAreaView>;
  return <SafeAreaView edges={['top']} style={styles.screen}><ScrollView contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + 116 }]} showsVerticalScrollIndicator={false}>
    <Header date={home.dateLabel || formatToday()} onChat={() => router.push('/assistant')} onNotifications={() => router.push('/settings/notifications')} />
    {done
      ? <DoneHome home={home} onEdit={() => router.push('/check/auto')} onOpenPattern={() => router.push('/(tabs)/discover')} onOpenRecords={() => router.push('/(tabs)/records')} onStartRoutine={() => router.push('/routine')} />
      : <><EmptyHome onStart={() => router.push('/check/auto')} /><HomeContinuity home={home} onOpenPattern={() => router.push('/(tabs)/discover')} onStartRoutine={() => router.push('/routine')} /></>}
  </ScrollView></SafeAreaView>;
}

function Header({ date, onChat, onNotifications }: { date: string; onChat: () => void; onNotifications: () => void }) { return <View style={styles.header}><View><Text style={styles.dateLabel}>{date}</Text><Text style={styles.brand}>몸기록</Text></View><View style={styles.headerActions}><Pressable accessibilityLabel="웰니스 챗 열기" accessibilityRole="button" onPress={onChat} style={styles.iconBtn}><AppIcon color={colors.text} name="message" size={21} /></Pressable><Pressable accessibilityLabel="알림 설정 열기" accessibilityRole="button" onPress={onNotifications} style={styles.iconBtn}><AppIcon color={colors.text} name="bell" size={21} /><View style={styles.notification}><Text style={styles.notificationText}>3</Text></View></Pressable></View></View>; }

function EmptyHome({ onStart }: { onStart: () => void }) { return <View style={styles.emptySection}><View style={styles.emptyHero}><Text style={styles.emptyKicker}>오늘의 기록</Text><Text style={styles.emptyTitle}>오늘 몸의 상태를{`\n`}아직 적지 않았어요</Text><Text style={styles.emptyBody}>3분이면 충분해요 · 어제까지 6일 연속 기록 중</Text><View style={styles.emptyMap}><HomeAvatar defaultFill="rgba(255,255,255,.46)" defaultStroke="#3A5209" figureStyle={{ width: 148, height: 204 }} highlights={[]} hideHint onMarkerPress={() => undefined} scale={.61} stageStyle={{ height: 184 }} wrapStyle={{ minHeight: 184 }} /></View><Pressable accessibilityRole="button" onPress={onStart} style={({ pressed }) => [styles.emptyCta, pressed && styles.pressed]}><Text style={styles.emptyCtaText}>오늘 기록하기 →</Text></Pressable></View></View>; }

function DoneHome({ home, onEdit, onOpenPattern, onOpenRecords, onStartRoutine }: { home: HomeSummary; onEdit: () => void; onOpenPattern: () => void; onOpenRecords: () => void; onStartRoutine: () => void }) {
  const [selectedPart, setSelectedPart] = useState<BodyMapPart | null>(null);
  const highlight = home.bodyHighlights[0]; const firstTag = home.tags[0]; const metrics = [{ label: '수면', value: home.sleepTrend.averageLabel || '-', source: 'Apple 건강' }, { label: '걸음', value: typeof firstTag === 'string' ? firstTag : firstTag?.label || '-', source: 'Apple 건강' }, { label: '불편 강도', value: highlight ? `${highlight.intensity}/3` : '없음', source: '직접 입력' }];
  return <><View style={styles.section}><View style={styles.sectionTop}><Text style={styles.weekHeading}>이번 주 기록</Text><Text style={styles.weekCount}>{Math.min(home.streakDays, 7)} / 7일</Text></View><View style={styles.progressWrap}><View style={styles.progressTrack} /><View style={[styles.progressFill, { position: 'absolute', width: `${Math.min(100, (home.streakDays / 7) * 100)}%` }]} /><View style={styles.progressMomi}><Momi mood="happy" size={42} /></View><View style={styles.progressDays}>{WEEKDAYS.map((day, index) => <View key={day} style={[styles.progressDay, index >= home.streakDays && styles.progressDayFuture]} />)}</View></View><View style={styles.weekdays}>{WEEKDAYS.map((day, index) => <Text key={day} style={[styles.weekday, index === new Date().getDay() && styles.todayWeekday]}>{day}</Text>)}</View></View>
    <View style={styles.section}><View style={styles.sectionTop}><Text style={styles.sectionTitle}>오늘의 몸</Text><Pressable accessibilityRole="button" onPress={onEdit} style={styles.editPill}><Text style={styles.editPillText}>수정</Text></Pressable></View><Pressable accessibilityRole="button" disabled={!highlight} onPress={() => highlight && setSelectedPart(highlight.part)} style={({ pressed }) => [styles.bodyLayout, pressed && styles.pressed]}><View style={styles.bodyMapCard}><HomeAvatar defaultFill={colors.surfaceStrong} defaultStroke={colors.surface} figureStyle={{ width: 100, height: 144 }} highlights={home.bodyHighlights} hideHint onMarkerPress={setSelectedPart} scale={.37} stageStyle={{ height: 136 }} wrapStyle={{ minHeight: 146 }} /></View><View style={styles.bodyCopy}><Text style={styles.bodyName}>{highlight ? `${PART_LABELS[highlight.part] ?? '기록한 부위'} · 불편 ${highlight.intensity}단계` : '기록된 불편 신호가 없어요'}</Text><Text style={styles.bodyMeta}>{home.evidence || '부위를 눌러 기록한 강도와 느낌을 확인하세요.'}</Text>{highlight ? <View style={styles.bodyArrow}><Text style={styles.bodyArrowText}>상세 보기</Text><AppIcon color={colors.danger} name="chevron-right" size={15} /></View> : null}</View></Pressable><Text style={styles.bodyHint}>색이 표시된 부위를 누르면 상세 기록이 열려요.</Text></View>
    <View style={styles.metricStrip}>{metrics.map((metric, index) => <View key={metric.label} style={[styles.metric, index === metrics.length - 1 && styles.metricLast]}><Text style={styles.metricLabel}>{metric.label}</Text><Text style={styles.metricValue}>{metric.value}</Text><Text style={styles.metricSource}>{metric.source}</Text></View>)}</View>
    <HomeContinuity home={home} onOpenPattern={onOpenPattern} onStartRoutine={onStartRoutine} />
    {home.recentRecords.length ? <View style={styles.recent}><Text style={styles.recentTitle}>최근 기록</Text>{home.recentRecords.slice(0, 3).map((record) => <View key={record.id} style={styles.logRow}><View style={styles.logDot} /><Text style={styles.logDate}>{record.date}</Text><Text numberOfLines={1} style={styles.logValue}>{record.value}</Text></View>)}<Pressable accessibilityRole="button" onPress={onOpenRecords} style={styles.allLogs}><Text style={styles.allLogsText}>전체 기록 보기</Text><AppIcon color={colors.primaryText} name="chevron-right" size={16} /></Pressable></View> : null}
    <BodyDetailSheet detail={selectedPart ? home.bodyDetails[selectedPart] : null} onClose={() => setSelectedPart(null)} onEdit={() => { setSelectedPart(null); onEdit(); }} visible={selectedPart !== null} />
  </>;
}

function BodyDetailSheet({ detail, onClose, onEdit, visible }: { detail: HomeSummary['bodyDetails'][BodyMapPart] | null; onClose: () => void; onEdit: () => void; visible: boolean }) {
  const level = detail?.lines.find((line) => line.label === '불편 강도')?.value ?? '기록 없음';
  return <Modal animationType="slide" onRequestClose={onClose} presentationStyle="overFullScreen" statusBarTranslucent transparent visible={visible}><SafeAreaView edges={['top', 'bottom']} style={styles.sheetOverlay}><Pressable accessibilityLabel="부위 상세 닫기" accessibilityRole="button" onPress={onClose} style={styles.sheetDismiss}/><View style={styles.sheet}><View style={styles.sheetHandle}/><View style={styles.sheetHeader}><View><Text style={styles.sheetDate}>오늘의 기록</Text><Text accessibilityRole="header" style={styles.sheetTitle}>{detail?.title ?? '부위 기록'}</Text></View><View style={styles.sheetLevel}><Text style={styles.sheetLevelText}>{level}</Text></View></View><View style={styles.sheetInfo}>{detail?.lines.map((line) => <View key={line.label} style={styles.sheetInfoRow}><Text style={styles.sheetInfoLabel}>{line.label}</Text><Text style={styles.sheetInfoValue}>{line.value}</Text></View>)}</View><Text style={styles.sheetHistoryTitle}>최근 7일 이 부위</Text><View style={styles.sheetBars}>{[0, 0, 2, 3, 2, 3, 4].map((value, index) => <View key={index} style={styles.sheetBarItem}><View style={[styles.sheetBar, { height: value ? 8 + value * 7 : 5 }, index === 6 && styles.sheetBarCurrent]}/><Text style={[styles.sheetBarLabel, index === 6 && styles.sheetBarLabelCurrent]}>{['토','일','월','화','수','목','금'][index]}</Text></View>)}</View><View style={styles.sheetActions}><Pressable accessibilityRole="button" onPress={onClose} style={styles.sheetClose}><Text style={styles.sheetCloseText}>닫기</Text></Pressable><Pressable accessibilityRole="button" onPress={onEdit} style={styles.sheetEdit}><Text style={styles.sheetEditText}>이 부위 기록 수정</Text></Pressable></View></View></SafeAreaView></Modal>;
}

function HomeContinuity({ home, onOpenPattern, onStartRoutine }: { home: HomeSummary; onOpenPattern: () => void; onStartRoutine: () => void }) {
  return <>
    {home.recentPattern ? <Pressable accessibilityRole="button" onPress={onOpenPattern} style={({ pressed }) => [styles.pattern, pressed && styles.pressed]}><Text style={styles.patternKicker}>최근 변화</Text><Text style={styles.patternTitle}>{home.recentPattern.title}</Text><Text style={styles.patternBody}>{home.recentPattern.description}</Text><Text style={styles.patternLink}>커넥션에서 자세히 보기 →</Text></Pressable> : null}
    {home.routine.title ? <View style={styles.section}><View style={styles.sectionTop}><Text style={styles.sectionTitle}>오늘의 루틴</Text><View style={styles.routineBadge}><Text style={styles.routineBadgeText}>어깨 3일째라 추천</Text></View></View><View style={styles.routineCard}><View style={styles.routineTop}><View style={styles.routineArt}><Momi mood="cheer" size={52} /></View><View style={styles.routineCopy}><Text style={styles.routineTitle}>{home.routine.title}</Text><Text style={styles.routineMeta}>{[home.routine.duration, home.routine.intensity, '목·어깨', '준비물 없음'].filter(Boolean).join(' · ')}</Text><Text numberOfLines={2} style={styles.routineDescription}>{home.routine.description}</Text></View></View><View style={styles.routineSteps}><Text style={styles.routineStep}>1  자세 잡고 호흡하기 · 30초</Text><Text style={styles.routineStep}>2  목 옆선 천천히 늘리기 · 60초</Text><Text style={styles.routineStep}>3  어깨 천천히 돌리기 · 30초</Text></View><Pressable accessibilityRole="button" onPress={onStartRoutine} style={({ pressed }) => [styles.routineCta, pressed && styles.pressed]}><Text style={styles.routineCtaText}>루틴 시작</Text></Pressable></View></View> : null}
  </>;
}

function formatToday() { return new Intl.DateTimeFormat('ko-KR', { month: 'long', day: 'numeric', weekday: 'long' }).format(new Date()); }
