import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  pressed: { opacity: 0.55 },
  screen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  loadingContent: { flex: 1, paddingHorizontal: 24, paddingTop: 24 },
  loadingHeader: { width: 104, height: 16, borderRadius: 8, backgroundColor: '#ECEFF3' },
  loadingTitle: { width: '68%', height: 32, marginTop: 40, borderRadius: 10, backgroundColor: '#ECEFF3' },
  loadingBody: { width: '88%', height: 18, marginTop: 12, borderRadius: 8, backgroundColor: '#F2F4F6' },
  loadingCard: { height: 340, marginTop: 28, borderRadius: 18, backgroundColor: '#F2F4F6' },
  loadingCardSmall: { height: 112, marginTop: 16, borderRadius: 18, backgroundColor: '#F2F4F6' },
  errorContent: { flex: 1, justifyContent: 'center', paddingHorizontal: 24 },
  scrollContent: {
    paddingHorizontal: 24,
    paddingTop: 22,
  },
  todayPanel: { marginTop: 24, paddingHorizontal: 18, paddingTop: 18, paddingBottom: 14, borderWidth: 1, borderColor: '#E5E9EF', borderRadius: 20, backgroundColor: '#F8F9FB' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  brand: {
    color: '#17191C',
    fontSize: 15,
    fontWeight: '800',
  },
  date: {
    marginTop: 2,
    color: '#8B919B',
    fontSize: 12.5,
    fontWeight: '600',
  },
  headerActions: {
    flexDirection: 'row',
    gap: 12,
  },
  headerIcon: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bell: {
    color: '#17191C',
    fontSize: 22,
  },
  notificationDot: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#E03131',
  },
  profileIcon: {
    width: 21,
    height: 21,
    borderWidth: 1.7,
    borderColor: '#17191C',
    borderRadius: 11,
  },
  statusSection: {
    marginTop: 0,
  },
  statusQuestion: {
    color: '#17191C',
    fontSize: 24,
    fontWeight: '800',
    letterSpacing: -0.8,
  },
  statusValue: {
    marginTop: 9,
    color: '#E03131',
    fontSize: 17,
    fontWeight: '800',
  },
  statusEvidence: {
    marginTop: 4,
    color: '#8B919B',
    fontSize: 13.5,
  },
  streak: { marginTop: 8, color: '#267A52', fontSize: 12, fontWeight: '800' },
  tagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 12,
  },
  tag: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
    fontSize: 11.5,
    fontWeight: '700',
  },
  blueTag: {
    color: '#1257E0',
    backgroundColor: '#EAF0FE',
  },
  redTag: {
    color: '#E03131',
    backgroundColor: '#FDECEC',
  },
  grayTag: {
    color: '#4A4F58',
    backgroundColor: '#F4F5F7',
  },
  avatarCard: {
    minHeight: 360,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 14,
    paddingVertical: 8,
    borderRadius: 0,
    backgroundColor: 'transparent',
  },
  bodyMapWrap: {
    width: 230,
    height: 330,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  bodyMapImage: {
    width: 210,
    height: 300,
  },
  bodyMapArea: {
    position: 'absolute',
    overflow: 'hidden',
  },
  bodyMapAreaPressed: { opacity: 0.45 },
  bodyMapNeckTarget: {
    position: 'absolute',
    top: 34,
    left: 94,
    width: 42,
    height: 42,
  },
  bodyMapShoulderTarget: {
    position: 'absolute',
    top: 45,
    left: 57,
    width: 116,
    height: 50,
  },
  bodyMapHint: {
    marginTop: 2,
    color: '#8B919B',
    fontSize: 11.5,
    fontWeight: '600',
  },
  vectorBodyMapWrap: {
    width: '100%',
    height: 320,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  bodyMapStage: {
    width: '100%',
    height: 288,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  bodyMapFigure: {
    width: 160,
    height: 288,
    alignItems: 'center',
  },
  activeTrapeziusTouchTarget: {
    position: 'absolute',
    top: 48,
    left: 46,
    width: 68,
    height: 48,
  },
  bodyMapSummary: {
    width: 126,
    marginLeft: 4,
    padding: 14,
    borderWidth: 1,
    borderColor: '#E5E9EF',
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
  },
  bodyMapSummaryEyebrow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  bodyMapStatusDot: { width: 8, height: 8, borderRadius: 4 },
  bodyMapSummaryEyebrowText: { color: '#737B88', fontSize: 11, fontWeight: '700' },
  bodyMapSummaryTitle: { marginTop: 10, color: '#17191C', fontSize: 18, fontWeight: '800' },
  bodyMapSummaryDescription: { marginTop: 6, color: '#737B88', fontSize: 11.5, lineHeight: 17 },
  bodyMapLevelBadge: { alignSelf: 'flex-start', marginTop: 10, paddingHorizontal: 8, paddingVertical: 5, borderRadius: 8, backgroundColor: '#FFF0E9' },
  bodyMapLevelText: { color: '#D9582C', fontSize: 11, fontWeight: '800' },
  bodyMapLegendRow: { flexDirection: 'row', alignItems: 'center', gap: 7, marginTop: 10 },
  bodyMapActiveLegend: { width: 10, height: 10, borderRadius: 3, backgroundColor: '#EF7442' },
  bodyMapInactiveLegend: { width: 10, height: 10, borderRadius: 3, backgroundColor: '#E2E8F1' },
  bodyMapLegendText: { color: '#737B88', fontSize: 10.5, fontWeight: '600' },
  avatarWrap: {
    width: 180,
    height: 242,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  avatarMarker: {
    position: 'absolute',
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 17,
  },
  neckMarker: {
    top: 42,
    left: 73,
    backgroundColor: 'rgba(224,49,49,.16)',
  },
  shoulderMarker: {
    top: 65,
    left: 28,
    backgroundColor: 'rgba(232,89,12,.15)',
  },
  markerDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  neckDot: {
    backgroundColor: '#E03131',
  },
  shoulderDot: {
    backgroundColor: '#E8590C',
  },
  avatarLegend: {
    position: 'absolute',
    bottom: 0,
    flexDirection: 'row',
    gap: 12,
  },
  legendText: {
    color: '#8B919B',
    fontSize: 11.5,
  },
  avatarCaption: {
    color: '#8B919B',
    fontSize: 12.5,
  },
  insightSection: {
    marginTop: 24,
    paddingTop: 22,
    borderTopWidth: 1,
    borderTopColor: '#E9ECF0',
  },
  insightLabel: { marginBottom: 7, color: '#687180', fontSize: 12, fontWeight: '800' },
  insightText: {
    color: '#17191C',
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 26,
  },
  reportEntry: { minHeight: 68, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 18, paddingHorizontal: 16, borderWidth: 1, borderColor: '#DDE2E8', borderRadius: 14, backgroundColor: '#FFFFFF' },
  reportEntryTitle: { color: '#17191C', fontSize: 15, fontWeight: '800' },
  reportEntryText: { marginTop: 4, color: '#687180', fontSize: 12 },
  patternEntry: { marginTop: 12, paddingVertical: 17, borderTopWidth: 1, borderBottomWidth: 1, borderColor: '#DDE2E8' }, patternLabel: { color: '#687180', fontSize: 12, fontWeight: '800' }, patternTitle: { marginTop: 6, color: '#17191C', fontSize: 16, fontWeight: '800' }, patternText: { marginTop: 5, color: '#465163', fontSize: 13, lineHeight: 20 },
  recordCard: {
    marginTop: 22,
    padding: 20,
    borderRadius: 16,
    backgroundColor: '#182033',
  },
  primaryActionEyebrow: { color: '#AFC7FA', fontSize: 12, fontWeight: '800' },
  primaryActionTitle: { marginTop: 8, color: '#FFFFFF', fontSize: 19, lineHeight: 27, fontWeight: '800' },
  primaryActionDescription: { marginTop: 7, color: '#C5CBD6', fontSize: 13, lineHeight: 20 },
  cardTitle: {
    color: '#17191C',
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 23,
  },
  cardDescription: {
    marginTop: 5,
    color: '#4A4F58',
    fontSize: 13.5,
    lineHeight: 21,
  },
  cardButton: {
    alignSelf: 'flex-start',
    marginTop: 15,
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
    color: '#182033',
    fontSize: 14,
    fontWeight: '800',
  },
  routineCard: {
    flexDirection: 'row',
    gap: 14,
    marginTop: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#EEF0F3',
    borderRadius: 18,
  },
  routineThumb: {
    width: 52,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: '#F4F5F7',
  },
  routineFigure: {
    color: '#17191C',
    fontSize: 26,
  },
  routineCopy: {
    flex: 1,
  },
  metaRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 8,
  },
  metaTag: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    backgroundColor: '#F4F5F7',
    color: '#4A4F58',
    fontSize: 11,
    fontWeight: '700',
  },
  section: {
    marginTop: 26,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: '#17191C',
    fontSize: 17,
    fontWeight: '800',
  },
  tip: {
    marginTop: 12,
    color: '#4A4F58',
    fontSize: 14,
    lineHeight: 22,
  },
  chartCard: {
    marginTop: 26,
    padding: 20,
    borderRadius: 18,
    backgroundColor: '#17191C',
  },
  chartLabel: {
    color: '#6B7481',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.3,
  },
  chartTitle: {
    marginTop: 8,
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  sleepChart: {
    marginTop: 18,
  },
  chartFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  chartValue: {
    color: '#7FA6FF',
    fontSize: 14,
    fontWeight: '800',
  },
  chartPeriod: {
    color: '#9AA3AE',
    fontSize: 12,
  },
  viewAll: {
    color: '#8B919B',
    fontSize: 13,
    fontWeight: '700',
  },
  recentRow: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF0F3',
  },
  recentDate: {
    width: 68,
    color: '#17191C',
    fontSize: 13.5,
    fontWeight: '700',
  },
  recentValue: {
    flex: 1,
    color: '#4A4F58',
    fontSize: 13.5,
  },
  chevron: {
    color: '#C3C7CE',
    fontSize: 26,
  },
  helperButton: {
    position: 'absolute',
    right: 18,
    bottom: 94,
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 17,
    borderRadius: 25,
    backgroundColor: '#17191C',
    shadowColor: '#101419',
    shadowOpacity: 0.45,
    shadowRadius: 10,
    elevation: 5,
  },
  helperIcon: { width: 24, height: 24, alignItems: 'center', justifyContent: 'center' },
  helperText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  routineEffect: { marginTop: 8, color: '#1257E0', fontSize: 10.5, lineHeight: 16, fontWeight: '700' },
  feedbackCard: { marginTop: 12, padding: 18, borderRadius: 20, backgroundColor: '#EEF3FF' },
  feedbackEyebrow: { color: '#1257E0', fontSize: 10.5, fontWeight: '800' },
  feedbackQuestion: { marginTop: 7, color: '#17191C', fontSize: 16, lineHeight: 23, fontWeight: '800' },
  feedbackOptions: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 14 },
  feedbackOption: { width: '48%', minHeight: 44, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#D6E1F7', borderRadius: 12, backgroundColor: '#FFFFFF' },
  feedbackOptionText: { color: '#315994', fontSize: 10.5, fontWeight: '800' },
  feedbackDanger: { borderColor: '#F3C6C8', backgroundColor: '#FFF6F6' },
  feedbackDangerText: { color: '#C83D42' },
  feedbackDone: { marginTop: 12, padding: 18, borderRadius: 18, backgroundColor: '#EAF7F0' },
  feedbackDoneTitle: { color: '#247A50', fontSize: 14, fontWeight: '800' },
  feedbackDoneText: { marginTop: 4, color: '#4D7962', fontSize: 11 },
  signalLink: { minHeight: 44, justifyContent: 'center', marginTop: 6 },
  signalLinkText: { color: '#C83D42', fontSize: 11, fontWeight: '800' },
  tabBar: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    left: 0,
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#EEF0F3',
    backgroundColor: '#FFFFFF',
  },
  tabItem: {
    width: '25%',
    color: '#B0B5BD',
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 18,
    textAlign: 'center',
  },
  activeTab: {
    color: '#1257E0',
  },
  sheetOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(16,20,25,.42)',
  },
  bottomSheet: {
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 28,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    backgroundColor: '#FFFFFF',
  },
  grabber: {
    alignSelf: 'center',
    width: 38,
    height: 4,
    marginBottom: 20,
    borderRadius: 2,
    backgroundColor: '#DEE1E6',
  },
  sheetTitle: {
    color: '#17191C',
    fontSize: 20,
    fontWeight: '800',
  },
  sheetSubtitle: {
    marginTop: 18,
    color: '#8B919B',
    fontSize: 13,
    fontWeight: '700',
  },
  sheetRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 13,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF0F3',
  },
  sheetLabel: {
    color: '#8B919B',
    fontSize: 13.5,
  },
  sheetValue: {
    color: '#17191C',
    fontSize: 13.5,
    fontWeight: '700',
  },
  sheetActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 20,
  },
  sheetSecondaryButton: {
    flex: 1,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: '#F4F5F7',
  },
  sheetSecondaryText: {
    color: '#17191C',
    fontSize: 14.5,
    fontWeight: '700',
  },
  sheetPrimaryButton: {
    flex: 1,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: '#17191C',
  },
  sheetPrimaryText: {
    color: '#FFFFFF',
    fontSize: 14.5,
    fontWeight: '700',
  },
});
