import { StyleSheet } from 'react-native';
import { colors, layout, motion, radius, spacing, typography } from '@/theme/tokens';

export const styles = StyleSheet.create({
  screen:{flex:1,backgroundColor:colors.canvas},pressed:{opacity:motion.pressOpacity},scrollContent:{width:'100%',maxWidth:layout.maxContentWidth,alignSelf:'center',paddingHorizontal:layout.horizontalPadding},
  header:{minHeight:78,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},brand:{color:colors.text,fontSize:19,lineHeight:27,fontWeight:'700',letterSpacing:-.5},date:{marginTop:1,color:colors.textMuted,...typography.caption},headerIcon:{width:44,height:44,alignItems:'center',justifyContent:'center',borderRadius:22,backgroundColor:colors.surfaceSubtle},
  entryScene:{minHeight:390,flexDirection:'row',overflow:'hidden',marginTop:spacing.xs,borderRadius:radius.xl,backgroundColor:colors.surfaceSubtle},entryCopy:{zIndex:1,flex:1,paddingTop:spacing.xl,paddingLeft:spacing.lg},contextLine:{width:28,height:4,marginBottom:spacing.md,borderRadius:2,backgroundColor:colors.body},entryTitle:{width:250,color:colors.text,fontSize:30,lineHeight:38,fontWeight:'700',letterSpacing:-1},entryDescription:{width:240,marginTop:spacing.sm,color:colors.textSecondary,...typography.body},entryBody:{position:'absolute',right:-82,bottom:-20,width:270,opacity:.62},
  recordAction:{minHeight:78,flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:spacing.sm,paddingHorizontal:spacing.lg,borderRadius:radius.lg,backgroundColor:colors.primary},recordActionPressed:{backgroundColor:colors.primaryPressed},recordActionTitle:{color:colors.white,fontSize:17,lineHeight:24,fontWeight:'700'},recordActionMeta:{marginTop:3,color:'rgba(255,255,255,.78)',...typography.caption},
  statusScene:{marginTop:spacing.sm,padding:spacing.lg,borderRadius:radius.xl,backgroundColor:colors.primarySoft},statusTop:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},statusLabel:{color:colors.primary,...typography.caption,fontWeight:'700'},editButton:{minWidth:52,minHeight:44,alignItems:'flex-end',justifyContent:'center'},editButtonText:{color:colors.primary,...typography.caption,fontWeight:'600'},statusTitle:{maxWidth:440,marginTop:spacing.xs,color:colors.text,...typography.display},statusEvidence:{maxWidth:440,marginTop:spacing.sm,color:colors.textSecondary,...typography.body},streak:{marginTop:spacing.md,color:colors.primary,...typography.caption,fontWeight:'600'},
  bodyLedger:{marginTop:spacing.lg,padding:spacing.lg,borderRadius:radius.xl,backgroundColor:colors.surfaceSubtle},sectionHead:{minHeight:44,flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between',gap:spacing.md},sectionTitle:{color:colors.text,...typography.sectionTitle},sectionDescription:{marginTop:2,color:colors.textMuted,...typography.caption},sectionCount:{color:colors.body,fontSize:24,lineHeight:30,fontWeight:'600'},
  vectorBodyMapWrap:{width:'100%',minHeight:340,alignItems:'center',justifyContent:'flex-start',marginTop:spacing.sm,backgroundColor:'transparent'},bodyMapStage:{width:'100%',height:278,alignItems:'center',justifyContent:'center'},bodyMapFigure:{width:190,height:270,alignItems:'center'},activeTrapeziusTouchTarget:{position:'absolute',top:48,left:46,width:68,height:48},bodyMapSelection:{marginTop:spacing.xs,color:colors.text,fontSize:14,fontWeight:'700'},bodyMapHint:{marginTop:spacing.xs,color:colors.textMuted,...typography.caption},
  noBodyRecord:{minHeight:120,justifyContent:'center',marginTop:spacing.md,padding:spacing.md,borderRadius:radius.md,backgroundColor:colors.surface},noBodyTitle:{color:colors.textSecondary,...typography.body},inlineAction:{minHeight:48,flexDirection:'row',alignItems:'center',alignSelf:'flex-start',gap:spacing.xs},inlineActionText:{color:colors.body,...typography.label},
  nextSection:{paddingTop:spacing.xl},actionIndex:{minHeight:82,flexDirection:'row',alignItems:'center',gap:spacing.sm,marginTop:spacing.sm,paddingHorizontal:spacing.md,borderRadius:radius.lg,backgroundColor:colors.surfaceSubtle},actionIcon:{width:40,height:40,alignItems:'center',justifyContent:'center',borderRadius:20},actionCopy:{flex:1},actionTitle:{color:colors.text,...typography.label},actionDescription:{marginTop:2,color:colors.textMuted,...typography.caption},
  feedbackLedger:{marginTop:spacing.xl,padding:spacing.lg,borderRadius:radius.lg,backgroundColor:colors.surfaceSubtle},feedbackTitle:{maxWidth:420,color:colors.text,...typography.sectionTitle},feedbackOptions:{flexDirection:'row',flexWrap:'wrap',gap:spacing.xs,marginTop:spacing.md},feedbackOption:{minHeight:44,flexGrow:1,alignItems:'center',justifyContent:'center',paddingHorizontal:spacing.sm,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,backgroundColor:colors.surface},feedbackOptionText:{color:colors.textSecondary,...typography.caption,fontWeight:'600'},savedFeedback:{marginTop:spacing.lg,color:colors.success,...typography.caption},
  recentSection:{marginTop:spacing.xxl},viewAll:{color:colors.primary,...typography.caption,fontWeight:'600'},recentIndex:{marginTop:spacing.xs,borderRadius:radius.lg,backgroundColor:colors.surfaceSubtle,overflow:'hidden'},recentRow:{minHeight:60,flexDirection:'row',alignItems:'center',gap:spacing.sm,paddingHorizontal:spacing.md,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.divider},recentDot:{width:7,height:7,borderRadius:4,backgroundColor:colors.primary},recentDate:{width:76,color:colors.text,...typography.caption,fontWeight:'600'},recentValue:{flex:1,color:colors.textSecondary,...typography.caption},
  sheetOverlay:{flex:1,justifyContent:'flex-end',backgroundColor:colors.scrim},bottomSheet:{paddingHorizontal:layout.horizontalPadding,paddingTop:spacing.sm,borderTopLeftRadius:radius.sheet,borderTopRightRadius:radius.sheet,backgroundColor:colors.surface},grabber:{width:36,height:4,alignSelf:'center',marginBottom:spacing.xl,backgroundColor:colors.border},sheetTitle:{color:colors.text,...typography.title},sheetRow:{minHeight:56,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:colors.divider},sheetLabel:{color:colors.textMuted,...typography.caption},sheetValue:{maxWidth:'62%',color:colors.text,...typography.caption,fontWeight:'700',textAlign:'right'},sheetActions:{flexDirection:'row',gap:spacing.sm,marginTop:spacing.lg},sheetSecondaryButton:{flex:1,minHeight:52,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:colors.border,borderRadius:radius.md},sheetSecondaryText:{color:colors.text,...typography.label},sheetPrimaryButton:{flex:1,minHeight:52,alignItems:'center',justifyContent:'center',borderRadius:radius.md,backgroundColor:colors.primary},sheetPrimaryText:{color:colors.white,...typography.label},
  loadingContent:{flex:1,paddingHorizontal:layout.horizontalPadding,paddingTop:spacing.xl},loadingHeader:{width:104,height:16,borderRadius:radius.sm,backgroundColor:colors.surfaceStrong},loadingTitle:{width:'72%',height:76,marginTop:spacing.xxl,borderRadius:radius.md,backgroundColor:colors.surfaceStrong},loadingBody:{width:'92%',height:44,marginTop:spacing.md,borderRadius:radius.md,backgroundColor:colors.surfaceStrong},loadingCard:{height:58,marginTop:spacing.xl,borderRadius:radius.md,backgroundColor:colors.surfaceStrong},errorContent:{flex:1,justifyContent:'center',paddingHorizontal:layout.horizontalPadding},
});
