import { useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import NavigationBackButton from '@/components/navigation-back-button';
import type { RoutineEffect } from '@/domain/wellness';
import { wellnessApi } from '@/services/wellness-api';
import { styles } from './feedback.styles';

const EFFECTS: Array<{ id: RoutineEffect; icon: string; label: string }> = [{ id:'better',icon:'↗',label:'한결 편해요'},{id:'same',icon:'→',label:'비슷해요'},{id:'worse',icon:'↘',label:'더 불편해요'}];
export default function RoutineFeedbackScreen() {
  const router=useRouter(); const insets=useSafeAreaInsets(); const { routineId='' }=useLocalSearchParams<{routineId?:string}>();
  const [effect,setEffect]=useState<RoutineEffect|null>(null); const [level,setLevel]=useState<number|null>(null); const [memo,setMemo]=useState(''); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
  const submit=async()=>{ if(!effect||!level)return; setSaving(true);setError('');try{const result=await wellnessApi.saveRoutineFeedback({routineId,effect,discomfortLevel:level,memo:memo.trim()}); if(result.shouldShowSignal) router.replace('/safety/signal'); else router.dismissTo('/(tabs)/home');}catch{setError('피드백을 저장하지 못했어요. 다시 시도해 주세요.');setSaving(false);}};
  return <SafeAreaView edges={['top']} style={styles.screen}><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={styles.flex}><View style={styles.topBar}><NavigationBackButton accessibilityLabel="루틴 완료로 돌아가기" fallbackHref="/(tabs)/home"/><Text style={styles.topTitle}>효과 피드백</Text><View style={styles.spacer}/></View><ScrollView contentContainerStyle={[styles.content,{paddingBottom:insets.bottom+120}]} keyboardShouldPersistTaps="handled"><Text style={styles.eyebrow}>루틴 후 체크</Text><Text style={styles.title}>지금 몸은{`\n`}어떻게 느껴지나요?</Text><Text style={styles.description}>짧은 피드백이 다음 루틴 추천에 반영돼요.</Text><Text style={styles.sectionTitle}>변화</Text><View style={styles.effectRow}>{EFFECTS.map(item=><Pressable accessibilityRole="button" accessibilityState={{selected:effect===item.id}} key={item.id} onPress={()=>setEffect(item.id)} style={[styles.effectCard,effect===item.id&&styles.selected]}><Text style={[styles.effectIcon,effect===item.id&&styles.selectedText]}>{item.icon}</Text><Text style={[styles.effectText,effect===item.id&&styles.selectedText]}>{item.label}</Text></Pressable>)}</View><Text style={styles.sectionTitle}>현재 불편 강도</Text><View style={styles.levelRow}>{[1,2,3,4,5].map(value=><Pressable accessibilityLabel={`불편 강도 ${value}단계`} accessibilityRole="button" accessibilityState={{selected:level===value}} key={value} onPress={()=>setLevel(value)} style={[styles.level,level===value&&styles.selectedLevel]}><Text style={[styles.levelText,level===value&&styles.selectedText]}>{value}</Text></Pressable>)}</View><View style={styles.scaleLabels}><Text style={styles.scaleText}>거의 없음</Text><Text style={styles.scaleText}>매우 불편</Text></View><Text style={styles.sectionTitle}>메모 <Text style={styles.optional}>(선택)</Text></Text><TextInput accessibilityLabel="루틴 효과 메모" maxLength={200} multiline onChangeText={setMemo} placeholder="어떤 점이 달라졌는지 남겨보세요." placeholderTextColor="#A4A9B2" style={styles.input} value={memo}/>{error?<Text style={styles.error}>{error}</Text>:null}</ScrollView><View style={[styles.action,{paddingBottom:Math.max(insets.bottom,12)}]}><Pressable accessibilityRole="button" disabled={!effect||!level||saving} onPress={()=>void submit()} style={[styles.button,(!effect||!level||saving)&&styles.disabled]}>{saving?<ActivityIndicator color="#FFF"/>:<Text style={styles.buttonText}>피드백 저장하기</Text>}</Pressable></View></KeyboardAvoidingView></SafeAreaView>;
}
