import { StyleSheet } from 'react-native';
import { colors, layout, motion, radius, spacing, typography } from '@/theme/tokens';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.surface },
  topBar: { width: '100%', maxWidth: layout.maxContentWidth, minHeight: 64, alignSelf: 'center', flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing.xs, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.divider },
  progressWrap: { flex: 1, paddingHorizontal: spacing.md },
  topSpacer: { width: layout.minTouch },
  scrollContent: { width: '100%', maxWidth: layout.maxContentWidth, alignSelf: 'center', paddingBottom: spacing.xl },
  header: { paddingHorizontal: layout.horizontalPadding, paddingTop: spacing.lg },
  title: { maxWidth: 520, color: colors.text, ...typography.display },
  description: { maxWidth: 470, marginTop: spacing.sm, color: colors.textSecondary, ...typography.body },
  sections: { marginTop: spacing.xxl },
  section: { paddingHorizontal: layout.horizontalPadding, paddingVertical: spacing.xl, borderTopWidth: 1, borderTopColor: colors.divider },
  sectionTitle: { color: colors.text, ...typography.sectionTitle },
  optional: { color: colors.textMuted, ...typography.caption, fontWeight: '600' },
  sectionDescription: { marginTop: spacing.xxs, marginBottom: spacing.md, color: colors.textMuted, ...typography.caption },
  timeRow: { minHeight: 58, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: colors.divider },
  timeLabel: { flex: 1, color: colors.textSecondary, ...typography.label },
  timeValue: { marginRight: spacing.sm, color: colors.brand, fontSize: 16, fontWeight:'700' },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs },
  chip: { minWidth: 72, minHeight: layout.minTouch, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.xs, paddingHorizontal: spacing.md, borderWidth: 1, borderColor: colors.border, borderRadius: radius.sm },
  selectedChip: { borderColor: colors.body, backgroundColor: colors.bodySoft },
  chipText: { color: colors.textSecondary, ...typography.label },
  selectedChipText: { color: colors.body },
  activityList: { borderTopWidth: 1, borderTopColor: colors.divider },
  activityRow: { minHeight: 76, flexDirection: 'row', alignItems: 'center', gap: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.divider },
  selectedActivityRow: { borderBottomColor: colors.brand },
  radio: { width: 22, height: 22, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: 11 },
  selectedRadio: { borderColor: colors.brand },
  radioDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: colors.brand },
  activityCopy: { flex: 1 },
  activityTitle: { color: colors.textSecondary, ...typography.label },
  selectedActivityTitle: { color: colors.text },
  activityDescription: { marginTop: spacing.xxs, color: colors.textMuted, ...typography.caption },
  notice: { flexDirection: 'row', gap: spacing.sm, marginHorizontal: layout.horizontalPadding, marginTop: spacing.lg },
  noticeLine: { width: 3, backgroundColor: colors.recovery },
  noticeText: { flex: 1, color: colors.textSecondary, ...typography.caption },
  errorText: { marginHorizontal: layout.horizontalPadding, marginTop: spacing.md, color: colors.danger, ...typography.caption },
  footer: { width: '100%', maxWidth: layout.maxContentWidth, alignSelf: 'center', paddingHorizontal: layout.horizontalPadding, paddingTop: spacing.sm, backgroundColor: colors.surface },
  nextButton: { minHeight: layout.ctaHeight, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colors.primary },
  nextButtonText: { color: colors.primaryText, fontSize: 16, fontWeight:'700' },
  disabledButton: { backgroundColor: colors.disabled },
  modalOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: colors.scrim },
  pickerSheet: { paddingBottom: spacing.xl, borderTopLeftRadius: radius.sheet, borderTopRightRadius: radius.sheet, backgroundColor: colors.surface },
  pickerHandle: { width: 38, height: 4, alignSelf: 'center', marginTop: spacing.sm, borderRadius: 2, backgroundColor: colors.border },
  pickerHeader: { minHeight: 60, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: layout.horizontalPadding, borderBottomWidth: 1, borderBottomColor: colors.divider },
  pickerTitle: { color: colors.text, ...typography.sectionTitle },
  doneButton: { minWidth: layout.minTouch, minHeight: layout.minTouch, alignItems: 'flex-end', justifyContent: 'center' },
  doneText: { color: colors.brand, ...typography.label },
  pressed: { opacity: motion.pressOpacity },
});
