import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 24,
  },
  backButton: {
    alignSelf: 'flex-start',
    width: 56,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backIcon: {
    color: '#18201C',
    fontSize: 34,
    fontWeight: '300',
    lineHeight: 36,
  },
  header: {
    paddingHorizontal: 24,
    paddingTop: 20,
  },
  title: {
    color: '#18201C',
    fontSize: 26,
    fontWeight: '700',
    letterSpacing: -0.9,
    lineHeight: 36,
  },
  description: {
    marginTop: 11,
    color: '#46514A',
    fontSize: 14.5,
    lineHeight: 24,
  },
  rows: {
    marginTop: 24,
    paddingHorizontal: 24,
  },
  sectionLabel: { marginTop: 22, marginBottom: 8, color: '#46514A', fontSize: 13, fontWeight: '700' },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: { minWidth: 62, minHeight: 44, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16, borderWidth: 1, borderColor: '#D8DCD6', borderRadius: 22 },
  selectedChip: { borderColor: '#285C4D', backgroundColor: '#E6EEE9' },
  chipText: { color: '#46514A', fontSize: 14, fontWeight: '700' },
  selectedChipText: { color: '#285C4D' },
  segment: { flexDirection: 'row', borderTopWidth: 1, borderBottomWidth: 1, borderColor: '#ECEEEC' },
  segmentItem: { flex: 1, minHeight: 48, alignItems: 'center', justifyContent: 'center' },
  selectedSegmentItem: { borderBottomWidth: 2, borderBottomColor: '#176B52' },
  segmentText: { color: '#6E776F', fontSize: 14, fontWeight: '700' },
  selectedSegmentText: { color: '#18201C' },
  row: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 2,
    borderTopWidth: 1,
    borderTopColor: '#E9EAE5',
  },
  rowLabel: {
    flex: 1,
    color: '#18201C',
    fontSize: 15.5,
    fontWeight: '600',
  },
  rowValue: {
    marginRight: 8,
    color: '#285C4D',
    fontSize: 15,
    fontWeight: '700',
  },
  chevron: {
    color: '#C3C7CE',
    fontSize: 27,
    fontWeight: '300',
    lineHeight: 24,
  },
  notice: {
    marginHorizontal: 24,
    marginTop: 20,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#ECEEEC',
  },
  noticeText: {
    color: '#46514A',
    fontSize: 13,
    lineHeight: 22,
  },
  footer: {
    paddingHorizontal: 24,
    paddingTop: 10,
    paddingBottom: 20,
    backgroundColor: '#FFFFFF',
  },
  nextButton: {
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: '#176B52',
  },
  nextButtonText: {
    color: '#FFFFFF',
    fontSize: 16.5,
    fontWeight: '700',
  },
  disabledButton: { opacity: 0.5 },
  modalOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(23,25,28,0.38)' },
  pickerSheet: { paddingBottom: 24, borderTopLeftRadius: 24, borderTopRightRadius: 24, backgroundColor: '#FFFFFF' },
  pickerHeader: { minHeight: 56, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 24, borderBottomWidth: 1, borderBottomColor: '#E9EAE5' },
  pickerTitle: { color: '#18201C', fontSize: 16, fontWeight: '800' },
  doneButton: { minWidth: 44, minHeight: 44, alignItems: 'flex-end', justifyContent: 'center' },
  doneText: { color: '#285C4D', fontSize: 15, fontWeight: '800' },
  pressed: {
    opacity: 0.55,
  },
});
