import { StyleSheet } from 'react-native';
import { colors, layout, motion, radius, spacing, typography } from '@/theme/tokens';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.surface },
  topBar: { width: '100%', maxWidth: layout.maxContentWidth, minHeight: 64, alignSelf: 'center', flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing.xs },
  progressWrap: { flex: 1, paddingHorizontal: spacing.md },
  topSpacer: { width: layout.minTouch },
  scrollContent: { width: '100%', maxWidth: layout.maxContentWidth, alignSelf: 'center', paddingBottom: spacing.xl },
  header: { paddingHorizontal: layout.horizontalPadding, paddingTop: spacing.lg },
  title: { maxWidth: 520, color: colors.text, ...typography.display },
  description: { maxWidth: 480, marginTop: spacing.sm, color: colors.textSecondary, ...typography.body },
  list: { marginTop: spacing.xxl, paddingHorizontal: layout.horizontalPadding },
  allRow: { minHeight: 76, flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingHorizontal: spacing.md, borderRadius: radius.lg, backgroundColor: colors.primarySoft },
  allCopy: { flex: 1 },
  allTitle: { color: colors.text, ...typography.label },
  allDescription: { marginTop: spacing.xxs, color: colors.textMuted, ...typography.caption },
  item: { borderBottomWidth: 1, borderBottomColor: colors.divider },
  itemTop: { minHeight: 88, flexDirection: 'row', alignItems: 'stretch' },
  itemToggle: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingVertical: spacing.md },
  itemCopy: { flex: 1 },
  itemTitle: { color: colors.text, ...typography.label },
  itemSummary: { marginTop: spacing.xxs, color: colors.textMuted, ...typography.caption },
  required: { color: colors.brand, ...typography.caption, fontWeight:'700' },
  optional: { color: colors.textMuted, ...typography.caption, fontWeight: '700' },
  detailToggle: { width: layout.minTouch, alignItems: 'flex-end', justifyContent: 'center' },
  checkbox: { width: 26, height: 26, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: radius.sm, backgroundColor: colors.surface },
  checkedBox: { borderColor: colors.brand, backgroundColor: colors.brand },
  details: { gap: spacing.xs, paddingVertical: spacing.md, paddingLeft: 42, paddingRight: spacing.md, borderTopWidth: 1, borderTopColor: colors.divider, backgroundColor: colors.surfaceSubtle },
  detailText: { color: colors.textSecondary, ...typography.caption },
  safetyNote: { flexDirection: 'row', gap: spacing.sm, marginHorizontal: layout.horizontalPadding, marginTop: spacing.xl },
  safetyLine: { width: 3, backgroundColor: colors.recovery },
  safetyText: { flex: 1, color: colors.textSecondary, ...typography.caption },
  footer: { width: '100%', maxWidth: layout.maxContentWidth, alignSelf: 'center', paddingHorizontal: layout.horizontalPadding, paddingTop: spacing.sm, backgroundColor: colors.surface },
  continueButton: { minHeight: layout.ctaHeight, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colors.primary },
  continueText: { color: colors.white, fontSize: 16, fontWeight:'700' },
  disabledButton: { backgroundColor: colors.disabled },
  disabledText: { color: colors.disabledText },
  pressed: { opacity: motion.pressOpacity },
});
