import { StyleSheet } from 'react-native';
import { colors, layout, motion, radius, spacing, typography } from '@/theme/tokens';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.surface },
  topBar: { width: '100%', maxWidth: layout.maxContentWidth, minHeight: 64, alignSelf: 'center', flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing.xs },
  progressWrap: { flex: 1, paddingHorizontal: spacing.md },
  topSpacer: { width: layout.minTouch },
  scrollContent: { width: '100%', maxWidth: layout.maxContentWidth, alignSelf: 'center', paddingBottom: spacing.xl },
  header: { paddingHorizontal: layout.horizontalPadding, paddingTop: spacing.lg },
  title: { maxWidth: 540, color: colors.text, ...typography.display },
  description: { maxWidth: 480, marginTop: spacing.sm, color: colors.textSecondary, ...typography.body },
  providerSection: { marginTop: spacing.xxl, marginHorizontal: layout.horizontalPadding, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.divider },
  providerHeader: { minHeight: 104, flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingVertical: spacing.md },
  selectedProvider: { borderBottomWidth: 3, borderBottomColor: colors.brand },
  providerIcon: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.brand, borderRadius: radius.md },
  selectedProviderIcon: { backgroundColor: colors.brand },
  providerCopy: { flex: 1 },
  providerName: { color: colors.text, ...typography.sectionTitle },
  providerDescription: { marginTop: spacing.xxs, color: colors.textMuted, ...typography.caption },
  connectionState: { minWidth: 54, minHeight: 32, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: radius.sm },
  connectionStateSelected: { borderColor: colors.brand, backgroundColor: colors.brandSoft },
  connectionStateText: { color: colors.textSecondary, ...typography.caption, fontWeight: '700' },
  connectionStateTextSelected: { color: colors.brand },
  permissionList: { paddingVertical: spacing.lg },
  permissionHeading: { marginBottom: spacing.xs, color: colors.textMuted, ...typography.caption, fontWeight: '700' },
  permissionRow: { minHeight: 62, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderTopWidth: 1, borderTopColor: colors.divider },
  permissionCheck: { width: 24, alignItems: 'flex-start' },
  permissionCopy: { flex: 1 },
  permissionLabel: { color: colors.text, ...typography.label },
  permissionDescription: { marginTop: spacing.xxs, color: colors.textMuted, ...typography.caption },
  readOnly: { color: colors.recovery, ...typography.caption, fontWeight: '700' },
  privacy: { flexDirection: 'row', gap: spacing.md, marginHorizontal: layout.horizontalPadding, marginTop: spacing.xl, paddingVertical: spacing.md, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.divider },
  privacyCopy: { flex: 1 },
  privacyTitle: { color: colors.text, ...typography.label },
  privacyText: { marginTop: spacing.xxs, color: colors.textSecondary, ...typography.caption },
  errorText: { marginHorizontal: layout.horizontalPadding, marginTop: spacing.md, color: colors.danger, ...typography.caption },
  footer: { width: '100%', maxWidth: layout.maxContentWidth, alignSelf: 'center', paddingHorizontal: layout.horizontalPadding, paddingTop: spacing.sm, backgroundColor: colors.surface },
  laterButton: { minHeight: 48, alignItems: 'center', justifyContent: 'center' },
  laterText: { color: colors.textSecondary, ...typography.label },
  startButton: { minHeight: layout.ctaHeight, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colors.primary },
  startText: { color: colors.white, fontSize: 16, fontWeight:'700' },
  disabledButton: { backgroundColor: colors.disabled },
  pressed: { opacity: motion.pressOpacity },
});
