import { StyleSheet } from 'react-native';
import { colors, layout, motion, radius, spacing, typography } from '@/theme/tokens';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.surface }, content: { width: '100%', maxWidth: layout.maxContentWidth, alignSelf: 'center', paddingBottom: spacing.xxl, backgroundColor: colors.canvas }, center: { minHeight: 500, alignItems: 'center', justifyContent: 'center' }, pressed: { opacity: motion.pressOpacity },
  header: { minHeight: 76, justifyContent: 'center', paddingHorizontal: layout.horizontalPadding, backgroundColor: colors.surface }, headerTitle: { color: colors.text, fontSize: 20, lineHeight: 26, fontWeight: '700', letterSpacing: -.7 },
  identity: { minHeight: 90, flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 14, paddingHorizontal: layout.horizontalPadding, backgroundColor: colors.surface }, avatar: { width: 52, height: 52, alignItems: 'center', justifyContent: 'center', borderRadius: radius.pill, backgroundColor: colors.primarySoft }, avatarText: { color: colors.primaryText, fontSize: 20, lineHeight: 28, fontWeight: '700' }, identityCopy: { flex: 1 }, name: { color: colors.text, fontSize: 17, lineHeight: 24, fontWeight: '700', letterSpacing: -.5 }, email: { marginTop: 2, color: colors.textMuted, ...typography.caption },
  stats: { flexDirection: 'row', marginHorizontal: layout.horizontalPadding, marginBottom: 10, overflow: 'hidden', borderRadius: radius.lg, backgroundColor: colors.surfaceSubtle }, stat: { flex: 1, minHeight: 74, alignItems: 'center', justifyContent: 'center', borderRightWidth: StyleSheet.hairlineWidth, borderColor: colors.divider }, statValue: { color: colors.text, fontSize: 20, lineHeight: 27, fontWeight: '700', letterSpacing: -.7, fontVariant: ['tabular-nums'] }, statLabel: { marginTop: 3, color: colors.textMuted, fontSize: 11, lineHeight: 16, fontWeight: '600', textAlign: 'center' },
  section: { marginTop: 10, paddingTop: 16, paddingHorizontal: layout.horizontalPadding, backgroundColor: colors.surface }, sectionTitle: { marginBottom: 6, color: colors.textMuted, ...typography.caption, fontWeight: '700' }, menuGroup: { backgroundColor: colors.surface }, menu: { minHeight: 56, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 0, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: colors.divider }, menuIndex: { display: 'none' }, menuCopy: { flex: 1 }, menuTitleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.sm }, menuLabel: { color: colors.text, fontSize: 15, lineHeight: 22, fontWeight: '600', letterSpacing: -.38 }, menuValue: { color: colors.textMuted, ...typography.caption, fontWeight: '700' }, menuDescription: { display: 'none' }, version: { marginTop: 20, color: colors.textMuted, fontSize: 10.5, lineHeight: 15, fontWeight: '600', textAlign: 'center' },
});
