import { useCallback } from 'react';
import { ActivityIndicator, Pressable, ScrollView, Text, View } from 'react-native';
import { useFocusEffect, useRouter } from 'expo-router';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppIcon, type AppIconName } from '@/components/app-icon';
import StateNotice from '@/components/state-notice';
import type { UserProfileSummary } from '@/domain/wellness';
import { useAsyncData } from '@/hooks/use-async-data';
import { wellnessApi } from '@/services/wellness-api';
import { colors } from '@/theme/tokens';
import { styles } from './me.styles';
export default function MeScreen(){const router=useRouter();const insets=useSafeAreaInsets();const{data,error,isLoading,reload}=useAsyncData<UserProfileSummary|null>(wellnessApi.getUserProfile,null);useFocusEffect(useCallback(()=>{void reload().catch(()=>undefined)},[reload]));return <SafeAreaView edges={['top']} style={styles.screen}><ScrollView contentContainerStyle={[styles.content,{paddingBottom:insets.bottom+110}]}>{isLoading?<View style={styles.center}><ActivityIndicator color={colors.primary}/></View>:error||!data?<StateNotice actionLabel="다시 시도" description="네트워크 상태를 확인한 뒤 다시 시도해 주세요." icon="!" onAction={()=>void reload().catch(()=>undefined)} title="내 정보를 불러오지 못했어요" tone="error"/>:<><Text style={styles.eyebrow}>내 웰니스</Text><Text style={styles.pageTitle}>나</Text><View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>{data.name.slice(0,1)}</Text></View><View style={styles.profileCopy}><Text style={styles.name}>{data.name}</Text><Text style={styles.email}>{data.email}</Text><Text style={styles.joined}>{data.joinedLabel} 함께하고 있어요</Text></View></View><View style={styles.stats}><Stat label="기록한 날" value={`${data.recordDays}일`}/><View style={styles.divider}/><Stat label="완료 루틴" value={`${data.routineCount}회`}/></View><Text style={styles.sectionTitle}>연결 및 알림</Text><Menu icon="heart" label="건강 데이터" onPress={()=>router.push('/settings/health')} value={data.healthConnected?'연결됨':'연결 안 됨'} valueTone={data.healthConnected?'good':'neutral'}/><Menu icon="bell" label="알림 설정" onPress={()=>router.push('/settings/notifications')} value={data.notificationEnabled?'사용 중':'꺼짐'}/><Text style={styles.sectionTitle}>내 기록과 정보</Text><Menu icon="document" label="기록 요약 만들기" onPress={()=>router.push('/reports/setup')}/><Menu icon="check" label="동의·데이터 관리" onPress={()=>router.push('/settings/data')}/><Menu icon="person" label="계정 관리" onPress={()=>router.push('/settings/account')}/><Menu icon="info" label="서비스 정보·문의" onPress={()=>router.push('/settings/info')}/><Menu icon="info" label="빈 상태·예외 안내" onPress={()=>router.push('/empty-states')}/><Text style={styles.version}>몸기록 · 개발 환경</Text></>}</ScrollView></SafeAreaView>}
function Stat({label,value}:{label:string;value:string}){return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>}
function Menu({icon,label,onPress,value,valueTone='neutral'}:{icon:AppIconName;label:string;onPress:()=>void;value?:string;valueTone?:'neutral'|'good'}){return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={({pressed})=>[styles.menu,pressed&&styles.pressed]}><View style={styles.menuIcon}><AppIcon color={colors.primary} name={icon} size={19}/></View><Text style={styles.menuLabel}>{label}</Text>{value?<Text style={[styles.menuValue,valueTone==='good'&&styles.good]}>{value}</Text>:null}<AppIcon color={colors.textMuted} name="chevron-right" size={19}/></Pressable>}
